### ISSUE TITLE
Discussion: Implement server-side static file processing plumbing

### ISSUE THREAD

**Issue by rkneufeld** [pedestal/pedestal#123]
We've yet to implement this feature. Let's discuss what's necessary here (cache-busting, sass/scss compilation, etc..)

**Comment by ohpauleez** [comment]
This is an old issue, but I recently had a conversation about it.  Sometime soon, I'll put in hooks to enable this tooling, but will not provide any of the tooling within Pedestal.

**Comment by ohpauleez** [comment]
I think this issue is resolved at this point.  I've seen community projects integrate Pedestal and asset pipelines without issues.  If someone has a specific asset-serving issue, please open a new issue.  Thanks all!
