### ISSUE TITLE
Add SSL support for embedded tomcat

### ISSUE THREAD

**Issue by rkneufeld** [pedestal/pedestal#124]
As with jetty, we need to support SSL for embedded tomcat.

See http://www.copperykeenclaws.com/adding-an-https-connector-to-embedded-tomcat-7/

**Comment by davidsiefert** [comment]
I'd like to give this a shot at implementing this.  It looks like 0.4.x is set to tomcat-8.x, is that the desired support?  (article ref's 7)

**Comment by ohpauleez** [comment]
@davidsiefert Thanks for stepping up to the plate!  Tomcat 8.0.24 would be desired.  If there's a particular problem with the latest release, another Tomcat 8.0.x release would be acceptable.

**Comment by ohpauleez** [comment]
This is now on master.  Thanks so much @yokolet
