### ISSUE TITLE
Terse route format has sharp edges

### ISSUE THREAD

**Issue by rkneufeld** [pedestal/pedestal#128]
From @mtnygard:

> The difference between when to use a symbol, vector, or function are explained in the docs, but in a way that only makes sense after you already understand it.
>
> It's very easy to create a syntax that looks right but results in compile-time exceptions ("No implementation of method: :expand-verb-action of protocol: #'io.pedestal.service.http.route.definition/ExpandableVerbAction found for class".)
>
> We either need to improve the documentation with more annotated examples, including simple cases, or we need to reconsider this data structure that doesn't act like a data structure.

**Comment by ddeaguiar** [comment]
I'd also like to clarify that the app may appear to work from a test and local run perspective but fails when you `lein compile :all` or `lein uberjar`. Here's an [example app](https://github.com/ddeaguiar/pedestal-routing-demonstration) demonstrating this.

**Comment by ohpauleez** [comment]
@ddeaguiar - your AOT error isn't related to routing, it's most likely related to the use of `defhandler`.  You should prefer to use the new Interceptor API instead.

**Comment by ddeaguiar** [comment]
@ohpauleez, thanks for the quick feedback! I will try that.

**Comment by mtnygard** [comment]
I think that we addressed this in PR #394. I worked over the parsing for terse routing syntax to provide some more friendly error messages for common errors. Recommend we close this issue.

**Comment by ohpauleez** [comment]
Yep, this has been addressed with better messaging and route-formats that are less prone to these issues.
