### ISSUE TITLE
Http kit support

### ISSUE THREAD

**Issue by kirillsalykin** [pedestal/pedestal#179]
Can be support for http-kit added?
Its almost same as jettty.
http://http-kit.org/

**Comment by cocodrino** [comment]
would be possible some vertx support in a future?..vertx provide many benefits: it's really fast,builded for microservices and allow interop between jvm languages (which is a big plus!)...

http://vert-x3.github.io/index.html

I think than support vertx would be more difficult than http-kit or any other clojure http server but would be a big step...

**Comment by mtnygard** [comment]
@cocodrino I added #399 to address vert.x, so this issue will remain about http-kit.

**Comment by ohpauleez** [comment]
This is now possible with the new chain providers on Master.  There is no http-kit support out of the box, nor are there plans to ship with support, but someone from the community is free to put Pedestal on top of http-kit if they like.

See this example of running [Pedestal against Jetty directly](https://github.com/pedestal/pedestal/blob/master/samples/fast-pedestal/src/fast_pedestal/fasterjetty_service.clj) or the very basic [chain provider sample](https://github.com/pedestal/pedestal/tree/master/samples/chain-providers)
