### ISSUE TITLE
Routes with nested variables routes don't work correctly

### ISSUE THREAD

**Issue by rkneufeld** [pedestal/pedestal#237]
From Sarkis K on the mailing list:

> Notice how "/:resource/:id" fails.
> Any ideas / suggestions?
>
> atest.service=> (defroutes routes [[["/:resource" {:get get-index-page}]]])
> #'atest.service/routes
atest.service=> (defroutes routes [[["/:resource/:id" {:get get-index-page}]]])
> CompilerException java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Keyword, compiling:(form-init3002751927199362507.clj:1:1)
>
> atest.service=> (defroutes routes [[["/resource/:id/:another" {:get get-index-page}]]])
#'atest.service/routes

More info from Ryan:

> This seems to be a bug with the path-regex function on line 79 of route.clj. Basically, path-parts is a vector, `[:resource :id]`, and the let tries to treat :resource like a sequence

And Tim:

> All path segments have to start with '/'. If you start the tree with a root URL, just '/', then a child path '/foo', they get concatenated as '//foo'. Then split at /, so the path is a vector with an empty string in the first position. When we reassemble a url with join, we have to special case the leading / so we don't end up with //foo.

**Comment by tcrayford** [comment]
This is blocking my experimenting with pedestal. Any pointers into fixing it? (I'm happy diving into the code, but I'm not that familiar with pedestal's codebase yet). I'm porting over an older app with route structures that depend on this kind of nesting.

The same bug affects paths that start with a param part, then have a static part right? (I hit this as well):

```clj
"/:foo/bar"
```

**Comment by tcrayford** [comment]
A failing test: the following throws an exception

```clojure
(deftest allows-nested-path-params
  (is (= nil
         (expand-routes '[[["/:resource/thing" {:get :int}]
                        ["/:resource/:thing" :int]]]))))
```

**Comment by rkneufeld** [comment]
Hmm, we may have to check with @ohpauleez on how to fix this. I'm not super-familiar with the routing either. On top of that, there are plans to rewrite the router as a Trie-based router sometime in the near future.

**Comment by ohpauleez** [comment]
I would suggest just putting some path segment before the `/:resource/:thing` piece.  This used to bother me a lot, but I have come to the conclusion the `/:resource/:entity` is a bit of an anti-pattern - you almost always want that mapping in a specific context, and almost always regret not having the extra segment further down the line in a long-lived project.

That said, Brenton Ashworth is hard at work on the new router code that I had started designing awhile back.  The updates to the router will also update the conversion of the routes into their route maps, which should make this bug go away.

That said, if this is blocking a larger project for you, there are a few options:

 * Write your own route-table parser using the Pedestal functions (and correcting the bug)
 * Submitting a patch for the URL splitting and joining piece to correctly handle this case
 * Explain to me the larger situation *off list/ticket/twitter* and see if I can get a fix in quicker for you

**Comment by tcrayford** [comment]
@ohpauleez : I was looking at switching to pedestal for the app I run (http://yellerapp.com), which is ~2 years old (the codebase is anyway). I agree that style is an antipattern, but I really don't wanna break existing routes (given that I send links into users emails and some of them click older emails from weeks/months/years ago).

It's not a huge rush, I think waiting for the new router code is probably the best idea (I don't wanna commit a bunch of effort to fixing it whilst the router's being rewritten anyway). I'm not full-time on that project, and there are always user facing features to work on ;)

Thanks, and sorry for being an demanding open source user :/ Pedestal has really good docs, and I've been pretty impressed with it so far (apart from that minor hiccup).
