### ISSUE TITLE
Service should always keywordize keys in :params key of context

### ISSUE THREAD

**Issue by rkneufeld** [pedestal/pedestal#240]
From #238, in a request context POST `:params` keys are strings, while GET keys are keywords.

After talking with @timewald we believe it is reasonable going forward for 0.3.x to *always* return keywords on the `:params` key of context.

**Acceptance Criteria:**

* [ ] `:params` is always keywordized. This can probably be accomplished by adding  [`middlewares/keyword-params`](https://github.com/pedestal/pedestal/blob/0719c9f77b12b25352a3c5a838273eedfa24798b/service/src/io/pedestal/service/http/ring_middlewares.clj#L89-L91) to [default-`interceptors`](https://github.com/pedestal/pedestal/blob/0719c9f77b12b25352a3c5a838273eedfa24798b/service/src/io/pedestal/service/http.clj#L107-L154)
* [ ] New tests are added to enforce this behavior. Old tests are updated.
* [ ] `:form-params` and `:query-params` behavior is not unilaterally changed.

**Comment by mtnygard** [comment]
I'm looking into the second and third acceptance criteria here. At the moment, we have body_params_test.clj that only exercises the body-params interceptor. There don't seem to be any tests that exercise a form post through the whole chain of default interceptors. Am I missing something?

Currently thinking to add a new test file about form posts. Would test :params and :form-params on a "real" app, similar to the construct in secure_headers_test.clj. Does this make sense?

**Comment by ohpauleez** [comment]
Confirmed - I don't see any tests around param behaviors, and most of the tests exercise just their localized functionality (building custom interceptor chains).

I agree - let's add a new test file about params against a "real" app, that exercises all param behavior (form posts, query strings, etc.)

**Comment by ohpauleez** [comment]
This won't step on any other changes, and should be done with a default interceptor.  Green light to keep going.
