### ISSUE TITLE
params should include path-params

### ISSUE THREAD

**Issue by chenfisher** [pedestal/pedestal#241]
I believe path-params should be included in the params map

Currenly,query strings and form params are included in params map but not path-params. I don't see why not.

Thanks

**Comment by vemv** [comment]
Hi there,

I think I encountered this gotcha. But the documentation (http://pedestal.io/reference/request-map) doesn't say `:path-params` is excluded from `:params`:

`:params | Y | Map of keyword or String → String | Merged map of path, query, and request parameters.`

Is the documentation incorrect?
