### ISSUE TITLE
Have `expand-abstract-constraint` dispatch on meta value

### ISSUE THREAD

**Issue by frankiesardo** [pedestal/pedestal#278]
A proposed tweak that can make route definition more flexible. If the terse route expansion could be dispatched on the meta value of the vector or map (instead of the hardcoded `:interceptors` and `:constraints`) , the the user would be able to insert his/her own tagged maps and vectors inside the route definition and compute some interesting values on the `routing-tree-node`. Of course for it to be useful the verbose expansion has to keep the custom keys generated in the previous step.
I see this as an easy and idiomatic way to build layers on top of pedestal's route definition, it would be nice to know what you guys think about it.

**Comment by hlship** [comment]
This issue has been open for quite some time. We apologize if it has not received
the attention it deserves; given the amount of time that has passed, we are
focusing on other urgent issues.  We are closing this issue for the meantime, please re-open 
if it is still relevant.
