### ISSUE TITLE
There should be `dev` enhanced support within Pedestal

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#309]
Given the consolidation of `service-tools` into Pedestal core, it'd be nice to have the foundational pieces of [lein-pedestal](https://github.com/ohpauleez/lein-pedestal) in a dev namespace within Pedestal.  This would ease tooling pains, and also allow developers to package up Pedestal apps from the REPL.  I'm more than happy to provide more context as needed.

**Comment by ohpauleez** [comment]
I'm holding off on this until we land the Servlet-less changes.

**Comment by briprowe** [comment]
This is interesting. I wouldn't mind getting more context on this. Maybe I could push it forward.

**Comment by ohpauleez** [comment]
The bulk of this is [sitting on master](https://github.com/pedestal/pedestal/blob/master/service-tools/src/io/pedestal/service_tools/war.clj).  Additionally, a new "watch" function was added, that codifies the common practice for using a watched-fn as the routes function.

I will be updating lein-pedestal to use the new WAR tooling.
