### ISSUE TITLE
Pedestal should provide support for ALPN

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#311]
ALPN is the protocol negotiation scheme for HTTP2, SPDY, and others.  There should be support within the container files themselves to provide this access.  The initial implementation only needs to work for Jetty, provide a template (ie: options and functions) for other containers to follow.

An initial pass through the code indicates this is best done by allowing developers to supply additional Jetty ConnectionFactories or Connectors for a given service.  I have done some amount of the implementation already and I'm more than happy to help anyone interested get started.

See the following [StackOverflow answer](http://stackoverflow.com/questions/25035063/how-to-run-jetty-with-spdy-using-alpn) and the [Jetty API docs](http://download.eclipse.org/jetty/stable-9/apidocs/)

**Comment by ohpauleez** [comment]
This work has been started on the [alpn branch](https://github.com/pedestal/pedestal/tree/alpn).  While the connectors all seem to work, ALPN connections don't seems to receive data.

**Comment by ohpauleez** [comment]
I'm pausing this until there is a stable Jetty release with HTTP2

**Comment by ohpauleez** [comment]
The branch has been refactored and updated.  HTTP2 and ALPN are all hooked up, but ALPN seems to be bailing out after the SSL handshake.

I'd love another set of eyes on this.

**Comment by claj** [comment]
In [ring-jetty9-adapter](https://github.com/sunng87/ring-jetty9-adapter/blob/master/project.clj#L19-L20) the dependency is given to leiningen under `:boot-dependencies` with the option `:prepend true`. Could this be the cause of post SSL handshakes failure?

Also, according to the (terse)[ ALPN jetty documentation](http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-server-example), there seems to be a (reified/proxified?) ALPN.ServerProvider that makes the final protocol negotiation. Is this equivalent to the 
```
(doto (ALPNServerConnectionFactory. "h2,h2-17,h2-14,http/1.1")
                 (.setDefaultProtocol "http/1.1")))
```
at [jetty.clj row 154-155](https://github.com/pedestal/pedestal/blob/aa94e9ffcfd9b34a3a966d5d75b7d2295805e167/jetty/src/io/pedestal/http/jetty.clj#L154-L155)? I got lost among the amazing OOP abstractions somewhere.

**Comment by ohpauleez** [comment]
Thanks so much @claj - `:prepend true` was the missing gem!  The ALPN branch has been moved to a pull-request.  It should land on master soon!

**Comment by ohpauleez** [comment]
This is on master now.
