### ISSUE TITLE
The transit-json-body interceptor should be configurable

### ISSUE THREAD

**Issue by solussd** [pedestal/pedestal#313]
It would be nice if `io.pedestal.http/transit-json-body` was a function taking transit writer options and returned an interceptor. Better yet, have it also take an optional `verbose` flag to enable json-verbose. That way a transit writer map can be passed through to the transit writer function. `io.pedestal.http.body-params/body-params` already takes an optional parser map from which you can figure transit readers.

`io.pedestal.http/transit-body` could be reimplemented as: 

```clj
(def transit-body
  (transit-json-body {}))
```
for backwards compatibility.

**Comment by ohpauleez** [comment]
If you need a specific setup for transit-body, I would suggest just using your own interceptor so you can have full control over it.  Also note that while `transit-json-body` is not configurable, the transit body-params is configurable (as you noted): https://github.com/pedestal/pedestal/blob/master/service/test/io/pedestal/http/body_params_test.clj#L32-37

The rationale for this is that body writing is usually service specific, if you're not doing some form of the default writing.  It also simplifies the interceptors themselves (as well as testing them).

**Comment by solussd** [comment]
Ok. That's what I ended up doing.

**Comment by ohpauleez** [comment]
Solid!  Let me know if there are any other hiccups.  Issues and patches welcome.
