### ISSUE TITLE
url-for-routes doesn't let you specify a default app-name option value

### ISSUE THREAD

**Issue by solussd** [pedestal/pedestal#314]
This is a bit nitpicky, but:

`io.pedestal.http.routes/url-for-routes` returns a "url-for" function that can take a bunch of different options. The documentation says you can pass default options that will be merged with any provided options to the generated "url-for" function. However, this doesn't work for the `:app-name` option because it is handled specially in the arg destructuring in the "url-for" function. 

It would be nice to be able to do something like this: 
```clj
(def url-for-admin (io.pedestal.http.routes/url-for-routes routes :app-name :admin-api))
(url-for-admin ::get-a-thing {:id thing-id})
```
instead of passing the app-name every time (of course, you still could– and don't have to include it as a default). 

`url-for-routes` could be reimplemented like this to support a default `:app-name` option: 
```clj
(defn url-for-routes
  "large docstring ...<snip>"
  [routes & default-options]
  (let [{:as default-opts} default-options
        m (linker-map routes)]
    (fn [route-name & options]
      (let [{:keys [app-name] 
              :or {app-name (:app-name default-opts)}
              :as options-map} options
            route (find-route m app-name route-name)
            opts (combine-opts options-map default-opts route)]
        (link-str route opts)))))
```

**Comment by ohpauleez** [comment]
I agree.  Patches welcome if someone gets to this before me
