### ISSUE TITLE
body-params/default-parser-map parser options not correctly parsed

### ISSUE THREAD

**Issue by solussd** [pedestal/pedestal#315]
`io.pedestal.http.body-params/default-parser-map` takes optional parser-options (aggregated with &). It then generates a hash-map from them, and pulls out keyvals for transit-options, etc.

For example, I should be able to call it like this: 
```clj
(default-parser-map :transit-options {:handlers utils/transit-readers})
```

It generates a parser for transit by calling `(apply custom-transit-parser :json transit-options)`. `custom-transit-parser`'s implementation: 

```clj
(defn custom-transit-parser
  "<snip>"
  [& options]
  (fn [request]
    (assoc request
      :transit-params
      (transit/read (apply transit/reader (:body request) options)))))
```
`options` at this point is a vector (`[:json [:handlers utils/transit-readers]]`, per my example usage) and `transit/reader` is being applied to it. 

transit/reader: 
```clj
(defn reader
  "<snip>"
  ([in type] (reader in type {}))
  ([^InputStream in type opts]
     (if (#{:json :json-verbose :msgpack} type)
       (let [handlers (merge (default-read-handlers) (:handlers opts))
             default-handler (:default-handler opts)
             reader (TransitFactory/reader (transit-format type)
                                           in
                                           handlers
                                           default-handler)]
         (Reader. (.setBuilders ^ReaderSPI reader
                                (map-builder)
                                (list-builder))))
       (throw (ex-info "Type must be :json, :json-verbose or :msgpack" {:type type})))))
```

`opts` at this point is: `[:handlers utils/transit-readers]`, which isn't a map and `(:handlers opts)` will always return `nil`.

Let me know if you'd like a PR for this.

**Comment by ohpauleez** [comment]
The doc states that for transit, options is a vector:

```
 :transit-options A vector of options to be used when invoking `transit/reader` - must apply to both json and msgpack
```

Can you confirm the issue goes away when called like this: `(default-parser-map :transit-options [:json {:handlers utils/transit-readers}])`

This is also seen [in the body-params test](https://github.com/pedestal/pedestal/blob/master/service/test/io/pedestal/http/body_params_test.clj#L32-37)

**Comment by solussd** [comment]
Ah, yes transit-options is not like the rest. Unfortunately, calling it like you suggested exposes a bug caused by this line in `default-parser-map`:
```clj
 #"^application/transit\+json" (apply custom-transit-parser :json transit-options)
```
`custom-transit-parser` would then be called with `:json` twice.

**Comment by solussd** [comment]
... and fixed on my end. PR?

**Comment by ohpauleez** [comment]
So, maybe this is the right way? `(default-parser-map :transit-options [{:handlers utils/transit-readers}])`

I was looking at the base transit function, not paying attention to the MIME-type dispatching.

**Comment by solussd** [comment]
Well, the test you linked to shows it being called with `[:json]`. 

I think it should support `[:<type>]` or `[:<type> option-map]`. 

The fix is an `:or` map in the argument destructuring for `default-parser-map`.

**Comment by solussd** [comment]
Like this? https://github.com/solussd/pedestal/commit/fbc21e0319d15e81af40d2e82eb841ef4a9f6e9e

**Comment by solussd** [comment]
scratch that.. the test is wrong.

**Comment by solussd** [comment]
The mime-type dispatch map will always have an entry for transit+json and transit+msgpack. Closing this. The body-params test should be fixed though. :)

**Comment by solussd** [comment]
Question- if the only valid way to call it is with an options map, why pass it in a vector?

**Comment by ohpauleez** [comment]
Yeah, seems like the test should be updated (it's clear that the calling convention changed across a few changes, and the option is ignored when processed).

The options vec was used before we support mime-types (we originally left it up to the developer to determine how to use transit within their own application).  Just needs to be cleaned up.

**Comment by rauhs** [comment]
I ran into this and it took me a while until I realized I had to pass in a vector.

Can we either:

1. Add an example use in the docstring for `:transit-otions`?

2. Fix this and allow to pass in a map instead of needing to wrap the map in a vector. After all `transit/reader` only takes `opts` which is a map with the keys `:handlers` and `:default-handlers`.
