### ISSUE TITLE
The io.pedestal.test/response-for function returns an empty response for routes with asynchronous interceptors.

### ISSUE THREAD

**Issue by briprowe** [pedestal/pedestal#316]
When testing routes which have intercpetors that return a `core.async/channel` rather than a `context`, the `execute` function returns. This ultimately causes the the `test-servlet` to return before the `test-servlet-response` has been "realized".

By changing the `committed` atom to a promise, we can delay the thread running the test code until the response has been realized.

**Comment by ohpauleez** [comment]
Thanks for using Pedestal and brainstorming ways we can improve it!  The more ideas, the better!

Rather than a promise, I'd like to see response-for use a channel internally.  This allows Pedestal to handle all async response capabilities, and removes the need for hard-coding timeouts (which should be avoided in async programming).  The final design isn't clear to me (I need to sit with it a bit).

**Comment by jonahbenton** [comment]
Hey Paul, it looks like servlet-response-for needs a way to allow off-thread operations to complete  [in between the .service call and the retrieval of status and headers](https://github.com/pedestal/pedestal/blob/311646912a013cff1762efa9dd0deec0b5085777/service/src/io/pedestal/test.clj#L217). 

Is the thought to do a blocking take there from a channel set up in test-servlet-response, perhaps attached to response metadata?

**Comment by ohpauleez** [comment]
Hi Jonah - that's the general idea.  More likely, we'll return the channel (that will receive the response-map), to allow developers to control the block characteristics (timeout and such).

**Comment by candera** [comment]
I prefer to avoid breaking changes when possible. IMO, changing the return types of `response-for` (or anything, generally) is a breaking change. I don't think it's necessary in any event: I suspect we could introduce a new function - call it `response-for-async` - that would always return a channel. For a channel-returning interceptor, this would be the channel returned by the interceptor. For context-returning interceptors, this would be a channel that yields the context. `response-for` could be implemented on top of `response-for-async` by doing a blocking take on the result of `response-for-async`. This should ensure that nothing breaks while still letting people write tests against channel-returning interceptors without giving up control of scheduling - they would choose the semantics they want based on the function they used, and `response-for-async` is primitive enough to support all usages. That does assume people have a way to influence delivery of the value on the channel returned by the interceptor, but I'm not sure that's avoidable in any event.

Would something like that address what people need to do? I just started working on this, so it's entirely possible I'm missing something - would love to hear the use cases.

**Comment by ohpauleez** [comment]
That all sounds accurate to me!  Thanks Craig!

**Comment by candera** [comment]
I do plan to work on this at some point, but it might not be soon. Don't let my name on this issue prevent you from picking it up. Drop a comment if you decide to work on it so I can check in with you when I get around to addressing it.

**Comment by martintrojer** [comment]
`response-for-async` would really help me testing my sse endpoints!

@ohpauleez Do you have a straw-man handy I can hack in-place while I wait for the official version?

**Comment by ohpauleez** [comment]
@martintrojer We have the design done and @candera has started on the code - hopefully it'll land on master soon-ish.  I completely agree that it'd be great to have.

I end up testing SSE endpoints using the simple client from the [sample](https://github.com/pedestal/pedestal/tree/master/samples/server-sent-events/src/server_sent_events/client).  You might also shoot a message out on the [mailing list](https://groups.google.com/forum/#!forum/pedestal-users) to see if anyone else has some tips.

**Comment by ohpauleez** [comment]
This was fixed in #362
