### ISSUE TITLE
Make test-servlet-input-stream extensible.

### ISSUE THREAD

**Issue by briprowe** [pedestal/pedestal#319]
I'm converting an existing codebase to use pedestal. Its tests use [ring.mock](https://github.com/ring-clojure/ring-mock) to generate test requests. I'd like to re-use that code as much as possible.

There are a few ways in which the data generated by `ring.mock.request/request` are incompatible with the data expected by `io.pedestal.test/response-for`.  In this issue, the incompatibility I'd like to tackle is in how the request body is represented.

Requests bodies created by `ring.mock.request/request` are `ByteArrayInputStreams`. Ex:

```clojure
(mock/request :post "foo" {:data :bar}) ;; =>
{:remote-addr "localhost", 
 :headers {"content-length" "11", "content-type" "application/x-www-form-urlencoded", "host" "localhost"},
 :server-port 80, :content-length 11, :content-type "application/x-www-form-urlencoded", :uri "foo",
 :server-name "localhost", :query-string nil, 
 :body #<ByteArrayInputStream java.io.ByteArrayInputStream@6778571>, 
 :scheme :http, :request-method :post}
```

In Pedestal, test request bodies are expected to be strings. By using an underlying protocol, I think we can make this extensible. The protocol would be responsible for converting arbitrary types into `ServletInputStream` objects.

**Comment by ohpauleez** [comment]
This change has been approved.  I'm going to close the issue here so we can move the conversation over to the Pull-Request.  Thanks for the contribution!

**Comment by nha** [comment]
Hello, sorry to post here but is there an example somewhere for using ring/mock with pedestal ? I asked a question here : http://stackoverflow.com/questions/33487615/clojure-test-a-pedestal-route with no luck.

**Comment by ohpauleez** [comment]
@nha - Thanks for using Pedestal!  Sorry your question didn't get an answer on StackOverflow - I don't think anyone monitors SO for Pedestal questions.  The best place to ask those kinds of questions is on the [mailing list](https://groups.google.com/forum/#!forum/pedestal-users).

Pedestal ships with its own utility for making requests directly to the servlet (similar to ring/mock, although I've never used `mock` myself) called [response-for](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/test.clj#L260-L273).  The Pedestal Service template produces a test automatically for you.  Check out one of the [samples](https://github.com/pedestal/pedestal/blob/master/samples/hello-world/test/hello_world/service_test.clj) for an example.
