### ISSUE TITLE
Support Server Sent Event "id" field

### ISSUE THREAD

**Issue by bobby** [pedestal/pedestal#321]
The SSE specification (http://www.w3.org/TR/eventsource/#event-stream-interpretation) describes the purpose of message lines starting with "id: ", and the inclusion of the the Last-Event-ID header, etc.  Pedestal should support sending messages containing an ID, and should document how to use the Last-Event-ID header in the SSE sample.

**Comment by ohpauleez** [comment]
No problem adding official support for the `id` field of a message.  Until then, it should be easy enough to append "\r\n id: .... \r\n" to your data string (I haven't confirmed this will work, but I can't see why it wouldn't).  You should also be able to handle Last-Event-ID in the initial connection channel setup
(I'm not sure what sort of official support we would provide for this, as it requires bookkeeping we wouldn't want to force upon all users.)

**Comment by yokolet** [comment]
Hi @bobby , I added event id support in sse-id branch. This branch supports Last-Event-ID also. There's two samples in https://github.com/pedestal/pedestal/blob/sse-id/samples/server-sent-events/src/server_sent_events/service.clj ; one is simple counter, another is custom event id.

- simple counter
```
~$ curl http://localhost:8080/
event: count
data: 10, thread: 77
id: 0

event: count
data: 9, thread: 77
id: 1
...
```

- simple counter with Last-Event-ID header
```
~$ curl -H "Last-Event-ID: 8" http://localhost:8080/
event: count
data: 10, thread: 77
id: 9

event: count
data: 9, thread: 77
id: 10
...
```

The event id is an id and can be anything such as date/time, uuid or other. So, users want to set their initial value and update function. The second example shows custom event id:

- custom event id
```
~$ curl http://localhost:8080/custom
event: count
data: 10, thread: 81
id: my 2 cents

event: count
data: 9, thread: 81
id: my 4 cents
...
```

- custom event id with Last-Event-ID header
```
~$ curl -H "Last-Event-ID: my 8 cents" http://localhost:8080/custom
event: count
data: 10, thread: 83
id: my 16 cents

event: count
data: 9, thread: 83
id: my 32 cents
...
```

If you have a chance, would you test this sse id feature? I appreciate the feedback.

**Comment by ohpauleez** [comment]
Landed on master.  Thanks all!

**Comment by bobby** [comment]
Thanks, team!
