### ISSUE TITLE
Pedestal: Client or Server?

### ISSUE THREAD

**Issue by johnjelinek** [pedestal/pedestal#326]
The [docs](https://github.com/pedestal/pedestal/blob/master/guides/documentation/readme.md) say:
```
In short: Pedestal provides a better, cohesive way to build rich client web applications in Clojure.
```
but it seems the the repo root [README](https://github.com/pedestal/pedestal/blob/master/README.md) has an inconsistent statement:
```
Pedestal is a set of libraries written in Clojure that aims to bring both the language and its principles (Simplicity, Power and Focus) to server-side development.
```

It should only be the latter, right?

**Comment by rkneufeld** [comment]
It's definitely the latter. Punting to @ohpauleez for a proper re-write.

**Comment by ohpauleez** [comment]
Fixed!  Thanks!

**Comment by johnjelinek** [comment]
@ohpauleez: changeset?

**Comment by ohpauleez** [comment]
On master, latest commit, https://github.com/pedestal/pedestal/commit/f2cb8b3e034c52171ca13a02d9aefb6ae59205ff

**Comment by johnjelinek** [comment]
:+1:



—
