### ISSUE TITLE
I can't get my routes works with the most simple example

### ISSUE THREAD

**Issue by cocodrino** [pedestal/pedestal#327]
Hi..sorry for the noob question, but coming from compojure has been a bit difficult understand the pedestal router...

this is the most simple case:

```clojure

(defn test-name [req]
  (let [name (get-in req [:path-params :name])]
    (ring-resp/response (str "hello! >>" name ))))

(defn hello [req] (ring-resp/response "hello!!!"))

(defroutes routes
           [[

             ["/hi" {:get hello}]

             ["/test/:name" {:get test-name}]

             #_["/" {:get home-page}
              ;; Set default interceptors for /about and any other paths under /
              ^:interceptors [(body-params/body-params) bootstrap/html-body]
              ["/about" {:get about-page}]]



             ]])


```

but neither http://localhost:8000/hi nor http://localhost:8000/test/tom works...I've restarted my server again but it doesnt fix the issue...it's frustrating cause I can't think in a more simple example and I can't found why doesnt works..

thanks!!

**Comment by ohpauleez** [comment]
Hi @cocodrino - Thanks for giving Pedestal a try and sorry you're having an issue.  In the future, you should post these kinds of questions on the [Pedestal Mailing List](https://groups.google.com/forum/#!forum/pedestal-users).

It looks like your route table isn't written correctly.  Rather than fix it for you here, I'd suggest you start off from a [sample](https://github.com/pedestal/pedestal/tree/master/samples/hello-world) or use the template via `lein new pedestal-service my-service`

**Comment by cocodrino** [comment]
ok..I've removed immutant and now it works...

 ::bootstrap/type          :immutant ;;doesnt works with immutant..same code
::bootstrap/type          :jetty  ;;this works

I'm using the lein autogenerated project and I'd uncommented the lines under the project file and change my bootstrap config...

**Comment by cocodrino** [comment]
the only difference with respect to the guide is than I'm running my server using the run-dev function inside porject.server ...I dont now if it could be the cause...but is weird than works with jetty and not with immutant..

**Comment by ohpauleez** [comment]
This has been fixed on the latest SNAPSHOT.  If you [search through the issues](https://github.com/pedestal/pedestal/issues?utf8=%E2%9C%93&q=immutant) you can see people who had the [same problem](https://github.com/pedestal/pedestal/issues/323) and originally [here](https://github.com/pedestal/pedestal/issues/291)

If you have more issues like this or you get tripped up anywhere, definitely jump on the mailing list!  Lots of people can contribute and provide you with the best tips and tricks.

**Comment by cocodrino** [comment]
thanks..I'll do it...
