### ISSUE TITLE
Use url-for for absolute paths and path-for for relative

### ISSUE THREAD

**Issue by kirillsalykin** [pedestal/pedestal#331]
Currently url-for generates relative path, but there are situations when abs path required: e-mail links, force ssl etc.

**Comment by ohpauleez** [comment]
Hi - thanks for using Pedestal!

`url-for-routes` (the core function) supports an [absolute-path option](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/route.clj#L308)

**Comment by kirillsalykin** [comment]
Oops, sorry.

**Comment by ohpauleez** [comment]
No worries at all!  I'm more than happy to help
