### ISSUE TITLE
Form-for function present in docs but absent in source

### ISSUE THREAD

**Issue by kirillsalykin** [pedestal/pedestal#332]
According to https://github.com/pedestal/pedestal/blob/master/guides/documentation/service-routing.md#verb-smuggling "form-for" function present. 

But i cant find any in source. This looks like very handy function and i believe it can be easy added.

**Comment by ohpauleez** [comment]
https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/route.clj#L434-452
