### ISSUE TITLE
Hook for SSE disconnects

### ISSUE THREAD

**Issue by tonsky** [pedestal/pedestal#338]
If I understand correctly, there’s no way to detect if SSE connection was closed until you send something. If server is passive and don’t initiate sends, and client is gone, map of contexts will accumulate a lot of garbage over the time. There’re heartbeats, but they cannot be listened for from user code.

Did I understand it correctly? Are there any plans to fix this?

**Comment by timewald** [comment]
I think there are (at least?) three choices:

1) send a periodic event that the client ignores
2) keep track of the last time an event was sent to a client and get rid of
contexts that haven't been used for a while
3) get rid of client SSE context when client's session times out (basically
the same as 2, but w/o tracking last event time separately)

Both 2 and 3 assume a client will reconnect as needed, as browsers will (or
should :-).

I'm not aware of any plans to build any of these in to Pedestal proper. I'm
curious which one you would opt for, or if you have another solution in
mind...

Tim-

On Tue, May 5, 2015 at 8:49 AM, Nikita Prokopov <notifications@github.com>
wrote:

> If I understand correctly, there’s no way to detect if SSE connection was
> closed until you send something. If server is passive and don’t initiate
> sends, and client is gone, map of contexts will accumulate a lot of garbage
> over the time. There’re heartbeats, but they cannot be listened for from
> user code.
>
> Did I understand it correctly? Are there any plans to fix this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pedestal/pedestal/issues/338>.
>



-- 
Datomic Team

**Comment by ohpauleez** [comment]
Tim's solutions are spot on - people usually opt for 3, but I'm curious what you have in mind.

Some additional context:
The heartbeats keep the SSE session open from the server-side, TCP keepalive keeps the actual connection open (and checks for a disconnected peer).  If a peer disconnects after the keepalive probe, but before the heartbeat is sent, you won't know about it until you send data.  As soon as a disconnect is detected, the connection and all of its references are torn down (they go out of scope) and are cleaned up.  This often (but not always) will end up causing an uncaught exception (about EOF) - this is harmless to your application.  This also doesn't generate anymore garbage than a standard HTTP Request/Response.

Generally speaking, in networked applications you can't know about a disconnected peer unless they disconnected via a protocol operation.  For example WebSockets (which will be introduced soon) manage their own keepalive with PING/PONG heartbeats (since the connection is bi-directional).  With TCP, you can know about a dead/disconnected peer via keepalive, but that isn't currently exposed within Pedestal (and I'm unsure that it's even exposed at the Jetty level).

Usually determining disconnected peers and choosing how to handle them is application specific, but if you have ideas, I'd certainly love to hear them!

**Comment by tonsky** [comment]
Pedestal can detect closed connections (can it? you can subscribe on
properly-closed TCP, right?) and already has heartbeats. Plus/minus
heartbeat we can be sure conn is dropped. Providing a custom callback on
that condition, for user, like `on-close`, would be fine.

**Comment by tonsky** [comment]
Under garbage I mean user-space garbage: when someone connects, you store event-chat and ctx for that connection. And there’s no single place on where to clean that info up.

@timewald 2 and 3 are not fun, it’s like turning SSE to long-polling

**Comment by ohpauleez** [comment]
If you mean, that event-chan and ctx are closed over, that's correct - but as soon as the exception on `send` happens, the exception causes all channels to close and the context becomes garbage.  You can detect a disconnected peer however you like, and close down any associated channel (response-chan or event-chan), which will tear down everything associated with the SSE connection.

**Comment by tonsky** [comment]
@ohpauleez sorry, I explain myself terribly. Take a look at this: https://github.com/pedestal/pedestal/blob/master/guides/documentation/service-sse.md

If `notify` is never called, `a-stored-streaming-context` will never be cleaned up, even if client is long gone.

**Comment by ohpauleez** [comment]
Ahh - the docs are a little out of date.  That was indeed an issue, but it was fixed in the 0.3.X releases.  The `samples` are much better maintained: https://github.com/pedestal/pedestal/blob/master/samples/server-sent-events/src/server_sent_events/service.clj

**Comment by tonsky** [comment]
Yes, but it doesn’t change core problem: I still must keep a ref to
`event-ch` somewhere, and that link will never be cleaned up.

**Comment by ohpauleez** [comment]
It won't be cleaned up automatically in your application, that's not Pedestal's job.  But you have access to all the mechanisms you need to auto clean it up, if you want to hold on to it.  What the sample shows is that you don't actually need to hold a reference to event-ch.  Holding a reference to the channel is entirely app-dependent.

That said, patches are certainly welcome if there's something you're seeing that would make detecting the closed channel better for your use case.

**Comment by bplatz** [comment]
I'm dealing with similar issues and I think generally what people are after (and I certainly am after) is to catch the exception that results from a closed connection, execute a provided callback function, and avoid the noisy error logging. If no callback is provided, then re-throwing, as is currently done, is probably appropriate.

Currently the standard setup allows no way to hook into that exception, and the only obvious approach is to set up your own heartbeat to look for a false async/chan response. The redundancy with Pedestal's heartbeat makes this a bit ugly, especially when coupled with the noisy error logs.

Another less invasive alternative would be to have an option to turn off the pedestal heartbeat if you are implementing your own (maybe by setting the heartbeat delay to -1 second). That doesn't help with the noisy logs however, but would solve the redundancy.

**Comment by ohpauleez** [comment]
@bplatz Thanks for adding some more meat here and reporting back.  Getting "field cases" helps evaluate issues.  In your particular application, is it problematic from detecting the closed channel when you put?

For example, when the client drops and the lower-level channel closes, Pedestal will also close the SSE channel you're using in your application code.  When you attempt to put on that SSE channel, it'll return false - the sentinel for you to handle close logic.  You may see some log spam from the heartbeat, but only for about 3 or so messages (depends on Keepalive).

Is there a way that putting on the closed channel wouldn't work in your application?

**Comment by bplatz** [comment]
@ohpauleez Detecting on a put is not problematic at all. 

An application that will send sporadic puts which may be in response to client-side actions may have no reason to do a put, particularly if the client is gone. This would accumulate unnecessary state on the server side.

To mitigate this, you'd need implement a heartbeat to try puts. This is redundant with what Pedestal is doing already but certainly works. The concerns are the added overhead, combined with the log spam. Turning off logging for io.pedestal.http.impl.servlet-interceptor seems like a poor solution, as I'm not sure what valid errors I'd possibly miss. This type of "error" seems like it should be more in the log/info camp, and not necessitate a full stack trace.

**Comment by ohpauleez** [comment]
Thanks for the additional details and thoughts.  Which change idea seems the most useful to your application and why?  What problems does it fix and how do the trade-offs align with your use case?

1. Do nothing - everything stays exactly the same.
2. Leave the channel logic how it is, change heartbeat catch to `log/info` and remove the stacktrace, and dismiss the added overhead concerns (I'm not convinced the application bookkeeping makes a significant impact, but I'd love to see data to the contrary if you have some numbers!)
3. Allow `heartbeat-delay` to be a map, optionally specifying a `:heartbeat-fn` to use in place of Pedestal's `do-heartbeat`, allowing applications to cleanup on failed heartbeats (ignoring keepalive).
4. SSE should take an additional `options` map argument, allowing for an additional callback function to be passed in which would get called immediately after the channel closing and cleanup.

**Comment by bplatz** [comment]
I think option 4 seems the most backwards-compatible and also offers future option expansion. With your pending websocket support it would be nice to keep the interfaces as similar as possible and perhaps it would help there as well.

The primary use case would be a hook to help clean up server-side state without having to implement another heartbeat-like functionality. Only options 3 and 4 solve the use case, and for clarity I think Pedestal doing pedestal clean-up is a good thing regardless (you perhaps imply not doing this for option 3, but doing it for option 4). The callback would only be for your own application state cleanup.

I think turning the thrown error into a log/info is a good idea regardless as I think it would be more consistent with how Pedestal logs other activities, however that is just my opinion.

I'm also happy to look into putting up a PR for option 4 if you are interested.

**Comment by tonsky** [comment]
Let me vote for option 4 too. The only real problem here is to clean up server state after client disconnects in a cases where server is passive (e.g. it only reacts to user actions)

**Comment by candera** [comment]
@ohpauleez and I spent some time looking at this today. A callback makes sense to both of us. I will work on getting a patch together.

**Comment by ohpauleez** [comment]
This is fixed on master.  Thanks for reporting!
