### ISSUE TITLE
Exceptions for routes with path params

### ISSUE THREAD

**Issue by henriklundahl** [pedestal/pedestal#340]
Pedestal 0.4.0 or 0.4.1-SNAPSHOT at 73b5854d.

Given this route:

    (defroutes routes [[["/a/:a/b/:b" {:get my-page}]]])

* I get a 500 response because of a NullPointerException [here](https://github.com/pedestal/pedestal/blob/73b5854d4ba01a6cd2146ca8a37ae6a2b76e8995/service/src/io/pedestal/http/route/prefix_tree.clj#L321) when requesting `/a/`, `/a/a` or `/a/a/b/`.
* When I request `/a`, `/a/a/b` or `/a/a/b/b/c` I get a 404 as expected.
* When I request `/a/a/` or `/a/a/b/b/` I get a 500 because of a StringIndexOutOfBoundsException [here](https://github.com/pedestal/pedestal/blob/73b5854d4ba01a6cd2146ca8a37ae6a2b76e8995/service/src/io/pedestal/http/route/prefix_tree.clj#L31).
* Requesting `/a/a/b/b` works fine.

**Comment by ohpauleez** [comment]
Thanks for reporting this - My guess is that we're falling off the tree because of an off-by-one error when looking up the longest sequence.

**Comment by snuggs** [comment]
404 is incorrect. The response code is actually 405 in this case. 404 is when the resource itself isn't defined. 
Given a resource collection definition @ `/foo/bar/` and a resource at `/foo/` a call to `/foo/bar` SHOULD respond with `405` status. 

Now of course `/sdafgagfgfg` SHOULD return `404` ;-)
