### ISSUE TITLE
<%= VERSION %> in bottom of cognitect-ca.pdf

### ISSUE THREAD

**Issue by claj** [pedestal/pedestal#342]
There seems to be a bug in your `CA.pdf`, the tag `<%= VERSION %>` seems to not be correctly resolved.

Sorry for being incredibly `meta`, but I guess this kind of legal stuff should be correct as well.

**Comment by henriklundahl** [comment]
[Over here](https://github.com/cognitect/clojure-lab) is a link to sign the agreement digitally. Perhaps the PDF can be replaced with this link?

**Comment by ohpauleez** [comment]
Fixed on master, Thanks all!
