### ISSUE TITLE
Is it possible to use variables within defroutes?

### ISSUE THREAD

**Issue by lynndylanhurley** [pedestal/pedestal#344]
Here's an example of what I mean:

~~~clojure
;; route defined as var outside of `defroutes`
(def foo-route ["/" {:get foo-handler}])

(defroutes routes
  [[["/"
      ;; this does NOT work
      ["/foo" foo-route]

      ;; this does work
      ["/bar" ["/" {:get bar-handler}]]]]])
~~~

I'm trying to do something like the first route and I can't figure out why it's not working. It doesn't throw any errors or anything. It just fails to register the route.

**Comment by ohpauleez** [comment]
Answered on the [mailing list](https://groups.google.com/d/msg/pedestal-users/JSx4svVy4Ng/kqpIIVDVsQIJ)
