### ISSUE TITLE
"Hello World" guide has the wrong version number

### ISSUE THREAD

**Issue by elliot42** [pedestal/pedestal#345]
The "Hello World" guide points people at installing 0.3.0 when the latest version available in 0.4.0.  There seem to be non-trivial changes between the versions (e.g. the existence of `...interceptors.helpers`) so it seems important to install the latest version.

**Comment by ohpauleez** [comment]
Yep, it's hard to keep the project moving forward and all the samples updated.  Contributions are very welcome here - especially for doc and sample updates.

**Comment by ohpauleez** [comment]
I think this just got fixed.  Thanks for reporting!
