### ISSUE TITLE
Unnecessary private marker

### ISSUE THREAD

**Issue by robert-stuttaford** [pedestal/pedestal#347]
Those who implement their own `::http/not-found-interceptor` have to also implement their own `response?` fn as you've marked it private:

https://github.com/pedestal/pedestal/blob/8fa70034afe6c8072ce88a874021af495517d207/service/src/io/pedestal/http.clj#L83-L88

 If it were public, we could just use yours :grin:

**Comment by ohpauleez** [comment]
Yep - fixed on master.  There are a few private functions throughout Pedestal that shouldn't be private functions (they're not hiding anything important)
