### ISSUE TITLE
How do I turn off the debug logs?

### ISSUE THREAD

**Issue by lynndylanhurley** [pedestal/pedestal#355]
When I start a pedestal server with boot, I see hundreds of screens of this:

![Why](http://i.imgur.com/7CEvHRn.png?1)

My terminal can barely keep up.

And if I need to actually log something from my app, it's impossible to find because I get a hundred more screens of this output with each request.

This is my boot task:

~~~clojure
(deftask app-server []
  (serve)
  identity)
~~~

Where the `serve` method is defined here:

~~~clojure
(defn service
  [port]
  {:env :dev
   ::server/routes routes
   ::server/resource-path "/"
   ::server/type :jetty
   ::server/join? false
   ::server/port (Integer. (or port 3000))
   ::server/allowed-origins {:creds true
                             :allowed-origins (constantly true)}})


(defn run-pedestal-server
  "Start the Pedestal API server."
  [& [port]]
  (println "Staring pedestal server...")
  (-> (service port)
      ;; interceptor chains
      server/default-interceptors
      server/dev-interceptors
      server/create-server
      server/start))


(defn serve [& [port]]
  (watch)
  (run-pedestal-server port))
~~~

Is there anything I can do to prevent this output?

Thanks!

**Comment by ohpauleez** [comment]
Thanks for using Pedestal!
The logging settings can be found in your project's config/logback.xml.

Towards the bottom will be a LEVEL setting.  By default it should be set to INFO, but it may have been accidentally set to DEBUG.  I have never personally seen a log explosion quite like the one you're showing, which makes me think this is something pretty specific to the application code/libraries in use.

Have you tried working with the logback.xml file?  Could another library in use be overriding your logging settings?

**Comment by lynndylanhurley** [comment]
@ohpauleez - thank you so much for your help!

My project is basically a new [tenzing](https://github.com/martinklepsch/tenzing) project. I just replaced the default server with pedestal and my console went crazy.

I created the `config/logback.xml` file and pasted in the [content from one of the sample projects](https://github.com/pedestal/pedestal/blob/8fa70034afe6c8072ce88a874021af495517d207/samples/hello-world/config/logback.xml), but it didn't have any effect.

Do I need to direct the server to use the `config/logback.xml` file somehow?

**Comment by lynndylanhurley** [comment]
[Here](https://github.com/lynndylanhurley/clojax) is the project in its current state.

**Comment by lynndylanhurley** [comment]
Ahh nevermind!! I just had to add `config` to `:source-paths`.

So to recap, the fix was to create a `config/logback.xml` file with [this content](https://github.com/pedestal/pedestal/blob/8fa70034afe6c8072ce88a874021af495517d207/samples/hello-world/config/logback.xml), and then to add `"config"` to the `:source-paths` option in the `build.boot` `set-env!` method.

~~~clojure
(set-env!
 :source-paths    #{"src/cljs" "src/clj" "dummy/cljs" "dummy/clj" "config"} ;; <--
 ...
~~~

Thanks @ohpauleez!!!

**Comment by ohpauleez** [comment]
You should add `config` to `:resource-paths` instead of `:source-paths`.  The effect will be the same, but it's a little more correct.
