### ISSUE TITLE
Problems with "watch" reloading namespace when using boot

### ISSUE THREAD

**Issue by lynndylanhurley** [pedestal/pedestal#356]
The `watch` function isn't reloading my code when the files change.

This is what I'm using to start the server:

~~~clojure

(defn service
  [port]
  {:env :dev
   ::server/routes routes
   ::server/resource-path "/"
   ::server/type :jetty
   ::server/join? false
   ::server/port (Integer. (or port 3000))
   ::server/allowed-origins {:creds true
                             :allowed-origins (constantly true)}})



(defn run-pedestal-server
  "Start the Pedestal API server."
  [& [port]]
  (println "Staring pedestal server...")
  (-> (service port)
      ;; interceptor chains
      server/default-interceptors
      server/dev-interceptors
      server/create-server
      server/start))


(defn serve [& [port]]
  (watch ["src" "dummy"])
  (run-pedestal-server port))
~~~

And here is my boot task:

~~~clojure
(deftask app-server []
  (serve)
  identity)
~~~

I can tell that this code is getting run:

~~~clojure
;; from io.pedestal.service-tools.dev

(defn- ns-reload [track]
 (try
   (doseq [ns-sym (track)]
     (require ns-sym :reload))
   (catch Throwable e (.printStackTrace e))))
~~~

The `(require ns-sym :reload)` is run whenever I change a file, and the value of `ns-sym` is correct, but for some reason the code isn't updated for the running server.

This was working fine with leiningen. What is it about boot that could be causing this issue?

**Comment by claj** [comment]
I think the reason is that reload doesn't know about the new file-systems

https://github.com/boot-clj/boot/wiki/Repl-reloading mentions

    boot.user=> (def dirs (get-env :directories))
    boot.user=> (apply repl/set-refresh-dirs dirs)

**Comment by ohpauleez** [comment]
I would also discourage using service-tools just for ns-watching - it's likely to be killed in a future version of Pedestal.  Instead, just use `ns-tracker` directly, as done in [this template](https://github.com/ohpauleez/pedestal-micro/blob/master/src/leiningen/new/pedestal_micro/service.clj)

**Comment by lynndylanhurley** [comment]
Thanks @claj and @ohpauleez!!!

@claj - I added those lines to my `build.boot` file but they didn't seem to have any effect.

@ohpauleez - that worked!!!

But this seems like a lot of trouble for such a common task. Could there be something like this instead?

~~~clojure
(def service
  {::http/host (or (conf :host) "127.0.0.1")
   ::http/port (Integer/parseInt (or (conf :port) "8080"))
   ::http/type :jetty
   ::http/join? false
   ::http/resource-path "/public"
   ::http/routes routes
   ::http/reload? true
   ::http/watch-dirs ["src"]})
~~~

I only bring it up because I spent so much time trying to get this to work. But I'm still new to this stuff so maybe it's not so difficult for more experienced devs.

Thanks again for your time guys :smiley:

**Comment by ohpauleez** [comment]
I personally don't like ns-reloading and it's not required for development setup.  Using a stock Pedestal service template, launch a repl and `(def serv (run-dev))`, then connect your editor to that repl.  As you re-eval/reload code, the changes will be live.  This lets you separate saving/writing a file, from evaluating/requiring/loading a file.

**Comment by lynndylanhurley** [comment]
@ohpauleez - that makes sense, and that sounds like the ideal solution. Do you know if this is possible with vim (using something like [fireplace.vim](https://github.com/tpope/vim-fireplace))?

**Comment by ohpauleez** [comment]
@lynndylanhurley I use vim-fireplace daily

**Comment by lynndylanhurley** [comment]
Omg fireplace is great!!! I didn't know coding could be this nice :smiley:
