### ISSUE TITLE
Pedestal should allow endpoints to upgrade requests to WebSockets

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#358]
Pedestal has long sought to support WebSockets.  One option is to utilize [JSR 356 - WebSockets Interface](https://eclipse.googlesource.com/jetty/org.eclipse.jetty.project/+/jetty-9.3.1.v20150714/examples/embedded/src/main/java/org/eclipse/jetty/embedded/WebSocketJsrServer.java), but often containers and other platforms offer more control over the WebSocket connection if directly created and managed.

WebSocket support should be added to Pedestal such that its interaction looks and feels similar to the way SSE is handled.  This means all WebSocket connections would be "Upgrade"d from HTTP.

**Comment by ohpauleez** [comment]
If someone needs WebSockets right now, you can use the "basic support" for Jetty on [the dedicated branch](https://github.com/pedestal/pedestal/tree/basic-websockets).

**Comment by piranha** [comment]
Any plans about releasing that functionality?

**Comment by ohpauleez** [comment]
This is now on master.
