### ISSUE TITLE
Running on nodejs?

### ISSUE THREAD

**Issue by kirillsalykin** [pedestal/pedestal#363]
Sounds like a little fantastic, but any chances running pedestal on nodejs? With Clojurescipt of course.

**Comment by ohpauleez** [comment]
Closed before I could even respond! :)
It isn't likely that we'd make this a direct goal, but we are working to make Pedestal non-Servlet specific.  After that's completed, you could go through the codebase and remove all the direct Java calls (wherever they may exist).
