### ISSUE TITLE
Minor bug using execution-id

### ISSUE THREAD

**Issue by thheller** [pedestal/pedestal#364]
I'm currently evaluating pedestal and browsing the code I found a very very minor issue, at least I think so.

https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/impl/interceptor.clj#L239

This uses the global execution-id ```(def'd)``` instead of the one in context ```(::execution-id context)```. The impact is probably not even noticeable since you usually don't run with debug logging in a multithreaded environment.

Anyways, probably the least serious issue but a good way for me to check if I understand things correctly. :)

**Comment by ohpauleez** [comment]
Because it's an Atomic long, it's a mutable object from the Java side.  It should show it's current value regardless.  That said, the numbers could skew - we should default to the execution-id in the context.
