### ISSUE TITLE
Pedestal server creation could be more extensible

### ISSUE THREAD

**Issue by briprowe** [pedestal/pedestal#366]
**Problem**: I'm trying to use Pedestal in a system built on Stuart Sierra's Lifecycle protocol. I would like to reuse the system startup logic as much as possible at test-time. To achieve this, being able to write a fixture something like the following would be helpful:

```clj
(ns my-service.fixtures.sysetm
  (:require [com.stuartsierra.component :as comp]
            [my-service.routing :as routing-table]
            [my-service.core :refer [->system]]))

(def ^:dynamic *system* nil) ;; ninja edit

(defn make-system-fixture
  [config]
  (fn [test]
    (binding [*system* (-> (->system :dev
                                     (routing-table/routes config)
                                     "/public"
                                     8080)
                           (assoc-in [:http-service :spec :io.pedestal.http/type]
                                     :testing)
                           (comp/start-system))]
      (try
        (test)
        (finally
          (comp/stop-system *system*))))))
```

**Possible Soln**: Implement `io.pedestal.http/server` as a multimethod.

**Comment by mtnygard** [comment]
Can you elaborate on this? There seems to be something interesting going on inside `my-service.core/->system` that might clarify what you're requesting.

**Comment by ohpauleez** [comment]
@briprowe I've talked to Stuart Sierra and others at Cognitect about patterns between Component and Pedestal.  Nearly all of the patterns were related to injecting something into interceptors/routes, but no one seemed to want to control the actual server integration.

What is the core issue around using the system map (where routes get passed in via a function call that returns routes - like you're doing above).?

**Comment by ddeaguiar** [comment]
Note that [`io.pedestal.http/create-server`](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http.clj#L294) can be considered a convenience function. You can (and should IMHO) split up servlet and service creation when using Pedestal with component. Your test system can create the servlet and provide access to the `:io.pedestal.http/service-fn` for test purposes.

**Comment by ohpauleez** [comment]
@briprowe With the comments in here and the extraction of Chain Providers, do you have everything you need?  Can this issue be closed/resolved?

**Comment by claj** [comment]
I do test that the service can be started, stopped and restarted with something like [this gist, service_test.clj](https://gist.github.com/claj/b2f98ba0009d72607e5126b2478261e8). I find fixtures quite confusing in this case, because we explicitly want to test the starting and stopping of the system.

The free-port is very useful when we both run tests and have an instance going.

**Comment by ohpauleez** [comment]
Just a heads up, I think you can set the Pedestal port to 0 and have it return the first available (high) port number -- that's a POSIX thing.  I haven't tried, but I would be surprised if that didn't work.

**Comment by ohpauleez** [comment]
I believe all the necessary pieces are present to achieve the desired goals.  I'm going to close this issue, but if someone has another use-case or idea they don't think is covered, please post here and I'll re-open the issue.  Thanks all!

**Comment by grzm** [comment]
I've put together a library for using Pedestal with Component that's been working well for me.

https://clojars.org/grzm/component.pedestal
