### ISSUE TITLE
HEAD Requests are not supported

### ISSUE THREAD

**Issue by Christopher-Bui** [pedestal/pedestal#372]
It looks like HEAD requests are not supported at all in Pedestal.

There's the [head interceptor](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/ring_middlewares.clj#L85-L91) that [wraps the ring middleware for head requests](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/head.clj), but it does it incorrectly.

The key thing to notice is the pedestal interceptor skips the wrap-head function, which keeps a reference to the original request that comes in. The consequence of not doing this is we simply assoc the :request-method to be :get to get the headers, then check on :leave if the changed :request-method is going to be :head, which of course it is not.

Assuming one writes this interceptor correctly, other issues crop up. It seems like the router does not route based on the request map, as we get a :servlet-request in the context that still says HEAD and our :get route never gets called. If this wasn't an issue, then by the default not found interceptor will return a 404 response because the ring middleware sets the response to nil.

Finally, if you try to explicitly create a :head route, that won't work because of [this vector](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/route/definition.clj#L183). I seem to be able to create custom, non-spec verbs and match :head requests by adding them in this vector.

And the explicit way isn't optimal because a :head request is simply the headers of the :get route. I'd like to be able to do it just once.

Are we, (@err, me) missing something simple?

**Comment by ohpauleez** [comment]
Thanks for the report!  I've looked into this and I think getting HEAD correctly supported is easy, direct, and useful for others using Pedestal.

The interceptor will be updated to correctly track the HEAD within the context (which is the Pedestal-eque way to achieve that).

**Comment by Christopher-Bui** [comment]
Right, that was my first approach. But it seems the router doesn't match based on the :request map.

I assoc'd a key into the context instead with the value of the original request method and updated the :request-method in the request to be :get. No routes match. My hypothesis is that it is due to there being a :servlet-request object which still has the original request being HEAD.

**Comment by ohpauleez** [comment]
Hi @Christopher-Bui - I just started working on this.  Can you point me to a repo where the issue is happening.  There [is a test](https://github.com/pedestal/pedestal/blob/master/service/test/io/pedestal/http/ring_middlewares_test.clj#L84-L95) that shows the head middleware works.  I've rewritten the HEAD interceptor by hand, which also works.  I need to see a failing case to see in which way it fails.

**Comment by err** [comment]
@ohpauleez 

can modify `head-is-valid` to achieve a failing test for the round-trip.
```clj
(deftest head-is-valid
  ;; ...
  (is (= {:body nil :status 200}
         (-> (context {:request-method :head})
             ((:enter (head))) ; addition
             app
             ((:leave (head)))
             (#(select-keys (:response %) [:status :body]))))))
```

commit: https://github.com/err/pedestal/commit/7a1ea4207f9f1291b87a6f8788a2e25dd4e5b78d
fork: https://github.com/err/pedestal/tree/support-HEAD-request

**Comment by mtnygard** [comment]
In reviewing this issue, it looks like we are doing more work to set up the call to ring's head-request and head-response than those functions actually do.

Is there any reason not to incorporate that logic directly in the head interceptor?

Basically, replacing the head interceptor with this:

``` clojure
(defn head
  "Interceptor for head ring middleware. If used with defroutes, it will not work
  if specified in an interceptors meta-key."
  []
  (interceptor {:name ::head
                :enter (fn [ctx]
                         (if (= :head (-> ctx :request :request-method))
                           (-> ctx
                               (assoc :head-request? true)
                               (assoc-in [:request :request-method] :get))
                           ctx))
                :leave (fn [{:keys [request response] :as ctx}]
                         (if (and response (:head-request? ctx))
                           (update ctx :response assoc :body nil)
                           ctx))}))
```

**Comment by ohpauleez** [comment]
That's basically how I rewrote it from scratch.  Since this is so straighforward I'm ok substituting our own implementation here (there is little risk around fundamental differences with the Ring Middleware).

**Comment by mtnygard** [comment]
OK, I've got this one.
