### ISSUE TITLE
Interceptor helpers should all allow return of a channel

### ISSUE THREAD

**Issue by oliyh** [pedestal/pedestal#375]
Hi,

Currently if I use `defhandler` (for example) to create a handler I cannot return a channel without a further interceptor to wrap a context around it. Currently, this looks like the following:

```clojure
(defafter async-handler [context]
  (if (satisfies? clojure.core.async.impl.protocols/Channel (:response context))
    (a/pipe (:response context) (a/chan 1 (map #(assoc context :response %))))
    context))

(defhandler my-handler [request]
  (a/timeout 1000)) 
```

It would be nice if this simple check was done inside `defhandler` so that it allowed you to return a channel like `defbefore` does. I notice that this applies to several other interceptor helpers like `on-request`.

I believe this would result in fewer surprises and cleaner code when using channels.

I'm happy to write the code if you agree with the idea.

**Comment by ohpauleez** [comment]
Hi @oliyh!  Thanks for using Pedestal and reaching out with the idea!
I often advise people not to use the helpers within Pedestal - they mainly exist for legacy reasons.  If you're building a new Pedestal application, you're encouraged to use the Interceptor API directly.

In your particular use case, is it problematic for you to use the API directly?

**Comment by oliyh** [comment]
Hi @ohpauleez thanks for your reply.

No, it's not a problem to build interceptors directly in general, although in this instance I was actually using [pedestal-swagger which has helpers](https://github.com/frankiesardo/pedestal-swagger/blob/master/src/pedestal/swagger/core.clj) which use the pedestal helpers underneath. In this case, it's more to do with pedestal-swagger's API. I'll have a chat with @frankiesardo and see what he thinks.

**Comment by ohpauleez** [comment]
@oliyh Sounds good. @frankiesardo, keep me in the loop!  Let me know anyway I can help!

**Comment by frankiesardo** [comment]
Thanks @ohpauleez I'm happy to follow the direction pedestal is pushing to and "deprecate" the macro helpers in `pedestal-swagger`. It's even better for me because there are less entry points to cover :octopus: 

I already have a public function that can be used with vanilla interceptor API, it's just a matter of updating my samples to encourage its use. Does that mean we can close this issue @oliyh?

**Comment by oliyh** [comment]
@frankiesardo yes this sounds like the best solution to me, thanks both.

**Comment by ohpauleez** [comment]
Thanks @oliyh and @frankiesardo!  I appreciate the interest, conversation, and resolution.  If anything else pops up, let me know!
