### ISSUE TITLE
CORS interceptor's `allow-origin` implementation error when it's arg is map with :allowed-origins key is seq of strings

### ISSUE THREAD

**Issue by mavbozo** [pedestal/pedestal#376]
The doc string for CORS's [allow-origin](https://github.com/pedestal/pedestal/blob/320066fa4e5c4cdee31d62b3c7c8bfa819d2665e/service/src/io/pedestal/http/cors.clj#L54) says:

```
Builds a CORS interceptor that allows calls from the specified `allowed-origins`, which is one of the following:

  - a sequence of strings

  - a function of one argument that returns a truthy value when an origin is allowed

  - a map containing the following keys and values

    :allowed-origins - either sequence of strings or a function as above

    :creds - true or false, indicates whether client is allowed to send credentials

    :max-age - a long, indicates the number of seconds a client should cache the response from a preflight request

    :methods - a string, indicates the accepted HTTP methods.  Defaults to \"GET, POST, PUT, DELETE, HEAD, PATCH, OPTIONS\
```

Some test in `io.pedestal.http.cors-test` fails when I supply a map argument whose `:allowed-origins` value is a seq of strings like this

```clojure
(def allowed-origins-as-map-app
  (::service/service-fn (-> {::service/routes routes
                             ::service/allowed-origins 
                             {:allowed-origins ["http://foo.com:8080"]}}

                            service/default-interceptors
                            service/service-fn)))
......
```

it throws
```
clojure.lang.ExceptionInfo: Interceptor Exception: Key must be integer
```

The problem happens because when the `allow-origin` arg is a map, it is returned as is from [normalize-args](https://github.com/pedestal/pedestal/blob/320066fa4e5c4cdee31d62b3c7c8bfa819d2665e/service/src/io/pedestal/http/cors.clj#L48-L52) and then--after destructuring, the `allowed-origins` value is used in function position in this [line](https://github.com/pedestal/pedestal/blob/320066fa4e5c4cdee31d62b3c7c8bfa819d2665e/service/src/io/pedestal/http/cors.clj#L76). That causes error when the value of `allowed-origins` is a seq of strings.

```
allowed (allowed-origins origin)
```

Since the usage in `allow-origin` body above expects `allowed-origins` as function,  I'll submit a pull request which changes the `normalize-args` function so that it returns a map whose `:allowed-origins` value is always a function.

**Comment by ohpauleez** [comment]
Thanks for reporting the issue (and submitting a CA)!  I'd like to take a quick pass through Pedestal to understand if this error is a bad documentation string, a bug in `normalize-args`, or a bug in the contract further down the stack (it's unclear to me at what level the change should be made).

**Comment by ohpauleez** [comment]
This is fixed on master.  Thanks!
