### ISSUE TITLE
pedestal service template

### ISSUE THREAD

**Issue by ioRekz** [pedestal/pedestal#378]
from the readme: "lein run-dev automatically detects code changes. Alternatively, you can run in production mode with lein run"

Is this still relevant ?

Changing an handler change nothing and I have to restart the server

**Comment by ohpauleez** [comment]
It's still accurate, but as documented [on the mailing list](https://groups.google.com/d/msg/pedestal-users/Lma1UP5yvtM/Rki333wLPQAJ), you still need to re-require/reload your routes (or add your own ns-watcher).
