### ISSUE TITLE
multipart params

### ISSUE THREAD

**Issue by shreyvithalani** [pedestal/pedestal#381]
Hii,I am trying to create a simple upload functionality in pedestal.I saw some examples online but they are using compojure and they have used multipart params with the post request.I am not able to figure out how should we use that with pedestal.Thanks

**Comment by shreyvithalani** [comment]
Sorry for the noob question but I am having hard time using pedestal.

**Comment by ohpauleez** [comment]
In the future, you should reach out to the [mailing list]() - lots of wonderful people there to help you.  Pedestal can use [Ring middlewares](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/ring_middlewares.clj).
