### ISSUE TITLE
error simple upload file example

### ISSUE THREAD

**Issue by shreyvithalani** [pedestal/pedestal#382]
I am trying to do a simple file upload in pedestal .I am getting the file data in request when I do (slurp (:body request) ,but it is in a format which is not accesible which is `"------WebKitFormBoundaryeUWUQE4EvvsrJgZk\r\nContent-Disposition: form-data; name=\"userfile\"; filename=\"1.json\"\r\nContent-Type: application/json\r\n\r\n{\n\t\"title\": \"Quiz 1\",\n\t\"exam-version\": \"0.1\",\n\t\"exam-number\": \"1\",\n\t\"program\": [{\n\t\t\"q\": \"Write a clojure function that calculates the minimum value of a collection.\",\n\t\t\"l\": \"p1\",\n\t\t\"t\": \"textarea\"\n\t}],\n\t\"questions\": [{\n\t\t\"q\": \"What is 1 + 1\",\n    \"c\": [\"2\", \"3\", \"4\", \"5\"],\n\t\t\"a\": \"2\",\n\t\t\"l\": \"q1\"\n\t}, {\n\t\t\"q\": \"What is the letter between the letters \\\"a\\\" and \\\"c\\\"?\",\n\t\t\"c\": [\"a\", \"b\", \"c\", \"d\"],\n\t\t\"a\": \"b\",\n\t\t\"l\": \"q2\"\n\t}, {\n\t\t\"q\": \"How do you determine if empty?\",\n\t\t\"c\": [\"empty?\", \"exist?\", \"map\", \"reduce\"],\n\t\t\"a\": \"empty?\",\n\t\t\"l\": \"q3\"\n\t}]\n}\n\r\n------WebKitFormBoundaryeUWUQE4EvvsrJgZk--` .Any solution for this thing?.The file I am uploading is json file.Thanks is advance.

**Comment by ohpauleez** [comment]
Hi @shreyvithalani - In the future, these questions are best asked on the [mailing list](https://groups.google.com/forum/#!forum/pedestal-users), as they are not direct issues with Pedestal itself and there is a much larger audience to help you.  You'll get better answers there!

I believe the file contents are on the form data (you should be accessing `:params` or `:form-params` depending on how you're handling the upload- I would assume mulitpart).

**Comment by shreyvithalani** [comment]
Thank you!!I will post that in mailing list..
