### ISSUE TITLE
SSE channel seems to close after a single event is sent

### ISSUE THREAD

**Issue by batasrki** [pedestal/pedestal#384]
This is probably down to how I'm attempting to use the SSE feature rather than a bug. As the title says, I'm able to only receive one SSE message on the client side, which isn't what I expect. Unlike the samples code, I am actually trying to integrate the SSE into a background pipeline where I post a URL, its HTML gets fetched and `<title>` parsed, and db record updated. As a last step, I'd like to post the updated record on the SSE stream such that the client receives it and updates itself.

The example code and the log is in this gist, https://gist.github.com/batasrki/74e4e62974eb8dde3e84.

Any help is appreciated.

**Comment by ohpauleez** [comment]
Hi @batasrki!  Thanks for using Pedestal and reaching out for help.  In the future, you might want to use the [mailing list](https://groups.google.com/forum/#!forum/pedestal-users) - more people are available there to help.

In the gist, the code is correctly only sending one event.  A `go` block, only runs once, just like a normal block.  You'll either need to use a `go-loop` or use `loop` within your go-block.

A few additional things you should be aware of:
 * The `stream-ready-fn` is usually to just setup the channel (potentially store it in an atom), not really for sending your events.
 * The `stream-ready-fn` takes [two args](https://github.com/pedestal/pedestal/blob/master/samples/server-sent-events/src/server_sent_events/service.clj#L40), The event channel (that you should be using) and the Pedestal context for that given request.
* "Broken Pipe" errors usually mean the other end (client side) has closed the connection, but Jetty wasn't aware of it (because of TCP keepalive).

If you fix your code up, and you're still getting errors, just re-open this bug. Thanks!

**Comment by batasrki** [comment]
Apologies for having to re-open this issue again, but I made the suggested changes (I believe) and got the same result. I then posted to the mailing list, also as suggested, here, https://groups.google.com/forum/#!topic/pedestal-users/J8oj33cg_e0. There has been no response there and I'm at a loss.

Any help is still appreciated.

**Comment by batasrki** [comment]
Also, I'm unable to re-open this issue.

**Comment by jonpither** [comment]
I have the same issue

**Comment by ohpauleez** [comment]
Let me update the sample code and see if I can recreate.  I haven't seen this behavior myself.

**Comment by ohpauleez** [comment]
The SSE sample works correctly: https://github.com/pedestal/pedestal/tree/master/samples/server-sent-events

**Comment by ohpauleez** [comment]
@jonpither Can you point me to a repo where the bug is happening so I can recreate locally?

**Comment by jonpither** [comment]
Behind a firewall, doing as per the current sample.

**Comment by ohpauleez** [comment]
The firewall is killing the HTTP connection?  If so, there's nothing Pedestal or Jetty can do to prevent that from happening.  @batasrki Are you also behind a firewall?  Is something else killing your SSE/HTTP connection?

**Comment by ohpauleez** [comment]
@jonpither Are you able to tell me what the TCP keepalive settings on the firewall are?  Can you confirm that the keepalive probes are making their way through the firewall?  My initial guess is that the firewall is very aggressive about determining if a client is idle/dead, or it is not forwarding keepalive probes and the client connection is closing before another event can be sent.

**Comment by martintrojer** [comment]
I expect this to be a network issue, where some corporate network equipment don't expect HTTP connections to;

a) stay alive for long periods and 
b) have no buffering

CC @malcolmsparks

**Comment by ohpauleez** [comment]
@martintrojer My thoughts too.  I'm going to close the issue again, but I'm more than happy to keep this thread going here.

**Comment by jonpither** [comment]
I wouldn't be surprised. 

It's pretty reliable to be produced though. I'll get back to this thread if I find anything more concrete.

I just reloaded a client side page as to generate a new SSE connection, and this produced the error, as though my code was trying to write to the old event stream for the previous page load, which has been closed.

**Comment by batasrki** [comment]
@ohpauleez no, the firewall wasn't the problem for me. I saw this problem on localhost, but I think I have found a workable solution.

The key is to ensure that all functions in the call chain stemming from `start-event-stream` route return either the channel provided by the interceptor or the context. Returning something other than one of these two throws the `Broken Pipe` error. The one curious thing, though, is that even though I am returning the channel from each function, I still occasionally get the `Broken Pipe`. I'm not sure why.

**Comment by djjolicoeur** [comment]
I know this is a closed issue, but just spent some time digging around this issue myself and thought I would share my insights on this thread. 

Maybe I'm wrong, but I came across the `Broken Pipe` issue myself, and it would appear that this is coming from from [here](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L105). 

At least in my case, if I close a browser window or refresh a client with an open SSE stream, the SSE heartbeat is going to eventually try to call `.flushBuffer` on a buffer to an IO sink that no longer exists, throwing an `IOException` in the process.  The `IOException` gets caught, logging that pesky stack trace in the process (making us all think our applications are broken!), and breaks the loop which closes the `resume-chan`.  This also causes the loop in `io.pedestal.http.sse/start-dispatch-loop` to break out of it's `recur` and close the `response-channel` and `event-channel`, as expected, and you should see something like: 
```
INFO  io.pedestal.http.sse - {:line 123, :msg "Response channel was closed when sending heartbeat. Shutting down SSE stream."}
```
 get logged out  

It would appear that the `Broken Pipe` stack trace that is being logged is actually part of normal operations if you have clients disconnecting, is that correct? If so I spent a lot of time tracking down what I thought was an error only to discover it was not, or at least not one I have to worry about.  Seems a bit confusing.  

On a positive note, `core.async` and the SSE stuff in general has made quick work of building a subsystem to push notifications to our clients, so I'm not complaining too much!

**Comment by ohpauleez** [comment]
@djjolicoeur Yep, "Broken Pipe" is normal and shouldn't be investigated.  The same thing happens if you close the browser in the middle of sending a response.
