### ISSUE TITLE
Setting (csrf/anti-forgery {:cookie-token true}) breaks

### ISSUE THREAD

**Issue by lambder** [pedestal/pedestal#386]
Changing one of the interceptor from
(csrf/anti-forgery)
to
(csrf/anti-forgery {:cookie-token true})

causes:
java.lang.IllegalArgumentException: No implementation of method: :form-encode* of protocol: #'ring.util.codec/FormEncodeable found for class: nil
        clojure.lang.ExceptionInfo: Interceptor Exception: No implementation of method: :form-encode* of protocol: #'ring.util.codec/FormEncodeable found for class: nil

having done some debugging I can see that in https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/csrf.clj#L52
the token is tried to be obtained from (:session request) but it is present only in (:session response)

**Comment by ohpauleez** [comment]
Thanks for using Pedestal!  Sorry to hear about the snag you hit.  It seems like there are some [tests](https://github.com/pedestal/pedestal/blob/master/service/test/io/pedestal/http/csrf_test.clj#L156) around this, but none that round-trip.

When addressing this issue we should:
 * Establish a repro case
 * Add round-trip tests

**Comment by ohpauleez** [comment]
I'll be in the CSRF code this week, so I'll see if I can repro this and if so, write a test that captures it.

**Comment by ohpauleez** [comment]
This should be fixed on master now.

**Comment by mavbozo** [comment]
was it fixed? I encounter this error today with pedestal from latest master branch.

I made a repo to reproduce this case https://github.com/mavbozo/pdscerr

**Comment by ohpauleez** [comment]
I'll take another look at it - thanks for the repro @mavbozo!

**Comment by ohpauleez** [comment]
@mavbozo Changes pushed to master.

**Comment by mavbozo** [comment]
@ohpauleez thank you for fixing this problem
