### ISSUE TITLE
Second Example in service-interceptors.md should use 'assoc' instead of 'merge'

### ISSUE THREAD

**Issue by mindbat** [pedestal/pedestal#389]
The second example in the interceptors guide contains a bug: https://github.com/pedestal/pedestal/blob/master/guides/documentation/service-interceptors.md#examples

Specifically, on the very last line of the `::add-foo-header` interceptor definition, it should be using `assoc` instead of `merge`. `merge` expects maps, and while the `:headers` value that `update-in` will use as the first argument to `merge` *is* a map, the additional arguments given are strings.

**Comment by ohpauleez** [comment]
Fixed.  Thank you!
