### ISSUE TITLE
Support vert.x as an HTTP backend

### ISSUE THREAD

**Issue by mtnygard** [pedestal/pedestal#399]
Once we have achieved servlet independence, we can easily interface with Vert.x's async model.

A bonus feature would be to support Vert.x's "executeBlocking" for interceptors that want to return some time in the future.

**Comment by ohpauleez** [comment]
+1 I think this is a fantastic target after the servlet independence changes land.

**Comment by ddeaguiar** [comment]
I think this should be implemented in a standalone repository.

**Comment by devurandom** [comment]
How does this relate to the capability mentioned in the readme that Pedestal can "run Pedestal services on non-Servlet containers"? (https://github.com/pedestal/pedestal/blob/e5ae3f306b52a42e0ea75b21c3175578cc1182d6/README.md?plain=1#L54)
Is there an example how to run Pedestal with "Vert.x, nginx, Netty, etc."?

**Comment by hlship** [comment]
This issue has been open for quite some time. We apologize if it has not received the attention it deserves; given the amount of time that has passed, we are focusing on other urgent issues.  We are closing this issue for the meantime, please re-open if it is still relevant.

**Comment by ohpauleez** [comment]
Noting for others here, if there's a desire to resurrect this- Vertx support is implemented in Pedestal2.
