### ISSUE TITLE
Optimizing routing for small routes; Enhance Prefix-tree

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#401]
The prefix-tree router performs extremely well for a large number of routes, but has inefficiencies and lacks optimizations for a small number of static routes (a common case for data-delivering services).

Some proof-of-work has been done in my [smallrouter sandbox](https://github.com/ohpauleez/smallrouter), but more work needs to be done.
- Profile the prefix-tree router for obvious hotspots
- Determine if there's a faster LCS algorithm
- Consider a routing optimization for a small set of static routes (utilizing arrays)
- Identify any array-based optimizations that can be made in the prefix-tree router

**Comment by ohpauleez** [comment]
Use whatever tooling and visualization gives you answers.  If looking to try something new, consider using [`perf` tooling](https://github.com/jrudolph/perf-map-agent) and generating a [Flame Graph](https://github.com/brendangregg/FlameGraph)

**Comment by ohpauleez** [comment]
You might also consider tricks done in Suffix Trees, like a suffix array (or the prefix equivalent, the [LCP Array](https://en.wikipedia.org/wiki/LCP_array)).  Some good ideas in [this ACM article](http://cacm.acm.org/magazines/2016/4/200160-40-years-of-suffix-trees/fulltext).

We already do a variant of this approach.

**Comment by hlship** [comment]
This issue has been open for quite some time. We apologize if it has not received
the attention it deserves; given the amount of time that has passed, we are
focusing on other urgent issues.  We are closing this issue for the meantime, please re-open 
if it is still relevant.

**Comment by ohpauleez** [comment]
I'm not sure why you would close this issue -- it's still a valid issue that should be worked on.  By closing it, the community is less likely to find it and improve the situation.

**Comment by hlship** [comment]
I was of the understanding that for small routes, linear is a good fit, and prefix tree is better for larger routes. We are trying to focus on actionable issues with great impact ... right now, we want to get 0.6.0 out the door, and then focus on a Jetty10 or 11 implementation.
