### ISSUE TITLE
Wrong order of file and resource interceptors

### ISSUE THREAD

**Issue by henriklundahl** [pedestal/pedestal#402]
Wouldn't switching the order between the [file and resource interceptors](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http.clj#L228-L229) in the default interceptors be more reasonable? That way, when using both, files will be found first and you can easily drop in replacements for static files that are already on the classpath.

**Comment by ohpauleez** [comment]
I tend to approach the problem the other way.  While I'm not inclined to make the swap in the code base, one could certainly make the swap for their own application by setting the `:interceptors` on the service-map.

**Comment by henriklundahl** [comment]
Which other way do you mean?

> While I'm not inclined to make the swap in the code base...

I assume you want to avoid breaking the current behavior?

> ...one could certainly make the swap for their own application by setting the :interceptors on the service-map.

Yes, which is probably for the better anyways...

Thanks.
