### ISSUE TITLE
Tabular routing format enhancements

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#406]
The new tabular routing format is a great addition to Pedestal, simplifying how routes can be captured.

There are some robustness issues that need to be addressed:

 * Duplicate route entries aren't caught until low-level processing happens (just needs documentation to set expectations -  All other route formats report higher up in the processing steps).
 * Tabular routing can break `url-for` - it's currently possible to specify two routes with the same handler (no unique name), and only last-one-wins.
 * There is some interesting behavior when turning a non-sequential into a sequential for route processing (doesn't generate all the routes) - this one may be my own user error.

**Comment by ohpauleez** [comment]
Ok, I've nailed down "sequential" issue - the tabular routes are sensitive to route order, because they generate the route-map sequence directly - the verbose-route foundation avoids this issue.

To recreate:  Take a tabular route definition, and put a more generalized route vec before a specific/constrained route (like `/search` in the route_test), and query against it (as done in `match-query`).

It's unclear is this only happens on the linear search router (which uses the sequence directly to route).

**Comment by mtnygard** [comment]
Hmm, I can see how that would happen. Do we have a general contract that says "more specific always wins?" If so, then that's definitely a bug in the table route parser.

**Comment by ohpauleez** [comment]
This only happens in the linear-search router, where there is a "more specific wins" rule to the order and matching-fn.  This "feature" was removed in the prefix-tree router - it's considered bad practice to use constraints to make routing decisions (those should be made in some route handler/interceptor).

I'd still consider this a bug if someone used table routes with the linear-search router.  I'm working on a fix right now.

**Comment by ohpauleez** [comment]
This just got fixed on e76102378b4ff466aa13e6721c59277ab02689fc
