### ISSUE TITLE
Doc updates for service routing

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#408]
The new [service routing](https://github.com/pedestal/pedestal/blob/master/guides/documentation/service-routing.md) doc is a fantastic addition, but it lacks a few details that should be covered:

 * It should mention the map-based routes syntax
 * The quick reference should cover all three routing formats
 * It should be updated to accurately reflect the changes that will be pulled in once the [route definition refactor](https://github.com/pedestal/pedestal/tree/route-def-refactor) is finished and on master
 * Some examples throughout the doc should illustrate all three formats (to allow users to understand how each format relates)
 * The [constraints section](https://github.com/pedestal/pedestal/blob/master/guides/documentation/service-routing.md#constraints) should be corrected and enhanced: Constraints should not be used to make routing decisions - Constraints are only used to eliminate a route possibility (routing *may* not continue - this is a decision made the router.  In the default case with the prefix-tree router, it does not continue).
 * The doc should illustrate using anonymous functions for handlers with `:route-name`s supplied
 * The main service routing doc should link to the [Terse Routing Format doc](https://github.com/pedestal/pedestal/blob/master/guides/documentation/routing-terse-syntax.md)
 * The [Terse Routing Format doc](https://github.com/pedestal/pedestal/blob/master/guides/documentation/routing-terse-syntax.md) should be updated to reflect the route definition refactor changes

**Comment by mtnygard** [comment]
I think these are all accounted for in master on pedestal/pedestal-docs

**Comment by ohpauleez** [comment]
I agree, thanks!
