### ISSUE TITLE
Zero-copy handling of headers/request/control data

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#410]
Jetty 9 introduced [array-backed tries](https://webtide.com/jetty-9-goes-fast-with-mechanical-sympathy/) - a single, large char[] array, with a tree of indexes for values.  All of this great work is undone when Pedestal makes copies of headers and control data to fulfill the Ring spec - furthermore, it obviously moves us further away from zero-copy.

This changes supersedes the [lazy request-map](https://github.com/pedestal/pedestal/pull/299) work.

Pedestal should strive to offer a Ring-compatible, zero-copy interface to request data provided by the Container.  This allows all optimizations performed by the container to trickle down and relieves GC pressure.

**Comment by claj** [comment]
Woha! This would be awesome!

**Comment by ohpauleez** [comment]
This work is being done the [zero-copy-requests branch](https://github.com/pedestal/pedestal/tree/zero-copy-requests)

**Comment by ohpauleez** [comment]
This is on master
