### ISSUE TITLE
Support Resin as an HTTP Backend

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#412]
Resin is the only major Servlet container not supported on Pedestal, but consistently ranks well (and receives press) from the [Techempower](https://www.techempower.com/benchmarks) benchmarks.

**Comment by yokolet** [comment]
Resin is not available from maven now, https://groups.google.com/forum/#!topic/caucho-resin/IQegApGSQG4 . Resin 5 alpha version (possibly will have maven support) is out but couldn't find on any maven repo yet. To support Resin, we need to ask people to copy all jar archives to somewhere of service's classpath. Also, we may need to exclude resin support from lein sub ....
It won't be a normal support by maven like tomcat or immutant. Does this fit to Pedestal?

**Comment by ohpauleez** [comment]
Hi @yokolet -- That email is talking about the Maven plugin (like our `pedestal-service` template and tooling).  Resin has its own Maven repository -- details are here: http://wiki3.caucho.com/Maven2

You should be able to just add the repository to the project, and pull the latest 4.X version.

**Comment by yokolet** [comment]
@ohpauleez got it. Thanks! I'll setup repository in project.clj and keep working. For some reason, my googling didn't find that repo.

**Comment by yokolet** [comment]
For record, WIP impl is in resin-support branch. Currently, the code has a classloader problem since Resin's addServlet is done by classname (String).

**Comment by yokolet** [comment]
It turned out Resin support is very hard.

- classloader problem
Resin's add servlet is done by classname (String) in a common way. This causes classloader problem. Resin's classloader doesn't know where is Pedestal's ClojureVarServlet. There may a way to add jar archive's absolute path to config file programatically. However, finding actual path to ClojureVarServlet's jar archive failed. Also, ClojureVarServlet's classloader doesn't know where is Resin's jar archive neither. The attempt to create Resin's instances using ClojureVarServlet's classloader (massive reflection) failed.

- Resin's API design
At this moment, Resin's latest version is 4.0.46. However, only older version of Resin API doc is out there, http://javadoc4.caucho.com/ . This makes things confusing.

    Somehow, ClojureVarServlet could be added to Resin's config, however adding servlet mapping is   problematic. To make it happen, com.caucho.server.webapp.WebApp type instance is necessary. Embed API example doesn't create this instance at all.
With the support of IDE, I wrote the code below to hopefully get WebApp instance. Unfortunately, Resin's API design focuses on cloud-ish cluster(s) model. Bunch of stuffs are required to reach to WebApp instance, for example:

```java
package resintest;

import com.caucho.cloud.topology.CloudServer;
import com.caucho.lifecycle.Lifecycle;
import com.caucho.loader.EnvironmentClassLoader;
import com.caucho.resin.HttpEmbed;
import com.caucho.resin.ResinEmbed;
import com.caucho.resin.ServletEmbed;
import com.caucho.resin.WebAppEmbed;
import com.caucho.server.cluster.ServletService;
import com.caucho.server.dispatch.ServletConfigImpl;
import com.caucho.server.host.Host;
import com.caucho.server.resin.Resin;
import com.caucho.server.resin.ResinArgs;
import com.caucho.server.webapp.WebApp;
import com.caucho.server.webapp.WebAppContainer;
import com.caucho.server.webapp.WebAppController;
import com.caucho.vfs.StringPath;

import javax.servlet.Servlet;

/**
 * Created by yoko on 4/20/16.
 */
public class CustomServletByInstance {
    static class PedestalServletEmbed extends ServletEmbed {
        public PedestalServletEmbed(String servletClassName) {
            super(servletClassName);
        }

        public void configure(ServletConfigImpl servletConfig) {
            super.configure(servletConfig);
        }
    }

    private static Servlet getPedestalServletInstace() throws Throwable {
        String classname = "io.pedestal.servlet.ClojureVarServlet";;
        return (Servlet) Class.forName(classname).newInstance();
    }

    public static void main(String[] args) throws Throwable {
        Servlet pServlet = getPedestalServletInstace();
        ServletConfigImpl servletConfig = new ServletConfigImpl();
        servletConfig.setServlet(pServlet);
        servletConfig.setServletName("default");
        servletConfig.setServletClass("io.pedestal.servlet.ClojureVarServlet");
        servletConfig.setServletClass(pServlet.getClass());
        servletConfig.addMapping("/*");
        PedestalServletEmbed servletEmbed = new PedestalServletEmbed("io.pedestal.servlet.ClojureVarServlet");
        servletEmbed.configure(servletConfig);

        ResinEmbed resin = new ResinEmbed();
        HttpEmbed http = new HttpEmbed(8787);
        resin.addPort(http);
        WebAppEmbed webAppEmbed = new WebAppEmbed("/", "/Users/yoko/Projects/sandbox/resin-boo/htdocs");
        webAppEmbed.addServlet(servletEmbed);
        resin.addWebApp(webAppEmbed);
        // desperately want webApp to set servlet mapping... !!
        WebApp webApp = webAppEmbed.getWebApp();

        // below is an attempt, but no luck

        Resin _resin = new Resin(new ResinArgs());
        CloudServer _cloudserver = new CloudServer("embed", "embed", null, 0, "localhost", 8787, false, CloudServer.ServerType.STATIC, true);
        // how to set cloudserver to resin ? this instance needs to get servletservice instance...
        ServletService _service = new ServletService(_resin);
        Host _host = Host.getLocal();
        StringPath _path = new StringPath("/Users/yoko/Projects/sandbox/resin-boo/htdocs");
        EnvironmentClassLoader _loader = EnvironmentClassLoader.create();
        Lifecycle _lifecycle = new Lifecycle();
        WebAppContainer _container = new WebAppContainer(_service, _host, _path, _loader, _lifecycle);
        WebAppController _controller = new WebAppController(_path, _container, "/");
        WebApp _app = _controller.getWebApp();
    }
}
```

Still, I can't figure out how to get WebApp instance.

It's better to come back this issue later.

**Comment by hlship** [comment]
This issue has been open for quite some time, and it looks like some significant effort would be needed to make it work.
Given the amount of time that has passed, we are focusing on other urgent issues.  We are closing this issue for the meantime, please re-open 
if it is still relevant.
