### ISSUE TITLE
Port websocket support over to Immutant backend

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#413]
There is websocket support via `:container-options` for Jetty.  Allow Immutant/undertow to support the same (or similar) container options.

**Comment by andrewhr** [comment]
Sorry if I miss some past discussion on the subject, but I would like to hear if there is some position about having a first-class abstraction for websockets on Pedestal.

With the new _chain provider_ feature, there is any possibility to implement or extend interceptors in a way that we could support this "long-lived, lifecycle based interactions"?

**Comment by ohpauleez** [comment]
It would be difficult to enable uniform handling of WebSockets within the route table, as we do with SSE, because each container exposes WebSockets differently.  We could program against a common interface (like the javax.websocket interface), but that takes a lot of useful functionality off the table, exposed by the containers themselves.

Regardless, we wanted to enable users to apply interceptors to any stream of data (one-shot request-reply, one-way streams like SSE, or bi-directional streams like WebSockets).  The new [interceptor.chain](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/interceptor/chain.clj) features allow you to do this - easily create chains to handle any stream or request-reply.

When we looked at how people are really using websockets in practice, there was very little overlap/integration between what was done in the routes and the data going over websockets.  It was much more common that websockets were just being used as a fat pipe for bi-directional data (location information streaming, for example), or as a streaming control interface for a larger system.

Given that situation, we elected to expose websockets as a common data format, within `:container-options`

All of that said, someone could write a custom chain-provider for a specific container, that mapped/exposed websockets directly into the route table.  At the chain-provider level, you control/determine all interactions between Pedestal and the Container.

I know that's a lot to digest, but let me know if all of that makes sense!

**Comment by andrewhr** [comment]
Thank you a lot for the whole overview!

As I understand, giving the limitations and diminishing returns the Pedestal team opted to play safe and just expose (via a common hook) the raw interface of a given container. So, returning to the issue itself, the idea is to bridge `immutant.web.async` capabilities as a `:container-options` entry. My understanding is correct?

If that's the task, I could provide some initial code so you can review and point me with a more concrete implementation. Anyway, I believe the jetty is already a good reference to follow.

**Comment by ohpauleez** [comment]
Exactly.  The code is already sitting [on a branch](https://github.com/pedestal/pedestal/compare/immutant-websocket-rework), I just need to go and clean it up a bit.

**Comment by ohpauleez** [comment]
This is now on master.
