### ISSUE TITLE
Address the TechEmpower Benchmarks

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#414]
I recently noticed that someone submitted Pedestal to the techempower benchmarks, but it's [woefully misconfigured](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Clojure/pedestal).

We need to either remove Pedestal from the benchmark, or set it up the way we'd run a performance-critical Pedestal application (NIO, custom/minimal interceptor chain, tailored router, etc.).  Furthermore, we'd need to definitely figure out the fastest and most reliable backend for Pedestal (Jetty, Immutant/Underow, Resin, Tomcat, Vert.x, nginx).  This work should only be done once all other 0.5.0 work is completed.

**Comment by ohpauleez** [comment]
All needed functionality has been shipped in the 0.5.x releases.

**Comment by andrewhr** [comment]
Are you working on this @ohpauleez? Some time ago I've take a look at those benchmarks and how they could be improved in general.

In particular, I believe they are a kind of noisy to compare between different clojure implementations and to compare clojure with alternative stacks. Maybe a major refactor of how they're wrote would be good - I did it but only for pedestal.

**Comment by ohpauleez** [comment]
I am not actively work int them.  I encourage anyone from the community to take stab at them.  Please post links to possible candidates here, before submitting changes directly to the Benchmark repo.

As a starting point, you could look at the [fast pedestal sample](https://github.com/pedestal/pedestal/tree/master/samples/fast-pedestal) to get some ideas.

**Comment by ohpauleez** [comment]
A new Pedestal version has been submitted via [a pull request](https://github.com/TechEmpower/FrameworkBenchmarks/pull/2521) to the TechEmpower repo.  Once the Pull Request is accepted and Round 14 is published, I'll close this ticket.

**Comment by ohpauleez** [comment]
PR was accepted, just awaiting for the round results.

**Comment by jcf** [comment]
The results from round 14 has been published, and the changes made have significantly improved Pedestal's numbers (as can be seen in the diff below).

https://www.techempower.com/benchmarks/diffs/r13-r14.html

**Comment by jcf** [comment]
The results from round 14 has been published, and the changes made have significantly improved Pedestal's numbers (as can be seen in the diff below).

https://www.techempower.com/benchmarks/diffs/r13-r14.html

**Update:** I was surprised to see Aleph running an order of magnitude more requests than Pedestal. Having not profiled the code I'm not sure if use of [clj-tuple](https://github.com/TechEmpower/FrameworkBenchmarks/blob/eb7321cffd3e332796b031c6e4fb7ed84e9202f7/frameworks/Clojure/aleph/hello/src/hello/handler.clj) might even things out a bit, and wonder if using Immutant rather than Jetty may be worth a try?

**Comment by ohpauleez** [comment]
Thanks for publishing back here with the results and the diff @jcf!

The results and ratios of the published test differ greatly from those we saw when running the TechEmpower Benchmark in three separate configurations.  We may publish our results in this issue thread as a means to involve the community on helping sort out the discrepancies.  Regardless, we're already looking into it.

**Comment by ohpauleez** [comment]
In the latest round, [Pedestal is doing quite well](https://www.techempower.com/benchmarks/#section=data-r16&hw=ph&test=fortune&l=hnfih7), and compares even better when on cloud infrastructure.  There are still other chain provider implementations that should be even faster, if we want to bump it up even more.

**Comment by hlship** [comment]
This issue has been open for quite some time. We apologize if it has not received
the attention it deserves; given the amount of time that has passed, we are
focusing on other urgent issues.  We are closing this issue for the meantime, please re-open 
if it is still relevant.
