### ISSUE TITLE
Is it possible to get a report of the context after each interceptor?

### ISSUE THREAD

**Issue by Malabarba** [pedestal/pedestal#416]
Hi there,

I need to figure out which interceptor is `assoc`ing a response into the context. Is there a straightforward way to get a log of what was the context returned by each interceptor after a request is done (or while it's being processed)?

cc. @mtnygard

**Comment by ohpauleez** [comment]
Hi and thanks for using Pedestal!

The interceptor chain has a lot of logging that should show you what you're after.  Take a look at [the chain implementation](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/impl/interceptor.clj#L131)

The context is logged per interceptor on both enter and leave.
It also logs [when a chain terminators](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/impl/interceptor.clj#L92) - that is, when an interceptor places a response in the context (when running on a servlet).

I'm going to close this issue.  If you have more questions, you should follow up on the [mailing list](https://groups.google.com/forum/#!forum/pedestal-users)

**Comment by Malabarba** [comment]
Thanks for the reply! 
And sorry for the noise, I should've gone to the mailing list.

Cheers
