### ISSUE TITLE
Template converted to use embedded Tomcat stops running as server is launched.

### ISSUE THREAD

**Issue by ClassicThunder** [pedestal/pedestal#424]
### Overview

Template converted to use embedded Tomcat stops running as server is launched. We would like to use the embedded Tomcat as our dev environment since our production environment is a war and deployed on Tomcat.

### Software Versions

Lein/Java: Leiningen 2.5.3 on Java 1.8.0_91 Java HotSpot(TM) 64-Bit Server VM
OS X: 10.10.5
Clojure: 1.8.0
Pedestal: 0.4.1

### Steps to reproduce:

1. Create a new project
```lein new pedestal-service tomcat```
2. Change ```::bootstrap/type :jetty``` to ```::bootstrap/type :tomcat``` and update the project.clj
3. Execution completes as soon as the server is launched.

```
name:tomcat user$ lein run-dev
Retrieving clj-time/clj-time/0.9.0/clj-time-0.9.0.jar from internal_repo
Retrieving clj-time/clj-time/0.9.0/clj-time-0.9.0.jar from internal_repo
WARN  o.a.catalina.core.StandardContext - A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []

Creating your [DEV] server...
WARN  o.a.catalina.core.StandardContext - A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
INFO  o.a.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
INFO  o.a.catalina.core.StandardService - Starting service Tomcat
INFO  o.a.catalina.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.0.24
INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
name:tomcat user$ lein new pedestal-service tomcat
```

The base project using ```::bootstrap/type :jetty``` and the Jetty dependency works fine.

**Comment by ohpauleez** [comment]
Thanks for a great bug report!  This is just a small issue with recognizing the `:join?` flag.  @yokolet is working on the Tomcat pieces this week, and she'll report back once she digs into the issue.

**Comment by ohpauleez** [comment]
This is the expected effect of setting `:join` to false.  Jetty is the backend not respecting `:join` when it's the main calling thread.

Usually the `run-dev` alias isn't used.  It's more common to call `(run-dev)` from a repl.

**Comment by ClassicThunder** [comment]
Awesome thanks for the help.

**Comment by ohpauleez** [comment]
Anytime!
