### ISSUE TITLE
Support container/WriteNIOByteBody on Tomcat backend

### ISSUE THREAD

**Issue by yokolet** [pedestal/pedestal#426]
The feature is missing when Tomcat is on the backend.

**Comment by yokolet** [comment]
Implementation is in tomcat-nio-support branch. Also tests were added which passed with newly added nio support.

**Comment by ohpauleez** [comment]
I'm going to kill this issue.  There doesn't appear to be a way to support NIO for Tomcat without allocating Buffers from scratch.  A general approach (using Servlet's 3.1 non-blocking support with Listeners), will be supported via channels.
