### ISSUE TITLE
unable to exit hello world 

### ISSUE THREAD

**Issue by mkno** [pedestal/pedestal#428]
ctrl+d ctrl+c doesn't seem to work and unable to stop the running hello world service 

using win 7

any suggestions?

**Comment by ohpauleez** [comment]
Hi @mkno - Thanks for using Pedestal and reporting the issue!  None of the core developers of Pedestal have a Windows machine, which makes it difficult for us to debug Windows-specific defects.  While we wouldn't reject Windows-specific improvements, we really only support Unix-based OSes (OSX, Linux).  It sounds like you might be have [this issue](http://superuser.com/questions/766325/ctrl-c-not-killing-process-in-cmd-exe) - unrelated to Pedestal?

**Comment by mkno** [comment]
I agree this isn't pedestal specific more likely a cygwin issue... man I really didn't expect to be hunting around on fixing a basic shell behavior on Windows...I'd like to get started but the windows environment poses so much hinderance to get up and running it's quite infuriating actually. 

My fault for not owning a Mac

**Comment by ohpauleez** [comment]
You could consider just downloading VirtualBox, installing a Linux VM, and using the VM.

**Comment by ddeaguiar** [comment]
Building on Paul's comment, consider using [Vagrant](https://www.vagrantup.com/) and [synced folders](https://www.vagrantup.com/docs/synced-folders/).

**Comment by mkno** [comment]
ugh really didn't want to fiddle with that extra virtualization layers but seems like I have no choice. 

cannot continue with pedestal on windows environment because of this simple bug caused by cygwin or whatever the hell it is and googling the problem just sends me on a wild goose chase on long mailing lists with no solutions in sight.

really frustrating stuff!

**Comment by ddeaguiar** [comment]
In my experience it's never been that big of a deal. Given that your deployment environment will be some *nix flavor you'd be doing yourself a favor anyways. The sync'ing of folders allows you to gain the benefit of developing against your deployment environment while using your preferred IDE. Management of the development image is minimal. You'll also benefit from the ability to leverage a shared development image across the development team. The importance of that depends on context but I can't tell you how many times the idiosyncrasies of local development environments has led to issues further down in the build/deploy pipeline.

I developed in Windows for a long time. My frustration with that environment dwarfs any frustrations I've encountered with the tooling I've described.

**Comment by mkno** [comment]
@ddeaguiar using Vagrant and synced folders and its working great....but now running into this issue with the hello world example https://github.com/pedestal/pedestal/issues/429

**Comment by mkno** [comment]
@ddeaguiar now it seems like the problem I have is that while in my windows environment `(server/start runnable-service)` correctly ran the server but unable to Ctrl+C out of it but when I try the exact same command via vagrant ssh it now will not run the code....so I'm back to square one lol Exact same source code, exact same nRepl version.
