### ISSUE TITLE
running (server/start runnable-service) in hello world example results in Compiler Exception

### ISSUE THREAD

**Issue by mkno** [pedestal/pedestal#429]
so I followed the lein pedestal-service helloworld example

https://github.com/pedestal/pedestal/blob/master/guides/documentation/hello-world-service.md

then I cd into the project and run `lein repl` but I'm getting the following

```
helloworld.server=> (server/start runnable-service)

CompilerException java.lang.RuntimeException: No such namespace: server, compiling:(/tmp/form-init4347651517860558217.clj:1:1)
```

**Comment by ohpauleez** [comment]
Hi, thanks for using Pedestal.  In the future, you should report issues like this on the [Pedestal mailing list](https://groups.google.com/forum/#!forum/pedestal-users) - there are a lot more people there that can help you.

You're calling a function (`start`) from a namespace that doesn't exist or hasn't been required (`server`).  Notice that you're already in the `helloworld.server` namespace.  You can just call `(def serv (run-dev))` - the docs are a little out of date.

**Comment by mkno** [comment]
```
helloworld.server=> (def serv (run-dev))
CompilerException java.lang.RuntimeException: Unable to resolve symbol: run-dev in this context, compiling:(/tmp/form-init6494148267096741192.clj:1:11)

```

**Comment by mkno** [comment]
while in my windows environment `(server/start runnable-service)` correctly ran the server but unable to Ctrl+C out of it but so I installed vagrant but when I try the exact same command via vagrant ssh it now will not run the code. same source code, exact same nRepl version.

**Comment by ohpauleez** [comment]
Please take this issue on the mailing list, Thanks!
Ignore the documentation guide.  Just `lein new pedestal-service`, then `lein repl`, and `(def serv (run-dev)`.

**Comment by mkno** [comment]
I have posted a link to this issue on the mailing list hopefully somebody can take a look at it tell me what I'm missing. in the future I will use the mailing list to resolve all my issues.

the steps you outlined does not work and results in the same Unable to resolve symbol error.

**Comment by mkno** [comment]
got it working, must use java 8!!!!!
