### ISSUE TITLE
error-dispatch requires use of impl keyword in order to use correctly

### ISSUE THREAD

**Issue by dball** [pedestal/pedestal#431]
Referring to https://github.com/pedestal/pedestal/pull/302, it appears that one must use a pedestal impl keyword in order to use error-dispatch correctly:

```
(def exception-handler
  (error/error-dispatch [context e]
    [{:interceptor ::requires}]
    (assoc context :response {:status 503 :body {:message "System unavailable"}})
    :else (assoc context :io.pedestal.impl.interceptor/error e)))
```

Failing to do this yields an unmatched case exception higher up, not the original exception.

It seems to me that the error-dispatch macro could reasonably append the ultimate :else clause to the matcher part of the form.

**Comment by ohpauleez** [comment]
On master, it's no longer an impl namespaced keyword, now that the interceptor chain pieces are openly public.  I wrestled with the idea of making the macro include the `:else` clause, but instead opted to let users have full control over the matching (allowing someone to swallow exceptions, if desired, or hook up a generic exception handler to catch everything that wasn't matched).
