### ISSUE TITLE
README.md documentation section problems.

### ISSUE THREAD

**Issue by gpellis** [pedestal/pedestal#442]
In the Documentation section under Digging deeper, there are three bullet points. The second and third bullet points have problems. The 'API Docs' link points to documentation for version 0.4.1-SNAPSHOT, and `lein doc` does not actually work for building the docs if you download the repository and try to run it.

With the way the repository is currently structured, the third bullet would need to be something closer to `lein sub install; lein sub codox`. But that, unfortunately, would still require some changes to work. Codox has issues with the code under `service/bench`, some files (web_server_benchmark.clj) will not compile. And the `project.clj` files for the jetty and immutant modules are missing some dependencies, core.async and pedestal.service.

**Comment by ohpauleez** [comment]
Thanks for reporting!  The API docs have been updated on github, the project doc tooling has been adjusted, and the README has updated instructions.

If you want your own local API docs, within the `service` directory, `lein docs`.

**Comment by ohpauleez** [comment]
Another quick update, you should be able to do a `lein docs` from the top-level project now (which would include all the backends -- Jetty, Tomcat, Immutant -- in your docs.
