### ISSUE TITLE
Allow disabling HTTP when HTTPS setups are provided

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#445]
Currently, Pedestal services *always* expose an HTTP port, but some users may want to enforce their service as HTTPS only.  Furthermore, as HTTP/2 use picks up, this case may become increasingly common.

This change proposes that if HTTPS service options are provided, and the standard `:port` option is explicitly set to `nil`, Pedestal will not create any form of HTTP connector (for the containers it ships with).

**Comment by claj** [comment]
I created a branch at https://github.com/claj/pedestal/tree/disable-http-jetty

I have not yet sent in a CA, will try to do that this Monday (June 27).

The code change is quite simple, the major thing is to throw exceptions on illegal configurations (ie h2c enabled, but no :port given, or no :port but no ssl either).

Question: There should be tests for the jetty adapter. This would better test various configurations as well as having clj-http client (or similar) that calls the service, with and without encryption, and optionally a trust-store configured for the client. Should we put such tests in the io.pedestal/jetty artefact? The tests would be dependent on io.pedestal/service as well as clj-http. Is there anything special to think about there?

**Comment by ohpauleez** [comment]
This is on master now.
