### ISSUE TITLE
Set Jetty's truststore from a file as well

### ISSUE THREAD

**Issue by schaffer** [pedestal/pedestal#448]
Currently, to set Jetty's truststore, it's needed to create a KeyStore object and setting :truststore to it.

There should be an option to set it from a file, passing a string as the filename.

I implemented this by changing function ssl-context-factory here: https://github.com/nubank/pedestal/blob/truststore-file/jetty/src/io/pedestal/http/jetty.clj#L44

**Comment by ohpauleez** [comment]
This is now on master.  Thanks!
