### ISSUE TITLE
Set Jetty's SslContextFactory object directly

### ISSUE THREAD

**Issue by schaffer** [pedestal/pedestal#449]
SslContextFactory has many options to be set, so it is useful to build the object externally and pass it to the embedded Jetty.

Also, Jetty allows us to create another class that overrides methods in SslContextFactory and use this class instead (this is done by changing XML files in the standalone Jetty).
In our case (Nubank), we change SslContextFactory to fetch the keystore directly from S3.

We managed that by adding the parameter :ssl-context-factory and changing ssl-context-factory function: https://github.com/nubank/pedestal/blob/ssl-context-factory/jetty/src/io/pedestal/http/jetty.clj#L44

**Comment by ohpauleez** [comment]
This is now on master.  Thanks!
