### ISSUE TITLE
Is it :interceptorfn or :interceptor-fn?  [0.5.0]

### ISSUE THREAD

**Issue by hlship** [pedestal/pedestal#454]
The documentation for service routing states that a function with meta data `:interceptor-fn` is in fact a function to generate the interceptor.

However, the code, https://github.com/pedestal/pedestal/blob/master/interceptor/src/io/pedestal/interceptor.clj#L38 , make it look like `:interceptorfn` is the correct keyword (no dash).

**Comment by ohpauleez** [comment]
The metadata is no longer needed and is discouraged (line 38 you linked is only there to support backwards compatibility).  You can just call the function within your routers, and the Interceptor API will extract the interceptor it returns.  `(my-interceptor-fn :arg1 :arg2)`

**Comment by hlship** [comment]
Backwards compatible or not, the documentation (or the code) is wrong.  Fortunately, the stuff I'm working on does rely on this.

**Comment by ohpauleez** [comment]
It is no secret that the docs are currently out of date from the current code base.  We've been working on a replacement for the docs, potentially a new site, and rebooting some form of community-controlled docs via the github wiki.  Feel free to jump in, all help is appreciated.
