### ISSUE TITLE
Document that :env key is a common practice, but not required

### ISSUE THREAD

**Issue by hlship** [pedestal/pedestal#455]
Searching the code for how `:env` is used, it is apparent that labeling the configuration in this way is a good practice, but is not meaningful to the Pedestal framework ... not code appears to de-reference the `:env` key from the service map.

**Comment by ohpauleez** [comment]
Hi @hlship! Thanks for using Pedestal and reaching out.  In the future, these kinds of questions should be directed to the [Pedestal mailing list](https://groups.google.com/forum/#!forum/pedestal-users).  We typically only use Github issues for bug reports, feature requests, and release planning.

Within the service map, `:env` doesn't trigger any functionality on or off.  It's a typical pattern in Pedestal services to use that key in your own application code to trigger ns-reloading and other dev functionality.  We also use it as a shorthand for "treat these settings as dev-only," which is not a hard-and-fast rule.
