### ISSUE TITLE
Warnings for shadowed functions in Clojure 1.9

### ISSUE THREAD

**Issue by grzm** [pedestal/pedestal#456]
# Description
When using `org.clojure/clojure "1.9.0-alpha11"`, I see the following warnings due to functions in Pedestal dependencies shadowing clojure.core functions.

```
WARNING: seqable? already refers to: #'clojure.core/seqable? in namespace: clojure.core.incubator, being replaced by: #'clojure.core.incubator/seqable?
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/boolean?
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/boolean?
WARNING: bounded-count already refers to: #'clojure.core/bounded-count in namespace: clojure.core.async, being replaced by: #'clojure.core.async/bounded-count
```

## Expected Behavior
I expect to see no warnings. 

## Actual Behavior
I see the following warnings:

```
WARNING: seqable? already refers to: #'clojure.core/seqable? in namespace: clojure.core.incubator, being replaced by: #'clojure.core.incubator/seqable?
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/boolean?
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/boolean?
WARNING: bounded-count already refers to: #'clojure.core/bounded-count in namespace: clojure.core.async, being replaced by: #'clojure.core.async/bounded-count
```

## Steps to reproduce
Build a Pedestal app using `[io.pedestal/pedestal.service "0.5.0"]`.

# Environment
```
λ javac -version
javac 1.8.0_45
```

## Operating System (including version).
Mac OS X 10.10.5

## Your current Leiningen version (`lein --version`)
```
λ lein --version
Leiningen 2.6.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM
```
## Pedestal version

`io.pedestal/pedestal.service "0.5.0"`

**Comment by grzm** [comment]
You're likely already aware of these. Including it just to keep track of them.

Looks like some (but not all) of these dependencies already have released versions including the fixes:

## clojure.core.incubator
```
WARNING: seqable? already refers to: #'clojure.core/seqable? in namespace: clojure.core.incubator, being replaced by: #'clojure.core.incubator/seqable?
```

https://github.com/clojure/core.incubator/commit/0a3b741c2757ff77cfaf2bf774bdc9cf407944cf

Fix is in current release [org.clojure/core.incubator "0.1.4"]

## tools.analyzer

```
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/boolean?
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/boolean?
```
https://github.com/clojure/tools.analyzer/commit/c375596ca76f79d701132d75c4021aeb4a3d20d4
Fix is in the current release [org.clojure/tools.analyzer "0.6.9"]

## core.async

```
WARNING: bounded-count already refers to: #'clojure.core/bounded-count in namespace: clojure.core.async, being replaced by: #'clojure.core.async/bounded-count
```
https://github.com/clojure/core.async/commit/43139e44b04dd09bb5faa555ea8ebd2ca09e25ce
Not in [org.clojure/core.async "0.2.385"], current release.

**Comment by grzm** [comment]
After checking out d5604cf7a5195d7ab3171ad6771aaf578d1db326 and installing it locally, I'm now only seeing the following expected warning:
```
WARNING: bounded-count already refers to: #'clojure.core/bounded-count in namespace: clojure.core.async, being replaced by: #'clojure.core.async/bounded-count
```
Once there's a new release of core.async, we should be good to go.

**Comment by ohpauleez** [comment]
I'm going to close this and before cutting the next release, I'll make sure to bump dep versions again.
