### ISSUE TITLE
io.pedestal.http.body-params/add-params doesn't support extended content-types

### ISSUE THREAD

**Issue by claj** [pedestal/pedestal#460]
# Description

I have not encountered this bug, but it would be highly confusing if I did.
## Expected Behavior

When adding a content-type with add-params, that contains a +-sign (or any other regexp character, for that matter) I  expect it to match the exact string given to add-parser.

Ie if I write 

`(add-parser ...parser-map... "application/transit+json" ...some-transit-parser-fn...)`

I expect it to match content-types that is exactly `application/transit+json`.
## Actual Behavior

When adding a content-type with +-signs in it, say `"application/transit+json"` (except the fact that it's already supported) the add-params will not escape the +-sign in the content-type rendering regexp, which will lead to that it matches something else than  `"application/transit+json"`.

(from [io.pedestal.http.body-params/add-params (line 56)](https://github.com/pedestal/pedestal/blob/4b5f792dbe81de4c6521aa1e3b82f46eea3e42f6/service/src/io/pedestal/http/body_params.clj#L56))

```
(re-pattern (str "^" "application/transit+json" "$"))
=> #"^application/transit+json$"

```

which does not match the exact verbatim string given as argument:

`(re-matches #"^application/transit+json$" "application/transit+json")
=> nil`
## Steps to reproduce

Try to add a parser for a content-type  with a + in it and try to match it for an incoming request with that exact content-type.
# Environment

Not applicable.
## Operating System (including version).

Not applicable.
## Your current Leiningen version (`lein --version`)

Not applicable.
## Pedestal version

Pedestal 0.5.2-SNAPSHOT (as well as earlier versions with `add-parser`)

**Comment by grzm** [comment]
Looks like perhaps `content-type` should be wrapped in `java.util.regex.Pattern/quote`, i.e.,
```clojure
(defn add-parser
  [parser-map content-type parser-fn]
  (assoc parser-map (re-pattern (str "^" (java.util.regex.Pattern/quote content-type) "$")) parser-fn))
```
I don't *think* the `content-type` is intended to be some kind of pattern match.

**Comment by grzm** [comment]
@claj Do you have an example of how `add-parser` is used? I'm trying to build a test case and haven't used this before.

**Comment by grzm** [comment]
Also, if this isn't being used as a pattern, why not just use a direct string comparison? Isn't a regex pattern more expensive?

**Comment by grzm** [comment]
I see that `add-parser` was just touched in June by @ohpauleez:
https://github.com/pedestal/pedestal/commit/d87146f2150973d86667ff29fbed2b206f0375b6

Looking for the bug it fixed, I don't see a corresponding closed issue. @ohpauleez do you recall what prompted the fix?

**Comment by ohpauleez** [comment]
I would like to do a deeper review of this code.  I agree the current behavior is odd, given that Clojure has regex literals (for exactly this kind of usecase).  It seems like we should use Strings for exact match and regex literals for regex matching, but I'd like to spend some more time thinking about the implications of that change.

**Comment by ohpauleez** [comment]
Fixes for this are on master, although I think `add-parser` is very rare.  More often than not, someone specifies/passes the parser-map to `body-params` at the creation of the interceptor.  Regardless, `add-parser` is not inline with the rest of the code -- it accepts regex patterns as an argument or otherwise properly quotes the string arg.
