### ISSUE TITLE
Unexpected behavior restarting tomcat server via io.pedestal.http/start and io.pedestal.http/stop

### ISSUE THREAD

**Issue by ClassicThunder** [pedestal/pedestal#470]
# Description
## Expected Behavior

When `(bootstrap/stop runnable-service)` is called Chrome is unable to establish a connection.

```
This site can’t be reached
localhost refused to connect.
```

When `(bootstrap/start runnable-service)` is called Chrome is able to navigate to the defined paths.

I want to be able to start and stop the server without exiting the repl. 
## Actual Behavior

The first `(bootstrap/stop runnable-service)` results in the browser waiting for a respnse indefinitely and the second  `(bootstrap/start runnable-service)` results in tomcat displaying its standard 404 message at urls that worked previously.
## Steps to reproduce

Using the below code
- Launch the REPL
- Run the command `(bootstrap/start runnable-service)` the home and about page are reachable via my browser.
- Run the command `(bootstrap/stop runnable-service)` the browser waits for a response indefinitely.
- Run the command `(bootstrap/start runnable-service)` the browser returns a the stock tomcat 404 page of the home and about page.

```
(ns pedestal-refapp.core
  (:gen-class)
  (:require [io.pedestal.http :as server]
            [io.pedestal.http.body-params :as body-params]
            [io.pedestal.http :as bootstrap]))

(defn about-page
  [request]
  {:status 200
   :body "about-page"})

(defn home-page
  [request]
  {:status 200
   :body "home-page"})

(def common-interceptors [(body-params/body-params) bootstrap/json-body])


(def routes #{["/" :get (conj common-interceptors `home-page)]
              ["/about" :get (conj common-interceptors `about-page)]})


(defonce runnable-service (server/create-server
                           {
                            :env :prod
                            ::bootstrap/join? false
                            ::bootstrap/routes routes
                            ::bootstrap/type :tomcat
                            ::bootstrap/port 8080}))
```
# Environment
## Operating System (including version).
- OS X El Capitan
## Your current Leiningen version (`lein --version`)
- Leiningen 2.6.1 on Java 1.8.0_102 Java HotSpot(TM) 64-Bit Server VM
## Pedestal version
- 0.5.0

**Comment by ClassicThunder** [comment]
Also I tested it using Jetty instead of Tomcat and it works as expected.

**Comment by ohpauleez** [comment]
I'm going to take a stab at this today (I have some ideas), but we might be at the mercy of Tomcat.  I also typically recommend that people don't restart the server at the REPL when developing (it shouldn't be necessary in dev mode).

You might find some helpful hints in the [dev/repl doc](http://pedestal.io/guides/developing-at-the-repl) -- "In dev-mode, you should never have to restart the server - changes are picked up as soon as they’re required/reloaded."

**Comment by ohpauleez** [comment]
I'm inclined not to change the code as it does exactly as it promises -- it starts and stops a service.  While some containers allow you to restart a stopped container, not all do (which is why a `restart` function isn't part of Pedestal).

There is good new though!

If you want to pause and resume your service on Tomcat you can with the `org.apache.catalina.startup.Tomcat` server object.  Here is how you...

pause:
`(.pause (.getConnector ^Tomcat server))

and resume:
`(.resume (.getConnector ^Tomcat server))`

This however doesn't close the socket, which means you'll still see the hanging behavior in the browser, but `resume` won't result in a 404 (since the context isn't destroyed).
