### ISSUE TITLE
url-for docstring for :override parameter

### ISSUE THREAD

**Issue by christianromney** [pedestal/pedestal#473]
# Description

The docstring for `io.pedestal.http.route/url-for-routes` describes the options that can be passed to the returned function (and, by extension, url-for). One of these options is `:override` which is stated to be "A map of aspects of the matching route to override including any of: `:scheme`, `:host`, `:port`." The wording is a bit confusing.

## Expected Behavior

Based on the description of the `:override` parameter being a map, I would expect to override the scheme, host and port like so:

```clojure
(url-for ::foo/page :override {:host "localhost" :scheme :http :port 8000} :absolute? true)
```
## Actual Behavior

This fails. The correct syntax omits the `:override` key and places the nested map's elements directly at the top level:

```clojure
(url-for ::foo/page :host "localhost" :scheme :http :port 8000 :absolute? true)
```
## Steps to reproduce

* Generate a new Pedestal service
* Require the following namespaces / aliases
```clojure
[io.pedestal.http.route :as route]
[io.pedestal.http.route.definition.table :refer [table-routes]]
```
* Put this function in server.clj 
```clojure
(defn url-for
  "Returns a url string for the named route"
  [route-name & opts]
  (let [f (route/url-for-routes (table-routes service/routes))]
    (apply f route-name opts)))
```
* Try the expected / actual examples above at the REPL

# Environment

## Operating System (including version).

macOS Sierra 10.12

## Your current Leiningen version (`lein --version`)

Leiningen 2.7.1 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM

## Pedestal version

0.5.1

**Comment by ohpauleez** [comment]
I believe the correct fix is just a better/correct doctring.  Do you agree?

**Comment by christianromney** [comment]
Yes, absolutely. It should be a simple fix, I just wanted to have a quick (virtual) chat about it before presuming to open a PR.
