### ISSUE TITLE
url-for omits trailing slash in combination with map tree router

### ISSUE THREAD

**Issue by rauhs** [pedestal/pedestal#477]
# Description

Using `url-for-routes` sometimes omits the trailing slash even though this is how it is specified in the route definition
## Expected Behavior

Return the URL as defined.
## Steps to reproduce

```
((io.pedestal.http.route/url-for-routes
   (io.pedestal.http.route.definition.table/table-routes
     [["/api/"
       :get identity
       :route-name :x]]))
  :x)
;; => "/api"
```

Note, this will also 404 since the router seems to match for the exact URL.
## Pedestal version

0.5.0

**Comment by ohpauleez** [comment]
I'll look into this soon.  Be advised though, Pedestal discourages trailing-slashes universally.  I would expect you might find some other situations where Pedestal ignores or removes the trailing slash from routes.

**Comment by ohpauleez** [comment]
There is a fix for this on the `url-for-trailing-slash` branch.  It will be merged with master after some more testing.

Just another reminder, trailing slashes are strongly discouraged within Pedestal services

**Comment by ohpauleez** [comment]
This is now on master. Thanks!
