### ISSUE TITLE
StatsD Metrics Reporter

### ISSUE THREAD

**Issue by semperos** [pedestal/pedestal#481]
# Description

When recording Pedestal metrics via a StatsD recorder/reporter, the payloads that Pedestal sends to the StatsD server contain illegal metric names (using a leading `:` character, derived in Pedestal from the [straight stringification](https://github.com/pedestal/pedestal/blob/7250c9a33aaffcbf909ba7f4e20f895445bdfd52/log/src/io/pedestal/log.clj#L299-L323) of keywords used for metric names), which causes the StatsD server not to record the metrics and instead log an error. The colon is reserved by StatsD as a separator between the metric name and the value being recorded.

I've verified that by refactoring the `counter`, `gauge`, `histogram`, and `meter` functions in the `io.pedestal.log` namespace to do something other than `(str metric-name)` where `metric-name` appears always to be a namespace-qualified keyword, I'm able to get StatsD metrics reporting working. Under the perhaps-mistaken assumption that `metric-name` is always a namespace-qualified keyword, my local fix simply does the following in the place of `(str metric-name)`:

```clj
(str (namespace metric-name) "." (name metric-name))
```

## Expected Behavior

Using a StatsD reporter for Pedestal metrics, metrics are published successfully to the StatsD server when running a Pedestal app.

## Actual Behavior

Pedestal publishes metrics to StatsD with illegal names, with StatsD reporting them as "bad lines" and not able to record them. Here is an example:

```
9 Nov 20:45:59 - DEBUG: :helloworld-metrics.service/statsd-hits:1|g
9 Nov 20:45:59 - DEBUG: Bad line: helloworld-metrics.service/statsd-hits in msg ":helloworld-metrics.service/statsd-hits:1|g"
```

## Steps to reproduce

1. Clone the StatsD repo: `git clone https://github.com/etsy/statsd && cd statsd`
2. Add a `config.js` file with the StatsD configuration found below in this issue.
3. Run StatsD with `node stats.js config.js`
4. Clone the Pedestal repo: `git clone https://github.com/pedestal/pedestal && cd pedestal`
5. Step into the metrics sample project: `cd samples/helloworld-metrics`
6. Run the sample project: `lein run-dev`
7. Hit the page of the app which sends metrics to StatsD at [http://localhost:8080/statsd](http://localhost:8080/statsd)
8. Observe StatsD log output, specifically the `DEBUG` output lines that indicate the metrics published are `Bad line`s

# Environment

## Operating System (including version).

Mac OSX 10.11.6 (El Capitan)

## Your current Leiningen version (`lein --version`)

Leiningen 2.7.1 on Java 1.8.0_60 Java HotSpot(TM) 64-Bit Server VM

## Pedestal version

As found in the sample project in this repo at commit 1ee713e, `[io.pedestal/pedestal.service "0.5.1"]`.

## Node version (used for running StatsD locally)

v5.10.1 

## StatsD version

I run StatsD locally from a checkout of the repo at https://github.com/etsy/statsd, tested with commits ff845eb and 02eae13 with same behavior, using config:

```js
{
  dumpMessages: true,
  debug: true,
  port: 8125,
  backends: [ "./backends/console" ]
}
```

**Comment by ohpauleez** [comment]
Thanks for the report @semperos!

The straight stringification of the keywords was to preserve namespaces with the minimal amount of overhead per metrics call and still support people using strings as their metrics names.

Let me think about the fix a bit more (potentially enforcing metric names need to be namespaced keywords), but I'll have a fix on master shortly.

**Comment by ohpauleez** [comment]
There's a fix on the `metrics-name-update` branch.  I'll merge it master after some more testing.

**Comment by ohpauleez** [comment]
This is now on master.  Thanks for reporting!

**Comment by semperos** [comment]
@ohpauleez Thanks for seeing this through, much appreciated!
