### ISSUE TITLE
Add documentation to the `io.pedestal.interceptors.helpers` namespace which calls out deprecated helpers.

### ISSUE THREAD

**Issue by ddeaguiar** [pedestal/pedestal#483]
# Description
The Pedestal [api docs](http://pedestal.io/api/pedestal.interceptor/io.pedestal.interceptor.helpers.html) are not clear about the current usage recommendations for the interceptor helpers in the `io.pedestal.interceptor.helpers` namespace. These recommendations were briefly discussed in #308 and expanded upon in pull #301. I suggest we add a namespace comment which captures the intended usage of these helpers and/or annotate all the helper macros in the `io.pedestal.interceptor.helpers` namespace with `{:deprecated 0.4.0}` metadata.

Bringing this up because someone ran into this issue today and brought it up in the #Pedestal Slack channel. I'd be happy to submit a PR for either approach.

## Pedestal version
0.5.1

**Comment by ohpauleez** [comment]
A comment in the namespace doc saying, "You should prefer using the Interceptor API directly over these macros.  Avoiding using these macros unless you're porting and existing Pedestal code base" -- or something to that affect.

Then a longer comment section within the file (just below the namespace declaration, before def's begin), explaining these macros pre-date the Interceptor API, they can break AOT compilation, and link to the appropriate issues/merged-PRs.

Thanks a ton @ddeaguiar!

**Comment by ohpauleez** [comment]
This meets all of my expectation.  Thanks so much @ddeaguiar!
