### ISSUE TITLE
Blocking put inside go-loop in SSE

### ISSUE THREAD

**Issue by oliyh** [pedestal/pedestal#484]
Hello,

Our production system suffered a hang today and I found that all the async-dispatch threads were waiting at `send-event` (stack trace below).

Once inside the code it looks like we have a blocking put inside a go loop, which doesn’t look right.

The blocking put is here: https://github.com/pedestal/pedestal/blob/cf3fa1ccd7e9a62d9e4d43ddeebb903b27408190/service/src/io/pedestal/http/sse.clj#L91

Inside the go loop here: https://github.com/pedestal/pedestal/blob/cf3fa1ccd7e9a62d9e4d43ddeebb903b27408190/service/src/io/pedestal/http/sse.clj#L150

It should be `>!` instead of `>!!` or we risk locking up the core async threads.

Does this make sense?
Thanks

```
{

      "state": "waiting",

      "stacktrace": [

        "clojure.core$promise$reify__7005 deref (core.clj:6823)",

        "clojure.core$deref invokeStatic (core.clj:2228)",

        "clojure.core$deref invoke (core.clj:2214)",

        "clojure.core.async$_GT__BANG__BANG_ invokeStatic (async.clj:145)",

        "clojure.core.async$_GT__BANG__BANG_ invoke (async.clj:137)",

        "io.pedestal.http.sse$send_event invokeStatic (sse.clj:91)",

        "io.pedestal.http.sse$send_event invoke (sse.clj:81)",

        "io.pedestal.http.sse$start_dispatch_loop$fn__23544$state_machine__9503__auto____23545$fn__23547 invoke (sse.clj:131)",

        "io.pedestal.http.sse$start_dispatch_loop$fn__23544$state_machine__9503__auto____23545 invoke (sse.clj:131)",

        "clojure.core.async.impl.ioc_macros$run_state_machine invokeStatic (ioc_macros.clj:1012)",

        "clojure.core.async.impl.ioc_macros$run_state_machine invoke (ioc_macros.clj:1011)",

        "clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invokeStatic (ioc_macros.clj:1016)",

        "clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invoke (ioc_macros.clj:1014)",

        "clojure.core.async$ioc_alts_BANG_$fn__9657 invoke (async.clj:383)",

        "clojure.core.async$do_alts$fn__9611$fn__9614 invoke (async.clj:252)",

        "clojure.core.async.impl.channels.ManyToManyChannel$fn__6376$fn__6377 invoke (channels.clj:95)"

      ],

      "name": "async-dispatch-8"

    }

 ```

**Comment by ohpauleez** [comment]
I'm going to start digging into this -- I've never seen this before even on high-volume services using SSE.

What's the volume/rate of outbound SSE events?  How many connected SSE clients where there?

**Comment by ohpauleez** [comment]
If you have a reproducible case, please test against the [non-blocking-sse-send-event](https://github.com/pedestal/pedestal/tree/non-blocking-sse-send-event) branch.

**Comment by oliyh** [comment]
Hi @ohpauleez,

Thanks! I would think (I don't know exactly I'm afraid) that we had tens of SSE connection sending order of 100 events per minute.

I have a workaround for now by providing a sliding buffer to `start-stream`. This seems to help; I have a Gatling test which previously didn't seem able to get above about 40 connections which now seems able to do 1000 although as Gatling also uses core async it's not a definite test case - I'm still experimenting with this.

From what I can tell a misbehaving client could easily block a go thread with that blocking put so I'm surprised this hasn't been seen before.

Cheers

**Comment by oliyh** [comment]
Hi @ohpauleez,

That branch behaves better, thanks.

However I notice from your comment that back pressure has to be considered. Would it be better to use `alts!` instead of `put!` so that a) it would block and provide back pressure (without hard blocking) and b) you could provide `alts!` with the heartbeat timeout as well so that if you couldn't send the message within the heartbeat timeout you could consider the client disconnected.

Hope I've made this clear - sorry I can't provide code but I'm writing this on my phone!

Cheers
Oliy

**Comment by ohpauleez** [comment]
This is on master now.  Thanks!
