### ISSUE TITLE
Malformed request can trigger an internal server error

### ISSUE THREAD

**Issue by ray1729** [pedestal/pedestal#488]
# Description

Incorrectly encoded URL parameters trigger an internal server error.

## Expected Behavior

Server should respond with 400 - bad request.

## Actual Behavior

Server responds with 500 - internal server error.

## Steps to reproduce

Run the hello world application from the Pedestal guide: http://pedestal.io/guides/hello-world

Issue the request `curl http://localhost:8890/greet?q=%`

# Environment

## Operating System (including version).

Ubuntu trusty 

## Your current Leiningen version (`lein --version`)

Leiningen 2.7.1 on Java 1.8.0_77 Java HotSpot(TM) 64-Bit Server VM

## Pedestal version

0.5.1

**Comment by ohpauleez** [comment]
On master.  Thanks!
