### ISSUE TITLE
Interceptor chain hangs on closed channel

### ISSUE THREAD

**Issue by EwenG** [pedestal/pedestal#490]
# Description

When an asynchronous interceptor closes its returned channel instead of putting a well formed context in it, the interceptor chain hangs, the socket is not closed, no response is returned to the client.

## Expected Behavior

The server should respond with internal server error

## Actual Behavior

The server hangs

## Steps to reproduce

Run the application from the gist [https://gist.github.com/EwenG/2f6846a2bad14c50b386](https://gist.github.com/EwenG/2f6846a2bad14c50b386)

Request the url: http://localhost:8080/

# Environment

## Operating System (including version).

OSX 10.11.6

## Your current Leiningen version (`lein --version`)

Leiningen 2.7.1 on Java 1.8.0_91 Java HotSpot(TM) 64-Bit Server VM

## Pedestal version

0.5.1

**Comment by ohpauleez** [comment]
Thanks for reporting this!  I'll be addressing this within the chain itself.

**Comment by ohpauleez** [comment]
This is now fixed on master.  It'll be part of an upcoming release.
