### ISSUE TITLE
Invalid route generated with url-for-routes

### ISSUE THREAD

**Issue by oliyh** [pedestal/pedestal#493]
# Description
```clojure
(require '[io.pedestal.http.route :as route]
         '[io.pedestal.http.route.definition :refer [defroutes]])

(defn all-things [ctx])

(defn make-thing [ctx])

(defroutes sample-routes
  [[["/things/:date"
     ["/" {:get all-things}]
     ["/thing" {:post make-thing}]]]])

((route/url-for-routes sample-routes) ::all-things :params {:date "2017-01-23"})
;; => /things/2017-01-23// ;; the trailing double slash is wrong, and results in a 404 when routing

((route/url-for-routes sample-routes) ::make-thing :params {:date "2017-01-23"})
;; => /things/2017-01-23/thing ;; works correctly
```

## Expected Behavior
The `::all-things` route should have a single trailing slash

## Actual Behavior
In 0.5.1 the behaviour is correct. In 0.5.2 it has a double trailing slash which results in a 404 when passed back into pedestal

**Comment by ohpauleez** [comment]
Thanks for reporting the issue -- this regression occurred when attempting to patch `url-for` with a route table that used trailing slashes across most/all routes.  I'll expand the test to cover nested routes, as you have here.

In general, I'd strongly discourage the use of trailing slashes in URLs.  For common operations, Pedestal should behave correctly, but it discourages trailing-slashes universally.

Semi-related, I'd advise against using URL-params and instead make the route take query-parameters.  Pedestal will further optimize your route tree if no params or wildcards are found in the URLs, resulting in constant-time routing.

**Comment by ohpauleez** [comment]
Also, `defroutes` is no longer needed (all it does is a syntax quote), so feel free to adopt the new style
```
(def routes `[[[ ... ]]])
```

I should have a fix for this on master today

**Comment by ohpauleez** [comment]
Fixed on master.  Thanks for reporting and sorry about the regression!

**Comment by oliyh** [comment]
Thanks @ohpauleez
