### ISSUE TITLE
Samples are using deprecated defroutes

### ISSUE THREAD

**Issue by terjesb** [pedestal/pedestal#494]
Many if not all of the samples are using defroutes, which is deprecated, ref #493.

Which of these would you prefer a PR for switching the samples to:
* terse routes using expand-routes
* table routes using table-routes
* table routes using expand-routes

**Comment by ohpauleez** [comment]
You should only need `expand-routes` if you're consuming the routing data structure programmatically (ie: if you're building your own router).  In the 0.5.x changes, the Router now expects to be passed *any* data structure that is `expand-routes`-able, programmed against a protocol.

If you generate a new sample via `lein new pedestal-service peddemo`, service.clj shows the preferred setup now.  You can also see that setup [here](https://github.com/pedestal/pedestal/blob/master/service-template/src/leiningen/new/pedestal_service/service.clj)

**Comment by ddeaguiar** [comment]
This issue will likely be addressed via #501.

**Comment by ohpauleez** [comment]
The guides and the samples are two separate things ^^

**Comment by ddeaguiar** [comment]
Heh, yes. Sorry about that!

**Comment by ohpauleez** [comment]
No worries!  Thanks for jumping in to help sort thing out!
