### ISSUE TITLE
Websocket handlers should handle flow control/backpressure asynchronously

### ISSUE THREAD

**Issue by mpenet** [pedestal/pedestal#497]
# Description

Context jetty/websocket: 
At first glance it seems that messages sent to websockets are fire & forget, the callback on the jetty side that receives the ACK (http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/websocket/api/WriteCallback.html) is not used, also see http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/websocket/api/RemoteEndpoint.html#sendBytes-java.nio.ByteBuffer-org.eclipse.jetty.websocket.api.WriteCallback- . That means that a slow consumer could cause the handler to drop messages and exceptions to be raised (not to mention it'd cause the channel buffer to fill for nothing instead of signaling the need to exert backpressure upstream). Also the handler would never know about potential write errors.

source in question: https://github.com/pedestal/pedestal/blob/master/jetty/src/io/pedestal/http/jetty/websockets.clj#L22-L51

ws-send could return a promise-chan that'd signal ACK from the receiver and we'd be just one <! away of a proper solution.

**Comment by mpenet** [comment]
I didn't check the read path, but I suspect we might have the same issue in reverse (ex with slow writers)

**Comment by ohpauleez** [comment]
Thanks for reporting the issue @mpenet!

Do you currently have flow control issues with a running system?  Are you doing any queuing outside of the immediate handlers?  Where is the ideal place for you to apply flow controls in your application?

I had originally considered using the callback versions of the Websocket API, but I wanted to hear some "field reports" before I changed the implementation.  I assumed that if someone had issues with flow control, they'd introduce a control mechanism that fit their use-case -- forcing the async callback case for all could hurt throughput/goodput for blasty, small messages.

**Comment by mpenet** [comment]
Hi Paul, 

I am merely evaluating pedestal at the moment. Queuing on my side wouldn't solve the issue, as I can't know if the consumers are actually receiving the messages I send to them. 

The thing is, if you ignore flow control it might be positive on a simple benchmark with very few consumers, but as soon as you have a decent number of concurrent user jetty will be busy filling internal queue(s) for nothing and just delay the inevitable: exceptions and/or drop messages once the queues are full, not to mention all this work done in the void might also cause troubles on the consumers who can actually deal with high rate of messages/frames. In short, when you exert backpressure you allow jetty to be in a more healthy state in the long run and actually serve you're healthy/fast consumer better and use less resources, so be more performant overall. 

Not to mention the fact that you have consistency, the possibility to replay failed sends or just to drop a connection when a number of failures occurred in a row etc etc.

**Comment by mpenet** [comment]
ping

I might be tempted to submit a PR to correct this, if I get any feedback about the issue and if we can agree on the form it might take.

**Comment by ohpauleez** [comment]
Hi @mpenet,

The current implementation uses blocking network calls, which would queue requests at the channel correctly, providing backpressure throughout (albeit, while using up a thread in the core.async pool in  the degraded/waiting case).

Both sendBytes and sendString are, "blocking until all bytes of the message has been transmitted."  Only after they are transmitted is `recur` called within the go-loop.  The read side is controlled by listeners on the WebSocketConnection itself, where listeners only see the framed messages.  I assume Jetty is correctly queuing the incoming messages to signal TCP backpressure when appropriate.
- - - - -

There are some Pedestal users that use WebSockets (most only need "publish/broadcast" so they opt for SSE), but we don't have any field reports that the current implementation doesn't meet their needs.  That said, I'm excited to see your interest in making it better. 

If you'd like to remove the blocking I/O:
 * Add a new protocol for async sending
 * Rewrite the inside of go-loop within `start-ws-connection`

If you hit snags, just report them here.

**Comment by mpenet** [comment]
I got it but I don't think I'd call that proper backpressure/flow control handling. 

Right now I'd consider that a potential DOS issue, 8 slow consumers could lock up the entire core.async threadpool, or if we hit the 1024 put queue limit with a writer that's too fast we'll also have troubles (even tho it's less of an issue that the consumer one). 

Imo, either the go call is swapped for thread and is made safe that way (or a variant of thread that accepts a bounded/fixed size executor service, potentially configurable) or the go block is kept but made blocking IO free.

**Comment by mpenet** [comment]
FYI similar issues will happen here, with async requests https://github.com/pedestal/pedestal/blob/f89d0abe244d0e8385d66a697724ef56180a00e5/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L100-L106

**Comment by ohpauleez** [comment]
@mpenet That particular async response can be ignored- that code path is specifically *only* if someone returned a channel as the response body (discouraged, but allowed for backwards compatibility; I agree that's dangerous/wrong).  The actual async handling of Pedestal is managed by the interceptor chain (using promise channels).

That aside, I agree the better approach is to rewrite the go-loop so it parks when the write is blocked/throttled - non-blocking throughout.

**Comment by hlship** [comment]
I'm working on subscriptions for Lacinia (GraphQL for Clojure) and am using WebSockets. I'm really hoping to see this fixed, as we expect to use subscriptions, and therefore WebSockets, for large numbers of clients over poor (e.g., mobile) connections.

**Comment by mpenet** [comment]
Apparently a 5 month old potential DOS via your whole core.async threadpool if WS is enabled is not considered critical :( We chose another lib for that reason here.

**Comment by ohpauleez** [comment]
@hlship Thanks for letting us know this is important to you and your team.  We'll start on it today/next week!

@mpenet Comments like that aren't encouraging, constructive, or informative.  We originally didn't pick it up because you had originally claimed you were going to start to work on the change.  Additionally, we know of a handful of larger production systems using Pedestal and WebSockets, without issue whatsoever.  It's also difficult to understand how important this change is for users/customers unless people speak up to voice their concern and make their "vote" known, especially given our finite resources to work on the libraries.

**Comment by mpenet** [comment]
I didn't claim anything, I said I "might" and since chose another lib I couldn't justify the time.
Just trying to raise the interest in this issue, as I won't work on it.

**Comment by ohpauleez** [comment]
@mpenet Sorry about the miscommunication and I appreciate you coming back to voice your concern.  Out of curiosity, what library/platform did you end up using?

**Comment by mpenet** [comment]
We use an erlang based service for this now. 

At the time we didn't find a jvm based solution that didn't require to spend days building it from scratch on something like netty and a solution mature/robust enough for our needs.

**Comment by ddeaguiar** [comment]
PR #656 adds support for flow control through a new websocket connection fn. While this is opt-in it should satisfy most users needs for more visibility into and control over message transmission.
