### ISSUE TITLE
There should be a sample for various auth setups

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#500]
As [mentioned on the Pedestal mailing list](https://groups.google.com/forum/#!topic/pedestal-users/MJL0h4ts_mk), the community would like to see some samples around auth setups (via Interceptors, Buddy, and at the ServletFilter level).

In my experience, auth tends to be an integration point (you need to connect your service to some existing auth system), and that integration point greatly differs across projects/organizations.  Nonetheless, some helpful tips and examples would go a long way to helping people get started.

**Comment by ddeaguiar** [comment]
@ohpauleez, I'd be happy to contribute to this but I'm thinking these tips should go in the [pedestal-docs ](http://pedestal.io) site. There are already placeholder sections for auth there. Perhaps this issue should be migrated to the [pedestal-docs](https://github.com/pedestal/pedestal-docs) repo?

**Comment by ohpauleez** [comment]
@ddeaguiar I would love to see guides on the subject (feel free to open an issue!), but I'd also like to see there be sample applications that people can grab as a starting point.

**Comment by ddeaguiar** [comment]
Got it. Thanks for clarifying!

**Comment by zclj** [comment]
@ohpauleez is there any more work to be done for this issue? If so what would be helpful contributions? Or is it only final review that is left?

**Comment by ohpauleez** [comment]
Hi @zclj  - I need to make a final pass on @ddeaguiar's stuff (which is long overdue).  Then we'd just want to use that as the template for creating other samples using other auth systems/libraries/approaches.
