### ISSUE TITLE
Guides should be reviewed and migrated to pedestal-docs

### ISSUE THREAD

**Issue by mtnygard** [pedestal/pedestal#501]
# Description

The docs under `/guides` are out of date. We should review them for content. Guides that are fully represented in pedestal/pedestal-docs should have their content replaced with a message directing the reader to the docs site.

Guides that are not fully represented in pedestal-docs should be migrated and brought up to date.

**Comment by ddeaguiar** [comment]
In the meantime I the doc links in the readme should be updated to point to the [pedestal.io](http://pedestal.io) site.

**Comment by ohpauleez** [comment]
README links have been updated.

**Comment by ddeaguiar** [comment]
These are the remaining guides:
- [war deployment](https://github.com/pedestal/pedestal/blob/master/guides/documentation/service-war-deployment.md)
- [async](https://github.com/pedestal/pedestal/blob/master/guides/documentation/service-async.md)
- [routing terse syntax](https://github.com/pedestal/pedestal/blob/master/guides/documentation/routing-terse-syntax.md)
- [connecting to Datomic](https://github.com/pedestal/pedestal/blob/master/guides/documentation/connecting-to-datomic.md)

**Comment by mtsbarbosa** [comment]
Added a datomic guide:
https://github.com/pedestal/pedestal-docs/pull/160
https://github.com/pedestal/pedestal/pull/716

I thought guides section a good place to add it, but feel free to suggest something else
