### ISSUE TITLE
 CSRF and application/x-www-form-urlencoded data.

### ISSUE THREAD

**Issue by ddeaguiar** [pedestal/pedestal#502]
# Description
When CSRF is activated via the service map, I alway see the _Invalid anti-forgery token_ response when POST'ing `application/x-www-form-urlencoded` data that includes the anti-forgery token.

It works as expected when I enable sessions via the service map and add the CSRF interceptor after the `body-params` interceptor during route configuration.

## Expected Behavior
The request should not be considered invalid when the correct anti-forgery token is submitted in the form params.
## Actual Behavior
The _Invalid anti-forgery token_ response is always returned.
## Steps to reproduce
* Activate CSRF protection via the service map.
* Add an authentication endpoint and submit a request with a content-type of `application/x-www-form-urlencoded` containing the anti-forgery token.

Refer to [this](https://github.com/ddeaguiar/pedestal-csrf-issue) sample app for a demonstration.

This issue seems to go back a few years based on [this](https://stuarth.github.io/clojure/csrf-pedestal/) blog post.

# Environment

Java 1.8.0_112

## Operating System (including version).

MacOS 10.12.3

## Your current Leiningen version (`lein --version`)

2.7.1

## Pedestal version

0.5.2

**Comment by ohpauleez** [comment]
Thanks for a great report!

I typically use CSRF protection in a slightly different setup, so I was never directly affected by this-- it was helpful to have a "traditional" repro case to work against.

I originally attempted allow the CSRF interceptor to access the params information directly from the platform representation, but if access is destructive, that affects everyone else downstream (like `body-params`).
After some time at the whiteboard, I decided that CSRF should imply body-params in the default interceptors (the case where you don't need body-params is minimal and not common).  There is a new CSRF argument/option, `:body-params`, that lets users set the body-params parser map if needed.

This is fixed on master.

**Comment by ddeaguiar** [comment]
Thanks for addressing this!
