### ISSUE TITLE
Cookies missing in Jetty when :h2? true

### ISSUE THREAD

**Issue by claj** [pedestal/pedestal#506]
# Description

We observed that the pedestal application doesn't get the session reliably when having `:h2?` enabled using Jetty. It turned out only one cookie is presented to the pedestal application when using `:h2?` / ALPN functionality.

## Expected Behavior

That our application sees the same cookies as the browser sends in the request.

This works when `:h2?` is disabled.

## Actual Behavior

When our SPA has started, it sends request backs to the server.

### Chrome

At this point, several cookies has been set and, according to Chromes network debugging tool, all of them are sent back to the server like this:

`__lc.visitor_id.8695666=S1491858882.6ef2063bfc; youple=wUuiEgfwvBDVDVpL6UrGrEmnP4b7huv%2FqSO2zpwpOuTt5YNhV32rQ7Zvh1ZqwOhkhfSH6kUEcIyL346vB6J77hPwcLN%2FLQSMEA%2FNRjZf%2BeILbbWesJ5C0IYmQpLUDaTvBb8vZ8ePbKEdmMweJCBQNNkouprMmVAtitABUP8ZcdHp3yZB%2BleDDWbZNirwobE%2FJ71tzVEWggEa9gZ8C5YHhQ%2FmJLS4CZ1LaOmqaMQD%2F6emdE2cpoBfCjGwL7EPIRL8kUCebuHx%2FP%2F0tUDNRIfxaw%3D%3D--m8W4ho%2B2%2FvQ5ozn75oBEEQUjMO%2BKrMMGj6w6GBncR40%3D; lc_window_state=minimized`

In the pedestal application, all cookies but one has mysteriously disappeared.

Relevant parts of the request object looks like this

`:session {}
:cookies {"__lc.visitor_id.8695666" {:value "S1491858882.6ef2063bfc"}}`

the received `:header "cookie"` string looks like this:

`:cookie-header "__lc.visitor_id.8695666=S1491858882.6ef2063bfc"`

### Firefox
The behaviour is consisten with Firefox. The sent cookie header is as follows:

`__lc.visitor_id.8695666=S1491819758.1a84a50d80; cookies-accepted="accepted"; lc_window_state=minimized; youple=hpP4vWgqZ8Ykt%2BuSZ1aGS7SVg%2BZ%2BlxQHNoYurHCox72LilmKX3ikKqOcNGqR37DijeraETHAFUZS1aVzCss%2FotFcRFuc5dCK1wQGi53Yo6QbDY4IC5gO0OMvf3QPJmY1zKXvrGEMMmya8Ht8oR4kQY5LcxcslK%2FOPtIKJVNp6kv%2B77elNSNzdMHJdrQa%2Bwsmp0BQejSExXlkXA2GJ%2FyYoMbWgDod7VapNNgSTSKDQ3Jk5Evnn%2FkPSeuUDTrwQuuluJS7EbPQg9kHSUsA3t2pgA%3D%3D--Ty%2BKlKIkh6u2Nnie9PTNl7p1roEfMGJXjYDr9EDy%2F%2FA%3D`

which results in

`:session {}
:cookies {"__lc.visitor_id.8695666" {:value "S1491819758.1a84a50d80"}}

:cookie-header "__lc.visitor_id.8695666=S1491819758.1a84a50d80"}`

The state and the symptomes are very confusing and took us quite some time to diagnose.

## Steps to reproduce

I will try to come up with a minimum reproducible case. I report it as is, hopefully the error is apparent from the stylobate implementation or from the reported dependencies.

# Environment

Chrome Version 57.0.2987.133 (64-bit)
Firefox 52.0.2 (64-bit)

Pedestal 0.5.2
Clojure 1.9.0-alpha14
Jetty version "9.4.2.v20170220"

[org.eclipse.jetty.alpn/alpn-api "1.1.3.v20160715"]

[ring/ring-core "1.5.1" :exclusions [[org.clojure/clojure]
                                                      [org.clojure/tools.reader]
                                                      [crypto-random]
                                                      [crypto-equality]]]

[ring/ring-codec "1.0.1"]

  :java-agents [[org.mortbay.jetty.alpn/jetty-alpn-agent "2.0.6"]]

## Operating System (including version).
macOS Sieera 10.12.3 (also seen on Ubuntu 16.04)

## Your current Leiningen version (`lein --version`)
Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM

## Pedestal version
0.5.2

**Comment by ohpauleez** [comment]
Thanks for reporting the issue @claj!  Just to clarify, you still have the HTTP 1.1 connector in the setup?  All you've done is set `h2?` to true and supplied the SSL details in the service map?

**Comment by ohpauleez** [comment]
Mostly a note for me or anyone else that tackles this - also see [HTTP/2 and cookies](http://unrestful.io/2015/06/21/cookies.html).

**Comment by claj** [comment]
Yes, our setup looks like this (obviously edited out things)

```clojure

{:env :prod
 ::server/file-path "XXX"
 ::server/container-options {:h2? false ;; setting this to true shows the strange behaviour
                                       :h2c? false ;; (some? http-port)
                                       :keystore "XXX"
                                       :key-password  "XXX")
                                       :ssl-port (config :pedestal-ssl-port)
                                       :context-configurator 
;;context-configurator looks something like ...
(fn [servlet-context-handler]
  (-> servlet-context-handler 
    (add-gzip-handler)
    (jetty-util/add-servlet-filer {:filter DosFilter :path "/XXX"})
    (add-ws-endpoints))

                                       :configurator (... set log handlers ...)
           ::server/enable-session {:cookie-name (config :session-cookie-name)
                                    :store (cookie-store {:key (config :pedestal-cookie-store-password)})}
           ::server/type :jetty
           ::server/join? false
           ::server/routes external-routes
           ::server/not-found-interceptor error-page-404
           ::server/allowed-origins {:allowed-origins ["XXX" "XXX"]}
           ::server/secure-headers (secure-headers config)}
```

Oh, I have ```[javax.servlet/javax.servlet-api "3.1.0"]```, btw.

I read the link you supplied, and both header compression and the various continuations is of course sound(!). I have three theories about this. 

a) something in our setup is fishy - GzipServlet (not nescessary on plain HTTP/2 but how to combine those?)
b) something with websockets doesn't work as expected combined with HTTP/2 - we use them since HTTP/2 doesn't really replace them (yet).
c) the session becomes so large that it is sent as a continuation which is not correctly handled by either jetty or, somehow, pedestal
d) the javascript things on our client inserts cookies on their own, which are sent asyncronously as header changes to the server, which drops them, somehow.
e) the HTTP/2 interface doesn't behave as pedestal expects it to behave - for instance I would guess the lookup-accessor to the request object would be sensitive to timing issues given the more connection oriented version of HTTP/2.

I would guess that Jetty HTTP/2 is already quite widespread in usage, and that a bug such as missing cookies would have been detected long ago - I have looked for such a bug among the [Jetty issues](https://github.com/eclipse/jetty.project/issues), but have not found anything that could explain the problem I see.

I'm happy using HTTP/1.1 for now, but there's something that doesn't feel right.

**Comment by claj** [comment]
Oh, I see that the [HTTP/2 standard section 8.1.2.5](https://http2.github.io/http2-spec/#rfc.section.8.1.2.5) allows the header to contain many COOKIE items, which differs from HTTP/1.1.

It also looks like [Jetty 9.4.3 will enforce RFC6265 compliance](https://webtide.com/jetty-cookies-and-rfc6265-compliance/), which regulates the encoding of certain special characters in cookies, which may or may not be related. Thanks for listening.

**Comment by claj** [comment]
I think the problem is that Ring expects all cookies to be stored as one header string, which is no longer nescessary according to the HTTP/2 standard mentioned above.

**Comment by claj** [comment]
Nope, the [Ring servlet adaptor](https://github.com/ring-clojure/ring/blob/master/ring-servlet/src/ring/util/servlet.clj#L13) do concatenate multiple header occurrences into a comma-separated string, the [Pedestal servlet header](https://github.com/pedestal/pedestal/blob/f89d0abe244d0e8385d66a697724ef56180a00e5/service/src/io/pedestal/http/request.clj#L22) reader seemingly does not.

One could argue that it would be better (performance-/sanity-wise) if the string-concatenation could be avoided. A special cookie adapter for jetty would certainly be possible.

**Comment by ohpauleez** [comment]
Thanks for the great work @claj!  I'll patch this up today and push it out on master for you to try out.

**Comment by ohpauleez** [comment]
If you get a chance, can you try the [extract-all-headers branch](https://github.com/pedestal/pedestal/tree/extract-all-headers) @claj?

**Comment by claj** [comment]
Yes, this solves my issue. I see that all the cookies are present in the context while using HTTP/2. Thanks a lot @ohpauleez!

**Comment by ohpauleez** [comment]
@claj I'm going to land this on master today.  There's no noticeable overhead, loss in throughput, or increased latency in the bench suite or with a production application.
