### ISSUE TITLE
[Refactor proposal] pedestal/http.clj seems to big, maybe split?

### ISSUE THREAD

**Issue by kirillsalykin** [pedestal/pedestal#510]
This file https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http.clj seems too big to me, I think it can be splitted into these parts:
- Response part (all `*-response` + `*-body` parts and `not-found` interceptor)
- Defaults part (default interceptors + dev defaults)
- Creation part (`create-server` etc)

Also some other questions:
1. Maybe I misunderstand but I thought everything servlet related was moved to provider, thus servlet-init etc not needed?
2. Also I propose to add `body-params` and  `keyword-params` interceptors to `default-interceptors`. I can see that now `body-params` are used, but only with `csrf`. Is this intentional secure default?

What do you think?

This refactor seems not that hard, I'd like to help with it.

Thanks.

**Comment by claj** [comment]
I think it would be more confusing to split this up. The service creation logic is a bit large, admitted, but it would be much harder to understand if the (very small) functions and definitions it uses, where sprinkled out in namespaces without any special semantic meaning. I don't see the problem you see regarding the service creation.

I don't know about the servlet and provider-related things.

The reason `body-params` isn't always used, I think, is that one don't want to parse things that should not be parsed, or don't have to be parsed. It could be a security thing, but most of all it's a performance thing, I guess.

**Comment by kirillsalykin** [comment]
> The reason body-params isn't always used, I think, is that one don't want to parse things that should not be parsed, or don't have to be parsed. It could be a security thing, but most of all it's a performance thing, I guess.

I think it should be included by default, even if it drops performance, because when I am using defaults I expect fully working application, which is not the case now.

**Comment by kirillsalykin** [comment]
@claj maybe I was not clear enough, 
> I think it would be more confusing to split this up. The service creation logic is a bit large, admitted, but it would be much harder to understand if the (very small) functions and definitions it uses, where sprinkled out in namespaces without any special semantic meaning. I don't see the problem you see regarding the service creation.

I don't propose to have small functions, I just propose to split http.clj - move some functions to different namespaces.

**Comment by claj** [comment]
It is that split I think is a bad idea, because it makes the server creation logic harder to parse because a lot of helpers are "hidden" away in other namespaces.

**Comment by ohpauleez** [comment]
Thanks for the conversation everyone!

I appreciate the input, suggestions, and review.  At less than 500 lines (373-ish, including comments and whitespace), I don't think the namespace is too big.  Within Pedestal, shallower namespaces are typically used for user-focused APIs or a place to combine many utilities of "deeper" namespaces.  This is certainly true within `http.clj` -- it provides the minimum set of functions/functionality to construct and run HTTP services using Pedestal.

There are a few reasons why `body-params` isn't a default interceptor.

 * When possible, Pedestal makes as few assumptions as possible about the service you're writing.  `body-params` is a rather large assumption (which can only be implied when using other interceptors, like CSRF) -- it dictates how the Servlet's InputStream should be handled (which is consume-once).
 * You may only want `body-params` for a subset of your service, in which case body-params is best assigned at the route descriptor level, not at the default chain level.
 * When possible, Pedestal doesn't perform unnecessary processing -- only pay for what you need.  Adding `body-params` as a default interceptor violates this
 * Body params allows for strong control over the parsing behaviors.  It would be difficult to capture/express that in the service map (which is often expected to contain only edn).

I'm going to close this issue for now, but I'm more than happy to continue the conversation on the [Pedestal mailing list](https://groups.google.com/forum/#!forum/pedestal-users).
