### ISSUE TITLE
Allow enqueueing of interceptors other than at end of interceptor chain

### ISSUE THREAD

**Issue by crimeminister** [pedestal/pedestal#512]
I recently encountered a situation in which I had to enqueue a sequence of interceptors and ensure that they executed immediately after the current interceptor. As the `io.pedestal.interceptor.chain/enqueue` function only supports adding interceptors to the end of the chain (which makes sense given that for the underlying `PersistentQueue` data structure that's what's supported efficiently) I added a `prequeue` function that [did what I needed](https://github.com/crimeminister/pedestal/commit/88e06ff4a36de9a481584211bee42f1e2fb5410e) though perhaps not as performantly as one might want. I am curious if there is any appetite for the chain API to support the addition of interceptors both at the front and back of the chain?

If the interceptor chain is used by itself for running data processing pipelines it might also be nice to extend the API to support more flexible insertion/removal options, e.g. before or after a given interceptor or between every two interceptors (to store timestamps for performance evaluation, say). I have pondered changing the underlying data structure storing the interceptor chain on the context from `PersistentQueue` to a [finger tree](https://github.com/clojure/data.finger-tree) as it supports constant time addition at both ends; does that make any sense given the discussion happening in #411?

**Comment by claj** [comment]
I think your thoughts make a lot of sense. I'm not in the pedestal team, but use pedestal quite a lot.

The `io.pedestal.interceptor.chain/enqueue` is currently only a helper function. The real "interface" is that the `:io.pedestal.interceptor.chain/queue` in the context should be queue and `:io.pedestal.interceptor.chain/stack` should be a stack.

There is nothing that prevents you from manipulating the interceptor queue in any way you want, so nothing prevents you from adding helpers for any transform of the interceptor queue. As you mention, this could degrade performance to some extent.

I do think, however, that one reasonable way to gain higher performance in the interceptor chain in the future is to make the context treat `enqueue`s and `terminate`s behave like instructions more like any other stack abstraction (possibly using the JVM:s somewhat opaque but highly efficient own callstack). Currently a custom data structure that only lazily presented the queue and stack could work - I think the performance is limited by the need to realize the interceptor queue and stack where the most common access is to pick the first/last item of the data structures and put them in the other one.

The persistence has other nice advantages, though, especially when using asynchronously.

That said you could still put validators in `terminate-when` (especially during development).

I don't know how performant finger trees are - if you could try it out it would be great! The interceptor logic is not that much code so I think you can try it out yourself! A good way to do performance benchmarks on tight loops like this is to use [Criterium](https://github.com/hugoduncan/criterium).

I did some experiments with ordinary PersistentVectors used much like arrays, but found that the indexing ("stack pointer") was a bit to brittle. A more suitable datastructure than PersistentVectors would probably rrb-trees, which allows unused parts of the subvectors to be GC:ed. Maybe finger trees are even better.

I think the most appropriate data structure would be to have a persistent combined queue/stack with pointer. Operations on the whole call-stack would be allowed, but the position of the stack pointer would be kept in place somehow.

In the future, I hope we could specify the program logic much like core.logic and other prolog derivates do - I imagine some kind of branching behaviors could be used for exception handling, retries and, to some extent, dispatching based on the incoming logic, so this is an interesting journey!

**Comment by crimeminister** [comment]
Thanks for adding your thoughts @claj. I have no trouble futzing with the interceptor chain `queue` or `stack` personally, but given that `chain/enqueue` already exists I assumed that they were implementation details not to be relied upon and that I would have breakage to fix at some point for doing so. I think it would be friendlier for most folks to have a broader API for manipulating the interceptor chain that hides those details away and makes potential refactoring easier.

I plan to have a go at using finger trees, as much to get more familiar with the guts of Pedestal as for any performance needs (though I will throw Criterium at the result to see just how badly I mangle things). It sounds from your experiment as though some performance headroom remains; I am less in need of raw speed for my use cases (though I will take it if it is there thank-you-very-much), but I am always looking for better developer experience, more reward per unit effort, and customizability. I would rather have Pedestal support for plugging into or replacing the interceptor chain with something highly tuned for my needs rather than a good, all-around implementation that makes that difficult. A little example: in past work I have had to ensure at-most-once execution semantics for every interceptor in a chain. It was easy to layer on top of Pedestal, but if the chain queue was an ordered set it would be "for free", and in that case correctness was much more important that throughput so I happily gave up throughput to get it. Defining a protocol for the chain and allowing Pedestal to be initialized with a custom implementation using that protocol would, I think, allow for easier experimentation of the sort you describe.

It is an interesting journey indeed! Reading what you've written, I suspect there are lots of interesting usages of Pedestal in the wild and that "cookbook" and "best practices" sections of the docs would make for interesting reading.

**Comment by mtnygard** [comment]
@crimeminister I guess you can consider this an "official" response. I'm one of the Pedestal committers.

We definitely consider the keys on the context map to be part of the documented contract and API.

With any data structure there's this tension between providing an encapsulating API versus allowing ordinary Clojure functions to work as expected. (It's the "10 functions on 10 data structures versus 100 functions on 1 data structure" argument.)

We've taken an approach that we think is pragmatic. Some keys are documented. You can count on them continuing to work with all the functions that currently work with them. That is, if we need to replace the concrete data type, we'll do it with something that satisfies the same protocols.

We can't guarantee that the performance characteristics will remain the same. We sometimes make changes to improve performance for the majority of cases, but it might be bad for performance if you've done something particularly creative or unusual with the data structure.

Finally, regarding the cookbook and samples, I'm also the maintainer of pedestal/pedestal-docs, and I'm always interested in people's requests and contributions. The issues list on that repo is more of a wish list, so feel free to add notes or requests for things that will make your life easier. Or things that would have made your life easier when getting started, for that matter.

If you have some partial content or code snippets to show, feel free to drop them in as issues as well. I'm happy to wrap it up in text and push it to the [docs site](https://pedestal.io).

**Comment by ohpauleez** [comment]
I think @claj and @mtnygard both gave the response I was going to write.  I'll add that writing your own chain provider to seed the initial context is a great way to tweak/tune Pedestal.  We've done that many times in the past to write high-performance applications with Pedestal.

I'm going to leave this open for a bit longer to double check that if the interceptor chain uses data structures already in the context, if they're present.

**Comment by crimeminister** [comment]
Thanks everyone for the feedback. I realize now that my initial approach to this problem wasn't particularly idiomatic Pedestal, and that I should focus on creating custom chain providers to get the interface I'd like for a given application as suggested by @claj and @ohpauleez.  I'll look for and/or open an issue in the `pedestal/pedestal-docs` suggesting a guide describing how to do so; thanks for the suggestion @mtnygard.

**Comment by ohpauleez** [comment]
I looks like as long as `pop`/`peek` work correctly on your queue data structure, you can use anything you like for the queue.  If the `::queue` is present in the context, it uses it (there's just an `fnil` for when no queue is found and it needs to create an empty one to `enqueue`).
