### ISSUE TITLE
Secure headers not applied to static files

### ISSUE THREAD

**Issue by stuartsierra** [pedestal/pedestal#516]
# Description

Static files served from the classpath or the filesystem are served without security-related headers such as `Content-Security-Policy`.

## Steps to reproduce

In a shell, run:

    lein new pedestal-service foo

    cd foo

    mkdir -p resources/public

    cat <<EOF > resources/public/page.html
    <!doctype html>
    <html>
        <head>
            <title>Sample page</title>
        </head>
        <body>
            <p>Sample page</p>
            <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        </body>
    </html>
    EOF

    lein run-dev

In another shell, run:
    
    curl -i 'http://localhost:8080/page.html'

Observe the headers in the response:

    HTTP/1.1 200 OK
    Date: Sat, 10 Jun 2017 18:30:09 GMT
    Last-Modified: Sat, 10 Jun 2017 18:30:06 GMT
    Content-Type: text/html
    Access-Control-Allow-Credentials: true
    Access-Control-Expose-Headers: Content-Length, Last-Modified, Content-Type
    Content-Length: 215

Compare by running:

    curl -i 'http://localhost:8080/'

And observe the headers in the response:

    HTTP/1.1 200 OK
    Date: Sat, 10 Jun 2017 18:30:15 GMT
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    Strict-Transport-Security: max-age=31536000; includeSubdomains
    X-Permitted-Cross-Domain-Policies: none
    Access-Control-Allow-Credentials: true
    Access-Control-Expose-Headers: Strict-Transport-Security, X-Frame-Options, X-Content-Type-Options, X-Xss-Protection, X-Download-Options, X-Permitted-Cross-Domain-Policies, Content-Security-Policy, Content-Type
    X-Content-Type-Options: nosniff
    Content-Security-Policy: object-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:;
    Content-Type: text/html;charset=utf-8
    Transfer-Encoding: chunked

# Environment

## Operating System (including version).

OS X El Capitan 10.11.6

## Your current Leiningen version (`lein --version`)

Leiningen 2.7.1 on Java 1.8.0_92 Java HotSpot(TM) 64-Bit Server VM

## Pedestal version

0.5.2

**Comment by stuartsierra** [comment]
Further:

Edit `src/foo/service.clj`, replace the content of `home-page` with the same HTML used above. Restart the server. Visit http://localhost:8080/ in a browser, open the debugger for network connections, and observe that jquery is blocked by CSP. By comparison, visit http://localhost:8080/ and jquery is not blocked.

This may be an indication that the default CSP headers are too strict for most applications but that this was not noticed before because those headers were not applied to static HTML files.

**Comment by ohpauleez** [comment]
Thanks for finding this one @stuartsierra.  I'll look into it (also curious if other headers correctly get applied to static files).  There is an issue that helps people loosen the CSP issue: #499 

I rather the controls default to a more secure (and recommended) setting - [1](https://content-security-policy.com/); [2](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP); [3](https://www.owasp.org/index.php/Content_Security_Policy)

**Comment by stuartsierra** [comment]
I think it's simply a matter of ordering in the default interceptors: [resource-path and file-path](https://github.com/pedestal/pedestal/blob/1328f4ac3588f55364475f6c98bda6c5f3775385/service/src/io/pedestal/http.clj#L256) are placed before secure-headers.

**Comment by ohpauleez** [comment]
In case anyone else is following this, I'll be working on this next week.  Should be on master in the near future.

**Comment by ohpauleez** [comment]
This is fixed on master.  Thanks @stuartsierra!

**Comment by stuartsierra** [comment]
great, thanks!
