### ISSUE TITLE
Immutant WebSocket session ID

### ISSUE THREAD

**Issue by jimrthy** [pedestal/pedestal#524]
# Description

Immutant web sockets are all hard-coded to have the same session ID

## Expected Behavior

Each new web socket really should get a fresh ws-session ID. Though we really need a way to associate it with something like an existing session cookie. (Just switching to a random session ID doesn't make life much/any better, since I don't have any idea who's on the other end).

I've done a little digging into what's involved here and how it might work, but I've only really been looking at pedestal for a few days now. So it seemed better to ask if someone with more experience had any "Oh, yeah, that would be easy, but no one's ever wanted to use this before" suggestions.

## Actual Behavior

io.pedestal.http.immutant.websockets/start-ws-connection hard codes on-connect-fn to send "immutant-ws-session" as the ws-session ID.

## Steps to reproduce

Translate the jetty web socket example to use the Immutant backend. (I should be able to post this in the next few hours. It's easy enough, though it did take a little digging to figure out, and I don't have a version handy that I'm allowed to publish).

Connect a web socket. Note the ws-session ID.

Connect a second web socket. Get the same ws-session ID.

# Environment

## Pedestal version

0.5.2

**Comment by jimrthy** [comment]
https://github.com/pedestal/pedestal/pull/525 should make it easier to double-check this.

**Comment by ohpauleez** [comment]
Thanks for pulling all of this together @jimrthy -- I'll start looking into it next week (I have a handful of other changes I need to push to master as well)

**Comment by jimrthy** [comment]
No, thank *you*! This is the sort of thing that I'd have just taken for granted before I got access to a library like Pedestal.

This seems more complex than I realized originally. (Who's shocked?)

Each websocket connection definitely seems to need some sort of reference to the caller so something different can figure out where to send a response. (My first inclination was that the original sec-websocket-key would be useful, and it may be, but now I have serious doubts about that).

The current implementation seems to be all about a basic lock-step request/response kind of life-cycle. Which is fine, but I need something that's more of a Reactive/Data-Flow sort of thing, where a client connects, then submits requests, and they flow back asynchronously (and lots of time that flow is its own multicast back to N clients who subscribed to a connection in the first place).

Yes, there are a *lot* of other pieces to this. But I think they start by giving the websocket endpoint access to the headers. Or maybe changing the docs to make it clearer that context-configurator has some low-level magic it can apply (I think I could bypass everything else and just set things up there the way I want, but I'm not sure how).

**Comment by jimrthy** [comment]
I got official permission to demonstrate what I mean. So hopefully I'll have time to extract that in the next day or so.

**Comment by ohpauleez** [comment]
Excellent!  Thanks for following up here!

**Comment by jimrthy** [comment]
https://github.com/jimrthy/ideal-rotary-phone/blob/master/src/ideal_rotary_phone/hello.clj covers the basic issues that I'm running into.

This is more a series of questions than anything useful.

I came up with *an* answer, but I don't trust it at all.

**Comment by hlship** [comment]
This issue has obviously been languishing for quite some time; is it still relevant?

**Comment by hlship** [comment]
I'm afraid we've moved away from having support for immutant, so I'm regretfully closing this issue.
