### ISSUE TITLE
Handlers should be able to return a channel.

### ISSUE THREAD

**Issue by patrickthebold** [pedestal/pedestal#528]
In general, an interceptor can return a channel that eventually produces a context map. Handlers should be able to return a channel that returns a response map.

**Comment by ohpauleez** [comment]
This is already possible and will trigger an "async" response, but is strongly discouraged because it goes down a weird (rarely used) code path -- this code path only exists for legacy purposes.  If you have a handler fn that returns a channel, it's better that you just change it to a definition of an interceptor directly.

**Comment by patrickthebold** [comment]
Interesting. Just to be clear, when you say this is already possible, you mean something different than what's described at the bottom here: http://pedestal.io/reference/streaming?

I realize there is a difference between an interceptor that returns a channel that produces a context map vs a context map that has a response map that has a body that is a channel, but those are the only two uses of a channel I've seen documented.

**Comment by ohpauleez** [comment]
Ah, I see, you want to produce the entire response map, not just the body -- sorry for my misunderstanding.  Yes, I was referring to the fact that response bodies coming out of handlers can already be core.async channels (that's the legacy code path).

To achieve what you're looking for, you might just write a function that given a function (the handler function), returns an interceptor with the async handling you want.  You can than use that function throughout your routes like a function call (it will have to be quoted/syntax-quoted) ````(async-handler my-handler-fn)```

**Comment by patrickthebold** [comment]
Thanks for the response. (As an FYI the documentation doesn't really make it seem that the streaming responses with channels is a legacy thing.) 

Right now I've just redefined how clojure.lang.Fn extends IntoIterceptor to check if the response is a channel. Which is kind of hacky, so I'll see if your suggestion works better. 

As someone trying to learn the framework, I will say I was surprised that it didn't "just work" when my handler returned a channel. It's  a bit subtle how the handler returns a response, which is only part of the context map and so the whole context map is not a channel when the handler returns a channel. Obviously you can decide if it's worth it, but it feels more consistent to allow for a channel to be returned. (Also, there's only one reasonable thing to do if a handler returns a channel.)
