### ISSUE TITLE
Version updates on dependencies needed

### ISSUE THREAD

**Issue by mtnygard** [pedestal/pedestal#549]
# Description

## Expected Behavior

Mixing Pedestal in with other contemporary Clojure projects should be easy.

## Actual Behavior

Version mismatches in dependencies make it hard to get a consistent set. Particularly aggravating on projects which use Leiningen's `:pedantic? :abort`

**Comment by ohpauleez** [comment]
All the deps have been cleaned up on master.  If this doesn't fix the issue Mike, reopen and we'll talk about.  Thanks!
