### ISSUE TITLE
Jetty 9.4.7.v20170914 -> 9.4.8.v20171121 doesn't start correctly

### ISSUE THREAD

**Issue by claj** [pedestal/pedestal#552]
# Description

We have a non trivial pedestal application using Component as depency injection.

When upgrading from 9.4.7 to 9.4.8 some of my tests breaks. There's an NPE when starting the server with Jetty 9.4.8 when starting the component. The problem can be almost anywhere, will try to spot it more clearly.

The problem is not there with version `9.4.7.v20170914` but occurs for versions `9.4.8.v20171121` and `9.4.9.v20180320`

## Steps to reproduce

# Environment

## Operating System (including version).

MacOS High Sierra 10.13.4

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)

Leiningen 2.8.1 on Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM

## Pedestal version

[io.pedestal/pedestal.service "0.5.3"]
[io.pedestal/pedestal.jetty "0.5.3"]
[org.eclipse.jetty.alpn/alpn-api "1.1.3.v20160715"]

`jetty-version` as above

[org.eclipse.jetty.http2/http2-server ~jetty-version]
[org.eclipse.jetty.websocket/websocket-api ~jetty-version]
[org.eclipse.jetty.websocket/websocket-client ~jetty-version]
[org.eclipse.jetty.websocket/websocket-server ~jetty-version]
[org.eclipse.jetty.websocket/websocket-servlet ~jetty-version]
[org.mortbay.jetty.alpn/jetty-alpn-agent "2.0.7"]
[org.eclipse.jetty/jetty-alpn-server ~jetty-version]
[org.eclipse.jetty/jetty-client ~jetty-version]
[org.eclipse.jetty/jetty-security ~jetty-version]
[org.eclipse.jetty/jetty-server ~jetty-version]
[org.eclipse.jetty/jetty-servlet ~jetty-version]
[org.eclipse.jetty/jetty-servlets ~jetty-version]

**Comment by ohpauleez** [comment]
I looked into this a few days ago -- it has to do with an update on how HTTP/2 is handled now and a method was removed from the API.  The fix is pretty easy.  As always, thanks for reporting @claj !

**Comment by ohpauleez** [comment]
Just a quick note -- this will also fix #555

**Comment by claj** [comment]
wov, thanks for fixing the least specific bug report ever!

**Comment by ohpauleez** [comment]
Jetty deps have been bumped, so this fix is on master now.  Thanks!
