### ISSUE TITLE
Illegal reflective access warning on loading jetty classes

### ISSUE THREAD

**Issue by rafaeldff** [pedestal/pedestal#555]
# Description
Opening a Java 9 JVM in a project with `[io.pedestal/pedestal.jetty "0.5.3"]` will show _Illegal reflective access_ warnings. This apparently was fixed in jetty upstream (https://github.com/eclipse/jetty.project/issues/1262).

## Expected Behavior
Expected not to see any warnings

## Actual Behavior
See warning such as
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.jetty.util.BufferUtil (file:/home/rafael/.m2/repository/org/eclipse/jetty/jetty-util/9.4.0.v20161208/jetty-util-9.4.0.v20161208.jar) to field java.nio.MappedByteBuffer.fd
WARNING: Please consider reporting this to the maintainers of org.eclipse.jetty.util.BufferUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

## Steps to reproduce
Open a REPL with Java 9 on a project depending on `[io.pedestal/pedestal.jetty "0.5.3"]`, then require pedestal.jetty - `(require '[io.pedestal.http.jetty])`. You will see the warnings as above.

# Environment

## Operating System (including version).
Linux rffnix 4.15.17 #1-NixOS SMP Thu Apr 12 10:31:21 UTC 2018 x86_64 GNU/Linux

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Leinigen 2.8.1
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

## Pedestal version
```
[io.pedestal/pedestal.service "0.5.3" :exclusions [org.slf4j/slf4j-nop]]
[io.pedestal/pedestal.service-tools "0.5.3"] 
[io.pedestal/pedestal.jetty "0.5.3"]
```

**Comment by ohpauleez** [comment]
As you noted, this is fixed in upstream Jetty (the project made a big effort to address all compatibility issues).  Given Java 9's EOL (March 2018), most JDK compatibility issues will be focused at Java 10, in preparation for Java 11 (which has LTS).

It's unclear how the Java and Clojure communities will react to the "Support Cliffs" in the newly established release cycle.

**Comment by ohpauleez** [comment]
Jetty has been updated to the version that includes the JDK9+ fixes, so this should now be fixed on master.  Thanks for reporting!

**Comment by eraserhd** [comment]
I'd love to have a release for this fix.

**Comment by ohpauleez** [comment]
0.5.4 should be released pretty soon.  There are still a few smaller items we need to complete and we've been testing the new code on production setups to ensure everything is working as expected.
