### ISSUE TITLE
SSE dispatch loop abort without proper clean up

### ISSUE THREAD

**Issue by kotokz** [pedestal/pedestal#560]
# Description
The current SSE dispatch loop not able to handle exception which thrown by send-event function. 
The loop simply abort without closing the event channel and calling on-client-disconnect call back.

This issue heavy impact application which depends on the on-client-disconnect function.
we fixed it by putting loop under a try-finally block to handle the resource cleanup

## Expected Behavior
the event-channel, response-channel should be closed
on-client-disconnect

## Actual Behavior
only response channel can be closed.

## Steps to reproduce
trigger a exception which only can be caught by "send-event" function. 
for example, trigger a channel buffer full scenario: 
[async-dispatch-3] io.pedestal.http.sse -- {:msg "exception sending event", :throwable #error {
 :cause "Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.\n(< (.size puts) impl/MAX-QUEUE-SIZE)"
 :via
 [{:type java.lang.AssertionError
   :message "Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.\n(< (.size puts) impl/MAX-QUEUE-SIZE)"
   :at [clojure.core.async.impl.channels.ManyToManyChannel put_BANG_ "channels.clj" 152]}]
 :trace
 [[clojure.core.async.impl.channels.ManyToManyChannel put_BANG_ "channels.clj" 152]
  [clojure.core.async$put_BANG_ invokeStatic "async.clj" 165]
  [clojure.core.async$put_BANG_ invoke "async.clj" 158]
  [io.pedestal.http.sse$send_event invokeStatic "sse.clj" 93]
  [io.pedestal.http.sse$send_event invoke "sse.clj" 81]
  [io.pedestal.http.sse$start_dispatch_loop$fn__8544$state_machine__5275__auto____8557$fn__8560 invoke "sse.clj" 133]
  [io.pedestal.http.sse$start_dispatch_loop$fn__8544$state_machine__5275__auto____8557 invoke "sse.clj" 133]
  [clojure.core.async.impl.ioc_macros$run_state_machine invokeStatic "ioc_macros.clj" 973]
  [clojure.core.async.impl.ioc_macros$run_state_machine invoke "ioc_macros.clj" 972]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invokeStatic "ioc_macros.clj" 977]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invoke "ioc_macros.clj" 975]
  [clojure.core.async$ioc_alts_BANG_$fn__5490 invoke "async.clj" 384]
  [clojure.core.async$do_alts$fn__5430$fn__5433 invoke "async.clj" 253]
  [clojure.core.async.impl.channels.ManyToManyChannel$fn__904$fn__905 invoke "channels.clj" 95]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]

# Environment
latest pedestal version.

## Operating System (including version).
Linux gbl13945 2.6.32-642.6.2.el6.x86_64 #1 SMP Mon Oct 24 10:22:33 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Leiningen 2.7.1 on Java 1.8.0_141 Java HotSpot(TM) 64-Bit Server VM

## Pedestal version
0.5.3

**Comment by ohpauleez** [comment]
This fix is now on master.  Thanks for reporting!
