### ISSUE TITLE
Support of regex patterns for :host

### ISSUE THREAD

**Issue by juskrey** [pedestal/pedestal#561]
I was in need to have routes with hosts as wildcards, so made some quick tweaks in terse parser and router for my project which seem to work well.
Is it reasonable to include such support in pedestal? If yes, I'd like to contribute.

**Comment by hlship** [comment]
It's good that you were able to generate your own solution, but at this time we do not feel that this is a general case that needs addressing in the framework. Feel free to bring this up in the Clojurian's pedestal slack channel and we'll see if it is something of value to the larger community.
