### ISSUE TITLE
Pedestal's metrics support should be migrated over to Micrometer

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#568]
[Micrometer](http://micrometer.io/) has become the standard facade for metrics on most JVM-based systems.  It unified the two major metrics APIs/facades, in the same way OpenTracing unified many tracing implementations/APIs/facades.

Since the concepts are identical to DropWizard Metrics, this is only a deps/class swap (no change to the protocols or logic).
Since the backend support is identical to DropWizard Metrics, there is a migration path to those updating to 0.5.4.

The metrics samples should also be updated.

**Comment by ohpauleez** [comment]
Quick status report:  There are slight differences between Micrometer and DropWizard Metrics.  While Micrometer's dimensionality is nice, I think working with the API and the metrics themselves involve a bit more ceremony.

There's also a chance I'll remove the JMX reporter as a default, and instead just opt-for a basic in-memory registry that can be inspected from the REPL.  Most production-oriented metrics registries are push-oriented and dropping the JMX default should reduce memory pressure in production.  Users can still opt to pull in the JMX Registry/Reporter as a dep if desired (and samples will be updated to illustrate that)

**Comment by jwhitlark** [comment]
Micrometer support would mean a great deal to me.  Not being able to have drop-in prometheus metrics are kinda a show stopper for my use case, and I say that as someone who did a great deal of work on metrics-clojure.  I wouldn't mind a bit removing jmx, I always felt it should be optional.

**Comment by ohpauleez** [comment]
@jwhitlark Pedestal's current metrics are developed against the DropWizard Metrics API.  There are a few [reporters for Prometheus](https://github.com/dhatim/dropwizard-prometheus).  Depending on your setup, you might also check the list of [reporters listed on the DropWizard site](https://metrics.dropwizard.io/4.0.0/manual/third-party.html).

Removing JMX is just about removing dependencies, but JMX is nice for two reasons:
 * It works wonderfully for local development
 * There are lots of solutions to plumb JMX into other metrics/reporting infrastructure

Hope this helps you in the short-term!

**Comment by yenda** [comment]
Is this still planned?

**Comment by ohpauleez** [comment]
Micrometer is still probably the best option (it functions as the "SLF4J" interface for many different provider backends).  Micrometer recently landed support for the OpenTelemetry protocol and there are contrib packages to support metric registries that connect directly through OpenTelemetry.

Pedestal2's Telemetry package should be used for the basis of any change regarding Metrics/tracing.  The protocol definitions enable developers to connect the metrics calls to any backend they want/need, and the default implementation for micrometer provides and easy, instant integration that works out of the box.

**Comment by hlship** [comment]
This is starting to feel like something that will slip to 0.5.12 then.  I have not yet looked at the Pedestal2 code base.

**Comment by hlship** [comment]
I'm sure Pedestal2 is nice, but we're focused on maintaining backwards compatibility and that adds a lot of challenge here, and possibly some duplication if we go on a path towards deprecating and eventually removing the current support tied to DropWizard This is a focus now in Pedestal 0.7.

**Comment by hlship** [comment]
Ended up embracing Open Telemetry (see #804).
