### ISSUE TITLE
Passing host, port to expand-routes breaks io.pedestal.test/response-for

### ISSUE THREAD

**Issue by martinklepsch** [pedestal/pedestal#570]
When passing the `{:host "localhost" :port 8888}` map to `expand-routes` `io.pedestal.test/response-for` will return a 404 for all incoming requests, regardless of their URL.

I tested this for the following URLs: 

- `/`
- `localhost:8888/`
- `http://localhost:8888/`

The reason for this is partly the `parse-url` function as well as how the request is constructed. A patch that fixes both aspects an be found here: https://gist.github.com/martinklepsch/9314308cfed88dcdd5a5429265df487d

**Comment by ohpauleez** [comment]
This change is on master and is part of the 0.5.4 release (on clojars now).  Thanks for reporting!
