### ISSUE TITLE
url-for silently accepts missing and invalid path-params

### ISSUE THREAD

**Issue by martinklepsch** [pedestal/pedestal#572]
`url-for` is very relaxed when it comes to providing path-params. It happily returns routes with path-params that have not been provided or with ones that don't match the provided constraints.

```clojure
(require '[io.pedestal.http.route :as route])

(def my-routes
  #{["/thing/:type/:id" :get {:name :f :enter identity}
                        :route-name :thing
                        :constraints {:id #"[0-9]+"}]})


(def url-for
  (route/url-for-routes (route/expand-routes my-routes)))
```

```clojure
(url-for :thing :path-params {})
;;=> "/thing/:type/:id"
```

```clojure
(url-for :thing :path-params {:id "hello"})
;;=> "/thing/:type/hello"
```

@ddeaguiar mentioned on Slack:

> Outside of such information [constraints] I think the current implementation makes a reasonable compromise.

By which he is referring to using the path params key as parameter itself:

https://github.com/pedestal/pedestal/blob/6b2faef808c66573e1fde564017ab1dbde1018c8/route/src/io/pedestal/http/route.clj#L252 

I fail to see what this behavior enables that wouldn't be possible if `url-for` would throw on missing path-params. In fact it seems brittle to me to have no validation that all path params are provided and in the right format. `url-for` will generate routes that won't be matched by the same route.

One typo in the `path-params` map and my Pedestal app will generate invalid routes and I would only notice by users or monitoring telling me.

Bidi (and perhaps other routing libs) throw in this case. This doesn't mean Pedestal has to do the same of course but I'm having trouble understanding the upside to the current behavior.

**Comment by ddeaguiar** [comment]
As per [rfc3986](https://tools.ietf.org/html/rfc3986#section-3.3), `:` is a valid path-segment character. Devoid of additional information, I do think the Pedestal implementation makes a reasonable compromise. However, when path param constraints are included there is additional information which could be used to communicate to the user that the url which would be generated would be invalid.

**Comment by martinklepsch** [comment]
> As per rfc3986, `:` is a valid path-segment character.

`:` May be a valid path segment but to me that isn't really an argument for falling pack to the path-segment's name/key if no value has been provided?

**Comment by ohpauleez** [comment]
The current behavior allows you to generate URLs which can be programmatically consumed and treated as "a path with params" -- this is sometimes useful to communicate to intelligent front-ends, especially if the path-param portions have domain significance.

The current implementation also avoids the overhead of exceptions in the hot path if needed.

As an alternative, imagine something like the following:
 * A new argument to `url-for` called `:strict-path-params`
 * This new argument takes a boolean (all path-params must be present or it throws an exception)
 * The new argument can optionally be passed a function which takes and returns the `:path-params` map.  You're free to throw in this function or patch in defaults that should be used.

Would this alternative solve the core problem of generating invalid URLs for your application/your clients?  Do you see a better option or direction that a possible solution should take?

**Comment by martinklepsch** [comment]
> The current behavior allows you to generate URLs which can be programmatically consumed and treated as "a path with params" -- this is sometimes useful to communicate to intelligent front-ends, especially if the path-param portions have domain significance.

That's a neat thing to have, but wouldn't the data structure returned by `expand-routes` be much more useful for that kind of purpose? (Compared to a string as you suggest if I understood correctly.)
```clj
{:path "/d/:group-id",
 :method :get,
 :path-constraints {:group-id "([^/]+)"},
 :path-re #"/\Qd\E/([^/]+)",
 :path-parts ["d" :group-id],
 :interceptors [,,,],
 :route-name :group/index,
 :path-params [:group-id]}
```

My personal opinion is that that the current behavior picks the wrong default but I understand that changing this would be a breaking change so yeah, an option to enable "strict mode" would go a long way for my particular situation. 

I'm not sure I fully understand the use case for passing in a function, since I could patch in defaults before calling `url-for` which seems more explicit/clear to me. No strong feelings here though.

**Comment by ohpauleez** [comment]
The additional option approach is indeed to avoid a breaking change, so I appreciate your understanding.

I suggested the option of passing a function to see if it ignited ideas for additional use cases you might have or other suggestions you might make in approaching the solution space.

Thanks for the feedback!

**Comment by martinklepsch** [comment]
An alternative way could also be introducing an option to _disable_ strict mode. With strict mode being shipped as default in the next release a warning could be shown but the behavior could remain identical. In a later version this warning would be turned into an exception. 

I guess this option is only interesting if you feel similarly about the current default being a little bit too optimistic.

**Comment by ddeaguiar** [comment]
@martinklepsch sorry for the late response but my answer to your [comment](https://github.com/pedestal/pedestal/issues/572#issuecomment-395489160) is yes. I +1 the approach @ohpauleez has suggested.

**Comment by martinklepsch** [comment]
> my answer to your comment is yes

I still fail to see why those two invocations should be regarded as the same but I'm not sure further discussion will resolve that. I'm on Slack if you happen to want to talk me through this.

**Comment by ohpauleez** [comment]
This is fixed on master and is in the 0.5.4 release (on clojars now)

**Comment by martinklepsch** [comment]
Reopening this as `url-for` still accepts nil path-params, see this discussion on the relevant commit: https://github.com/pedestal/pedestal/commit/72f6e7da91cef142f2070f08883264c04aa3f6b8#r29440240

**Comment by martinklepsch** [comment]
Bump. 🙂

**Comment by ddeaguiar** [comment]
@martinklepsch sorry for the late response, I was traveling. I've created issue #602 to track this change.
