### ISSUE TITLE
Support Jetty context path

### ISSUE THREAD

**Issue by terjesb** [pedestal/pedestal#578]
# Description

I've been looking into migrating some Pedestal services from WildFly/Immutant to standalone Jetty. When run under WildFly, the deployment gets its context path from the container. When deploying the same route table to Jetty, it's now in the root context. This makes it inconvenient to target both containers during a transition. There may also be other use-cases for deploying the same app to Jetty under multiple/different context paths. Or even running multiple Jetty apps behind a single load balancer, and having them under different contexts/prefixes instead of all in the root context on different ports.

One option is to (programmatically) update the routes, i.e. have separate route tables for the different containers.
Another option would be to use the same route table, but enable Jetty to use a context similar to WildFly.

I've looked into the latter and have a patch for this with passing tests:
* add support for a :context-path in Jetty's :container-options
* change url-for-routes to support existing :context parameter (it had an if branch for this already, but I didn't get it to work and it doesn't appear to be tested)
* change servlet-interceptor to add :context-path to the request again, to support dynamic url-for via :request :context-path and the same if branch as above. (Ref also our previous discussion in issue #439.) Tried to do this with an 'external' interceptor, but then the default-interceptors and routing plumbing seem to adds the url-for function to the context _before_ the :context-path is available. Not sure how to prepend an interceptor to the chain. (default-interceptors both constructs the vector and updates service-map, perhaps these two operations could be separated later.)

I think the changes are only breaking for anyone using url-for and its :context parameter, but I believe this did not work as documented.

(Note that url-for probably doesn't work for WildFly/Immutant right now either, ref the previous discussion. This patch doesn't fix this, but possibly makes it easier to do. OTOH, if url-for isn't wanted/required for Jetty either, adding only :context-path seems trivial.)

Preparing a PR.

## Expected Behavior

Pedestal could support Jetty's context-path and make it more convenient to transition between WildFly and Jetty deployment, or support the same app under different contexts.

## Actual Behavior

Pedestal does not support Jetty's context-path.

## Steps to reproduce

# Environment

## Pedestal version

0.5.3

**Comment by ohpauleez** [comment]
Thanks for reporting the issue and pulling together a PR @terjesb!  I agree that these changes should be made and the PR looks good.  I'll be pulling together a few changes for 0.5.4 today -- if I touch `url-for`, I'll just pull your changes in, otherwise, I'll just merge your PR when I'm setting up my PR.

**Comment by ohpauleez** [comment]
Scratch that, I'm just going to merge your PR and I'll apply my changeset patches on top of that.  Again, thanks for being an outstanding community member, reporting a quality issue with a strong motivation and description of the problem, and pulling together a PR with minimal changes and tests.

**Comment by ohpauleez** [comment]
Landed on master.  I just need to make a few additional tweaks.

**Comment by terjesb** [comment]
Thanks for the quick response and kind words, @ohpauleez. One thing I note when re-reading this, and no biggie, but perhaps the container-options should be :context instead of :context-path, to match the parameter name to url-for? Your call, feel free to tweak this.
