### ISSUE TITLE
Slash Routing Behavior

### ISSUE THREAD

**Issue by deadghost** [pedestal/pedestal#590]
# Description
Two segment URL interfering with match of three segment URL.

## Expected Behavior
`:get-mailchimp-templates` route is returned. From the documentation on http://pedestal.io/guides/defining-routes:

> A single path parameter only matches one segment of a URL. One segment is just the part between '/' characters. 

 I expected the match to pass through `"/integrations/:integration"` to `"/integrations/mailchimp/templates"` and return the templates route.

## Actual Behavior
`nil` is returned. The two segment URL may be stopping the match from hitting the three segment URL. The two segment URL route however is not returned.

## Steps to reproduce
```
(def routes-failure
  (route/expand-routes
   #{["/integrations/:integration" :get [] :route-name :get-integration]
     ["/integrations/mailchimp/templates" :get []
      :route-name :get-mailchimp-templates]}))

(route/try-routing-for
 routes-failure :prefix-tree "/integrations/mailchimp/templates" :get)
;; => nil

(def routes-success
  (route/expand-routes
   #{["/integrations/mailchimp/templates" :get []
      :route-name :get-mailchimp-templates]}))

(-> (route/try-routing-for
     routes-success :prefix-tree "/integrations/mailchimp/templates" :get)
    (:route-name))
;; => :get-mailchimp-templates
```

# Environment
CIDER 0.16.0 (Riga), nREPL 0.2.13
Clojure 1.9.0, Java 1.8.0_181

## Operating System (including version).
Ubuntu 18.04.1 LTS

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Leiningen 2.8.1 on Java 1.8.0_181 OpenJDK 64-Bit Server VM

## Pedestal version
 0.5.4

**Comment by ohpauleez** [comment]
Sorry to hear you got caught up on this!

Segment wildcards like your `:integration` segment, only match/bind one segment.  You would nee to define a route like `"/integrations/:integration/templates"` or use a splat route like `"/integrations/*integration"`.  Using a splat route will bind the remaining pieces of the URL to the splat segment name - for example, given the splat route `"/integrations/*integration" and the URL request for /integrations/mailchimp/templates, the integration param would have a value of `"mailchimp/templates"`.

If you still need more help, feel free to reach out on the [mailing list](https://groups.google.com/forum/#!forum/pedestal-users)

**Comment by ohpauleez** [comment]
My apologies!  I was responding before I was completely awake.

Your experience is expected behavior on the prefix-tree router.  You'd need to use the linear router if you wanted the matching to continue past the wildcard segment to a concrete match.

From the [release notes](https://github.com/pedestal/pedestal/releases) and pull request where the Prefix-tree router was landed:
```
The prefix-tree router also changes some of the routing behavior. In the linear-search, you could have routes like /one/:wild and /one/two, the latter being a hard match and the former picking up any wildcard URL matches (not /one/two). In the prefix-tree, this isn't allowed, and one/:wild will always be matched. This change also encourages "best practices" and removes the possibility of subtle bugs introduced by human error.
```
 There are more details in the [Router docs](http://pedestal.io/reference/routing-quick-reference)
