### ISSUE TITLE
Missing keys on context's :request (compared to tutorial)

### ISSUE THREAD

**Issue by xvrdm** [pedestal/pedestal#601]
# Description

I am following the [official tutorial on content type management](http://pedestal.io/guides/hello-world-content-types) and cannot find the expected keys on the `context`'s `:request`. 

Thanks for the tutorial btw, it is **great** to have such resource!

## Expected Behavior

In the tutorial, it looks like there should be (was?) an `:accept` key which itself had a `:field` key.

```
...
(get-in context [:request :accept :field] "text/plain")
...
```

## Actual Behavior

After getting `text/plain` for every call, I looked at the keys on the `:request` and I only get these:

```
(:protocol :async-supported? :remote-addr :servlet-response :servlet :headers :server-port :servlet-request :path-info :url-for :uri :server-name :query-string :path-params :body :scheme :request-method :context-path)
```

To get the expected behaviour, it looks like I have to search for the `"accept"` value in the `:headers`.

```
 (get-in context [:request :headers "accept"] "text/plain")
```

## Pedestal version

`0.5.4`

If that's indeed a outdated part of the tutorial and we can contribute somewhere, happy to submit a PR...

**Comment by ddeaguiar** [comment]
@xvrdm, sorry for the late response. I'm glad you are finding the tutorials useful! I took a look at the tutorial and it's working as expected. Pedestal's content negotiation implementation is [responsible](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/content_negotiation.clj#L186) for assoc'ing `:accept` to the request map. The accept header is used by this implementation to determine the _most acceptable_ response format.
