### ISSUE TITLE
Default host of localhost prevents application from receiving incoming requests inside a Docker container

### ISSUE THREAD

**Issue by claj** [pedestal/pedestal#604]
# Description

Pedestal 0.5.4 introduced a default host binding to "localhost", for good reasons (uniformity and default security). This change caused problems for our setup where we run pedestal in Docker containers. The containers just _did not respond to anything_ anymore, localhost in Docker containers are not exposed to the container routing.

I began with suspecting Jetty (or changes introduced to Jetty) to behave badly, but it was said to connect to `0.0.0.0` (all interfaces) when given `null` or `0.0.0.0` by default. The `pedestal/jetty` implementation mentions :host, but it is `pedestal/service` that packs it up from `::server/host`.

## Expected Behavior

That jetty-based pedestal in docker containers connects to "0.0.0.0" instead of "localhost", _or that it is apparent that this has to be configured explicitly_ when running pedestal in docker.

## Actual Behavior

Jetty based pedestal containers has recently introduced a default `::server/host` which is `"localhost"`. Jetty's standard host is `0.0.0.0`.

When running pedestal in a Docker container, binding to "localhost" makes the container unresponsive.

## Steps to reproduce

Do not give a specific ::server/host but try to run an app in a Docker container with jetty/pedestal 0.5.4.

docker run -p9443:9443 the-image

Look for the log print
```
[nREPL-worker-3] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@6b0ed7a9{/,null,AVAILABLE}
[nREPL-worker-3] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@6b25960a{SSL,[ssl, alpn, h2, http/1.1]}{localhost:9443}
[nREPL-worker-3] INFO  org.eclipse.jetty.server.Server - Started @1496218ms
```
observe `localhost:9443`.

You will not be able to reach that service from outside the container.

Re-configure your app to have `::server/host "0.0.0.0"`

```
[nREPL-worker-4] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@18267894{/,null,AVAILABLE}
[nREPL-worker-4] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@60c84da0{SSL,[ssl, alpn, h2, http/1.1]}{0.0.0.0:9443}
[nREPL-worker-4] INFO  org.eclipse.jetty.server.Server - Started @1552405ms
```

Observe that server connector now connects to `0.0.0.0:9443`.

You will be able to visit your containers service from outside of the container.

# Environment

## Operating System (including version).

macos 10.14.1
Docker Engine: 18.09.0

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Leiningen 2.8.1 on Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM
## Pedestal version
Pedestal 0.5.4
Jetty* "9.4.14.v20181114"
org.eclipse.jetty/jetty-alpn-openjdk8-server (not conscrypt)

**Comment by davezen1** [comment]
Try setting the http host in service.clj :               

::http/host "0.0.0.0"


I was able to access the the service from the host at 0.0.0.0

**Comment by sauvala** [comment]
I also stumbled to this. Fortunately @davezen1's trick worked. This was very confusing to try to figure out where the problem might be - is it my code, Docker configs...

**Comment by ddeaguiar** [comment]
I think the docs need to be clearer about this. Perhaps a comment in the service template as well as info in pedestal.io.

**Comment by claj** [comment]
A comment in some template file and mentioning this in the documentation is probably enough to make this less of a problem.

**Comment by boolpath** [comment]
I had the same issue while deploying to Heroku. Thanks @davezen1, that fixed it.
```
::http/host "0.0.0.0"
::http/port (Integer. (or (env :port) 8080))
```

**Comment by henrique1977** [comment]
> ::http/host "0.0.0.0"

THANK YOU!!  @davezen1 you're the man!!

**Comment by spellman** [comment]
Where `::server/host` (OP) and `::http/host` (above) each mean `:io.pedestal.http/host` 🙂

**Comment by hlship** [comment]
I don't think we can (or should) detect that Pedestal is operating inside a container; however, adding documentation to discuss this scenario is absolutely something we will be doing.

**Comment by hlship** [comment]
Added this documentation: https://github.com/pedestal/pedestal-docs/commit/df3e6bc195a29ec68917c5f810b983e0eb9e4a79
