### ISSUE TITLE
Routing/request data construction should be tolerant of java.util.Map

### ISSUE THREAD

**Issue by ohpauleez** [pedestal/pedestal#606]
When using Pedestal on various platforms (like AWS APIGW/Lambda), request construction and routing details work as expected except for a few key areas that use `reduce-kv`.

[reduce-kv does not currently work with java.util.Map](https://dev.clojure.org/jira/browse/CLJ-1762) because the protocol (IKVReduce) is not extended to java.util.Map.

It would be wise to also make a similar change in `keywordize-keys` in io.pedestal.http.params.

**Comment by jcswart** [comment]
In the work I'm doing that raised this issue I used the solution here: https://dev.clojure.org/jira/browse/CLJ-1762 at the top of my service/server definition.  In my very small project I think this is likely okay. For pedestal as a whole, maybe not.

I mention it here just to share that it will solve the problem easily (buy maybe not simply).

**Comment by claj** [comment]
https://clojure.org/releases/devchangelog#_release_1_11_0 mentions:

[CLJ-1879](https://clojure.atlassian.net/browse/CLJ-1879) IKVReduce - make old slow path (IPersistentMap) faster and extend to Object, detaching it from any fully enumerable set of types

Would this make it possible to extend reduce-kv to work with `java.util.Map`?

**Comment by hlship** [comment]
I don't understand the root of this problem: under what circumstances is a java.util.Map being passed around the Pedestal code, and where?  What does AWS have to do with it?

**Comment by ohpauleez** [comment]
When you want to use a Pedestal application to process API Gateway requests, Lambda events, or SNS events, the chain provider attempts to process the request and route the information, but the internals of Pedestal routing and request building call `request-kv` and IKVReduce isn't (or wasn't at the time) extended to java.util.Map.

Above, Jarrod highlights the workaround to make this work.

Two possible solutions exist, but I'm sure the community could find others:
 * Extend a protocol Pedestal doesn't own to a type it doesn't own, but fulfilling an extension clojure.core should have (in the same way `get` works across the language boundary)
  * Replace the use of reduce-kv with `reduce` in Pedestal to make it compatible when going across the language boundary

**Comment by hlship** [comment]
```
(reduce-kv conj [] (doto (HashMap.) (.put "a" "a") (.put "b" "b")))
=> ["a" "a" "b" "b"]
*clojure-version*
=> {:major 1, :minor 11, :incremental 1, :qualifier nil}
```

Looks like this was addressed in recent versions of Clojure.

**Comment by hlship** [comment]
That's at least part of the problem solved, but I'm not sure about the rest.

**Comment by hlship** [comment]
https://clojure.atlassian.net/browse/CLJ-1762 is marked as fixed in 1.8.

**Comment by hlship** [comment]
This issue has been open for quite some time. We apologize if it has not received
the attention it deserves; given the amount of time that has passed, we are
focusing on other urgent issues.  We are closing this issue for the meantime, please re-open 
if it is still relevant.

**Comment by ohpauleez** [comment]
This is still an issue, please re-open
```
(reduce-kv (fn [acc k v] (assoc acc k v)) {} (doto (java.util.HashMap.) (.put :a :a) (.put :b :b)))
Execution error (IllegalArgumentException) at user/eval140 (REPL:1).
No implementation of method: :kv-reduce of protocol: #'clojure.core.protocols/IKVReduce found for class: java.util.HashMap
```

**Comment by hlship** [comment]
With the removal of the io.pedestal/pedestal.aws library in 0.7.0, I'm afraid this issue is no longer actionable.
