### ISSUE TITLE
Interceptor stacktrace

### ISSUE THREAD

**Issue by jeans11** [pedestal/pedestal#612]
# Description

When an exception occur in a interceptor, the stacktrace is not printed in dev mode.

## Expected Behavior

Show the stacktrace

## Actual Behavior

`Internal server error: exception`

## Steps to reproduce

# Environment

## Operating System (including version).

Mac OSX

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)

Lein 2.7.1

## Pedestal version

0.5.5

**Comment by ohpauleez** [comment]
Can you provide any steps to reproduce?  Exceptions should be printed to the logs, and by default there is a logger that prints to the console when running locally.

**Comment by jeans11** [comment]
Hi @ohpauleez! Thanks for your quick answer.

I run my project with Emacs and cider. I have no `logs` folder under my project.

Minimal route code to reproduce:

```clojure
(defn handler
  [_ req]
  {:status 200 :body (+ 1 "string")})

(defn my-route
  [_]
  ["/hello"
   :post
   (partial handler managers)
   :route-name :hello])
```
When I go to `/hello`, I have `Internal server error: exception` but the stacktrace is not printed on my console.

**Comment by jeans11** [comment]
My bad! Don't forget `org.slf4j/slf4j-simple` dependencies! I close the issue.
