### ISSUE TITLE
Add boot guide to API guide in docs

### ISSUE THREAD

**Issue by elamje** [pedestal/pedestal#616]
# Description
API Guide is not a good entry point into learning Pedestal, need to add links to install and get familiar with boot-clj first.

## Expected Behavior
I wanted to start working with Pedestal, so I went to the API guide with no knowledge of boot (only lein). The guide assumes knowledge of boot. I would recommend adding an explanation of where to get up to speed with boot before diving into the API guide.

**Comment by ddeaguiar** [comment]
Hi @elamje, thanks for trying Pedestal and sorry to hear that you had issues with the docs. I'm guessing you are referring to the docs on pedestal.io, is that correct? We currently have an [issue](https://github.com/pedestal/pedestal-docs/issues/105) open to migrate the guides and samples to use clojure's [tools.deps](https://github.com/clojure/tools.deps.alpha) tooling over boot.

**Comment by ddeaguiar** [comment]
Closing this as I think it pertains to the pedestal.io docs and I've not gotten a response.
