### ISSUE TITLE
Pedestal dependencies have CVEs of high/critical severity

### ISSUE THREAD

**Issue by mynomoto** [pedestal/pedestal#619]
# Description
I ran `dependency-check-maven` on the pom.xml generated by a tools.deps project using `clj -Spom`. The report attached contains the results showing evidence that several pedestal dependencies related to jetty contains high/critical severity. The report is zipped because github do not accept html attachments.
[dependency-check-report.html.zip](https://github.com/pedestal/pedestal/files/3214978/dependency-check-report.html.zip)

Updating jetty dependencies to the latest did not broke tests on my project and are not affected by those vulnerabilities.

## Expected Behavior
Pedestal dependencies should not have know CVEs of high/critical severity

## Actual Behavior
Pedestal dependencies have CVEs of high/critical severity

## Steps to reproduce
Run dependency-check-maven with the pom generated by tools.deps using `clj -Spom` on a project with only pedestal as dependency. I used the configuration on example 1 on this page: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/

# Environment

## Operating System (including version).
Arch Linux

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
`clj`

## Pedestal version
0.5.5

**Comment by ddeaguiar** [comment]
Thanks for reporting this, will take a look!

**Comment by ddeaguiar** [comment]
Reopening because the change has landed on `master` but a release has yet to be cut. Will close once a release is cut.

**Comment by ddeaguiar** [comment]
Release pushed.
