### ISSUE TITLE
Support service-specific error handling of errors that percolate up to stylobate

### ISSUE THREAD

**Issue by ddeaguiar** [pedestal/pedestal#623]
# Description

If a client terminates while streaming a response (such as a large file), a `java.io.IOException` with the message `Broken pipe` is thrown. Such errors are thrown by the `ring-response` [interceptor](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L288) and immediately handled by the stylobate [interceptor](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L286). It is not straight forward for a service implementor to implement a custom error handler for such errors. Error handling interceptors introduced via the `io.pedestal.http/interceptors` key occur later in the interceptor chain and are not invoked.

See #621

## Expected Behavior

Support custom error handling for errors thrown by `ring-response` or other foundational interceptors.

## Steps to reproduce

1. Create a service which serves a file resource.
2. Request the resource from a browser.
3. Close the browser before the response is finished streaming.

## Pedestal version

0.5.7

**Comment by ddeaguiar** [comment]
Service implementors do have the ability to take control over how the servlet is initialized by providing an `:io.pedestal.http/chain-provider` implementation. Ideally they'd be able to leverage the requisite fn's defined in the `io.pedestal.http.impl.servlet-interceptor` namespace but the `interceptor-service-fn` [fn](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L335) is private so composing an alternative to the `http-interceptor-service-fn` [fn](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L365) in order to take control over the foundational interceptors requires either duplicating `interceptor-service-fn` or accessing it through the var. 

Should this fn be part of the public api for the ns?

**Comment by orestis** [comment]
Just commenting on this, that as implemented, the broken pipe detection is not working, since the actual IOException is a few layers down the exception cause chain. I have implemented this as an alternative:

```
(defn- broken-pipe-in-chain? [exception]
  (loop [ex exception]
    (cond
      (nil? ex) false
      (and
       (instance? java.io.IOException ex)
       (= "broken pipe" (string/lower-case (str (ex-message ex)))))
      true
      :else (recur (ex-cause ex)))))
```

**Comment by hlship** [comment]
Maybe I'll even come up with a way to test it.
