### ISSUE TITLE
Missing catch in try? Or useless try?

### ISSUE THREAD

**Issue by DjebbZ** [pedestal/pedestal#624]
# Description

In https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L978, the code that tries to resolve the OpenTracing's GlobalTracer is wrapped in a `try` without a `catch`/`finally`. Unless I'm missing something, either somebody forgot the `catch`/`finally`, or somebody removed the `catch`/`finally` and forgot to remove the `try`.

## Pedestal version

0.5.5+

**Comment by ddeaguiar** [comment]
@DjebbZ, thanks for catching that! Based on the doc-string, I'm leaning towards catching the exception thrown when an invalid fully qualified fn name is provided, logging it and defaulting to the noop tracer. @ohpauleez do you have any thoughts on this?

**Comment by DjebbZ** [comment]
As long as the message explains that the noop tracer will be used, I think it's fine.

**Comment by ddeaguiar** [comment]
Removed `try`. Change landed on `master`. Will close this issue when the next release is cut.
