### ISSUE TITLE
X-Ray fails on tag-span when span created with :initial-tags using a Clojure map

### ISSUE THREAD

**Issue by ddeaguiar** [pedestal/pedestal#626]
# Description
When creating a span using a clojure map as the value of `:initial-tags` and subsequently calling `tag-span`, X-Ray throws an `java.lang.UnsupportedOperationException` exception.

```
{:via
 [{:type java.lang.UnsupportedOperationException,
   :at [clojure.lang.APersistentMap put "APersistentMap.java" 380]}],
 :trace
 [[clojure.lang.APersistentMap put "APersistentMap.java" 380]
  [rentals.service$eval19545 invokeStatic "NO_SOURCE_FILE" 43]
  [rentals.service$eval19545 invoke "NO_SOURCE_FILE" 43]
  [clojure.lang.Compiler eval "Compiler.java" 7177]
  [clojure.lang.Compiler eval "Compiler.java" 7132]
  [clojure.core$eval invokeStatic "core.clj" 3214]
  [clojure.core.server$prepl$fn__8941 invoke "server.clj" 232]
  [clojure.core.server$prepl invokeStatic "server.clj" 228]
  [clojure.core.server$prepl doInvoke "server.clj" 191]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [cognitect.rebl$repl invokeStatic "rebl.clj" 120]
  [cognitect.rebl$repl invoke "rebl.clj" 94]
  [cognitect.rebl$_main invokeStatic "rebl.clj" 123]
  [cognitect.rebl$_main invoke "rebl.clj" 122]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.Var applyTo "Var.java" 705]
  [clojure.core$apply invokeStatic "core.clj" 665]
  [clojure.core.server$accept_connection invokeStatic "server.clj" 73]
  [clojure.core.server$start_server$fn__8879$fn__8880$fn__8882
   invoke
   "server.clj"
   117]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 748]],
 :phase :execution}
```

[Here's](https://github.com/aws/aws-xray-sdk-java/blob/v2.2.1/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/entities/EntityImpl.java#L450) the offending line in the X-Ray SDK.

## Expected Behavior
Based on the current docs,`tag-span` should accept a clojure map.

## Steps to reproduce
1. Configure your service to register an Xray tracer
```
(require '[io.pedestal.log :as log])
(let [pspan (log/span "test-parent")
       span (log/span "test-child" pspan {:initial-tags {"foo" "bar"}})]
   (try
     (log/tag-span span "baz" "boo")
     (finally
       (log/finish-span span)
       (log/finish-span pspan)))
   )
```
# Environment
Mac OS 10.14.5, Java 1.8.0_202-ea, Leiningen 2.8.3

## Pedestal version
0.5.7

**Comment by ddeaguiar** [comment]
Ping @ohpauleez, interested in your thoughts on this one.

**Comment by ddeaguiar** [comment]
Clojure maps are immutable so perhaps we convert to a mutable map internally.

**Comment by ohpauleez** [comment]
I expected `setAnnotations` to copy key/values into an internal map of annotations, but the fact that it just updates its internal reference to be the map you provided is troubling to me.

[This line](https://github.com/pedestal/pedestal/blob/master/aws/src/io/pedestal/log/aws/xray.clj#L56) in the x-ray support to just call `tag-span` with the map arg which loop over the map entries as we'd expect.  We should also consider changing the implementation of tagging via a map from `reduce-kv` to something else, or put pressure on the Clojure.core team to close https://clojure.atlassian.net/browse/CLJ-1762 or ship the extension in the Pedestal code (which is reaching far beyond our boundary) -- (related: https://github.com/pedestal/pedestal/issues/606 )

**Comment by ddeaguiar** [comment]
Fix on master. I'm holding off on changing the use of `reduce-kv` for now since that's part of a larger issue (#606).
