### ISSUE TITLE
Lambda proxy integration doesn't set `:content-type` key in request map

### ISSUE THREAD

**Issue by ordnungswidrig** [pedestal/pedestal#630]
# Description

According to the pedestal request map documentation the key `:content-type` must contain the request's content-type if present.

## Expected Behavior

`direct-apigw-provider` will create a service map that creates request which containt the content-type in the request map.

## Actual Behavior

The content type is not present in the request map. (It's available in the request headers though). 

#### Note

This affects the `body-params` interceptor which depends on the `:content-type` key to be present.

## Comment

It's not clear to me why pedestal presents some http header values in the request map while they are also available in the headers map. The [documentation](http://pedestal.io/reference/request-map) should state whether these values are exact copies of the header value or maybe preprocessed (e.g. string->kw conversion). Also it's not obvious if the presence of these values are a "hard guarantee" by pedestal or an outcome of the default interceptor chain.

Affected headers are `Content-Type`, `Character-Encoding`, `Content-Lenght`, `Remote-Address`.

Interestingly, the [RING SPEC](https://github.com/ring-clojure/ring/blob/master/SPEC) declared some keys in the ring request map deprecated at some point. See [this ring issue](https://github.com/ring-clojure/ring/issues/103).

## Suggested fix

Set all headers as defined in the pedestal request map documentation when using `direct-apigw-provider`.

### Alternative

Deprecate the keys which are direct copies from the request headers and only make use of these.

## Pedestal version

At leaster 0.5.5 .. master

**Comment by ordnungswidrig** [comment]
> The fix to this issue is to add an interceptor to the very beginning of your chain that shapes the context and request as needed.

I would expect the `direct-apigw-provider`, like the default http servlet integration, to inject the `:content-type` key (with others) into the servlet request map. It's totally unexpected that `direct-api-provider` and `apigw-request-map` which depend on the aws api-gw lambda "http proxy" integration to not to be compatible with the standard pedestal http stack. (My understanding is that the lambda in pedestal is expecting api-gw lambda proxy integration. The code documentatin is a little vague and suggest otherwise, but the implementation depends on the proxy integration protocol).

I get your point about some chain providers doing the minimum, but why does a regular http provider (e.g. jetty) inject these keys and the lambda proxy http provider doesn't? Also that documented nowhere. In the end the code you kind of [does already exist](https://github.com/pedestal/pedestal/blob/master/samples/aws-codestar-lambda/src/pedestallambda/service.clj#L41) and moving this to inject the keys in `apigw-request-map` would be straight forward.

If appreciated, I'd happily prepare a patch.

**Comment by ohpauleez** [comment]
There were three main reasons behind this decision.  On Lambda, the platform/container is already resource constrained - Pedestal should give the user full control over how that particular resource is used while still providing options for full compatibility with the default stack.  On API-GW, a large portion of the standard interceptor stack is already performed (things are already parsed, etc) and Pedestal avoids duplicating that work.  Finally, for most things in Pedestal we don't impose a cost across all users, if there's a way users can build their desired outcome from parts.

I agree the outcome of the experience can be a bit unexpected, but the Sample App correctly illustrates how to have a compatible stack that runs in all environments (in-memory servlet, servlet container, API-GW+Lambda).

Yes, the API-GW provider expects a proxy integration.  That said, writing a custom chain provider for your particular setup is encouraged if it's more efficient or addresses the needs of your system better (I often use a custom chain provider for my production Pedestal systems).  Taking full control of the interceptor stack is also encouraged.

**Comment by ddeaguiar** [comment]
> Thank you for linking the Ring Spec and issue - it always bothered me that those fields were copied. Pedestal originally copied fields to the request map to match the earlier versions of the Ring Spec (because some Middleware expected those values to be in the request).

@ohpauleez, the copying of data to the request map bothers me as well. I understand the compatibility rationale but don't think that Pedestal-provided interceptors should depend on that behavior. We could change the body-params to use the content-type value from the `headers` instead. Thoughts?

Either way, the docs should be clearer on how the request content-type value is provided for ring middleware compatibility purposes and one should not expect it to be set by all chain providers. I'll create an issue for that in the [pedestal-docs](https://github.com/pedestal/pedestal-docs) repo.

**Comment by ordnungswidrig** [comment]
> while still providing options for full compatibility with the default stack

@ohpauleez that's the part I don't get. The default stack contains `body-params` but it fails for the api-gw lambda proxy integration. And while I know that lambda envs are resource constraint, I don't think, copying 4 values to the request map make a difference.

**Comment by ddeaguiar** [comment]
Pedestal docs issue [129](https://github.com/pedestal/pedestal-docs/issues/129) created.

**Comment by ddeaguiar** [comment]
Closing this as a docs issue exists.
