### ISSUE TITLE
Server Sent Events on client disconnect

### ISSUE THREAD

**Issue by stLalo** [pedestal/pedestal#631]
# Description
My project is an ETL tool that handles data from a Cloud drive and user input. The drive publishes messages at anytime a new file is created in the drive. My tool picks it up and does some ETL magic. Otherwise, my ETL tool handles user input related with the same entities from the drive. After new data has gone through the ETL magic box, it sends out the data to different services, including the Client (browser) via SSE.
I have a route name `/events` that will handle all the `upserted` data and send it to the client. So far I have based my development on [SSE example](https://github.com/pedestal/pedestal/blob/master/samples/server-sent-events/src/server_sent_events/service.clj). 

## Expected Behavior
For what I said above, the expected behavior is that the Client will start a SSE stream the moment the app is loaded in the browser. It won't sent data all the time. The server sends an event when it receives new data from a cloud database stream or user input. When the data has finished being polished, it is sent out to the Browser.

## Actual Behavior
The client (browser) receives the data from the server via SSE. It then updates the UI data. However, every time the client disconnects, the server throws an exception due a broken pipe.
```
15:02:17.976 ERROR [io.pedestal.http.impl.servlet-interceptor] (async-dispatch-8) {:msg "An error occured when async writing to the client", :line 116, :src-chan #object[clojure.core.async.impl.channels.ManyToManyChannel 0x2003bbe9 "clojure.core.async.impl.channels.ManyToManyChannel@2003bbe9"], :throwable #error {
 :cause "Broken pipe"
 :via
 [{:type java.io.IOException
   :message "Broken pipe"
   :at [sun.nio.ch.FileDispatcherImpl write0 "FileDispatcherImpl.java" -2]}]
 :trace
 [[sun.nio.ch.FileDispatcherImpl write0 "FileDispatcherImpl.java" -2]
  [sun.nio.ch.SocketDispatcher write "SocketDispatcher.java" 47]
  [sun.nio.ch.IOUtil writeFromNativeBuffer "IOUtil.java" 93]
  [sun.nio.ch.IOUtil write "IOUtil.java" 51]
  [sun.nio.ch.SocketChannelImpl write "SocketChannelImpl.java" 471]
  [org.xnio.nio.NioSocketConduit write "NioSocketConduit.java" 152]
  [io.undertow.server.protocol.http.HttpResponseConduit write "HttpResponseConduit.java" 607]
  [org.xnio.conduits.AbstractStreamSinkConduit write "AbstractStreamSinkConduit.java" 51]
  [org.xnio.conduits.ConduitStreamSinkChannel write "ConduitStreamSinkChannel.java" 150]
  [io.undertow.channels.DetachableStreamSinkChannel write "DetachableStreamSinkChannel.java" 240]
  [io.undertow.server.HttpServerExchange$WriteDispatchChannel write "HttpServerExchange.java" 2049]
  [io.undertow.servlet.spec.ServletOutputStreamImpl writeBufferBlocking "ServletOutputStreamImpl.java" 570]
  [io.undertow.servlet.spec.ServletOutputStreamImpl flushInternal "ServletOutputStreamImpl.java" 485]
  [io.undertow.servlet.spec.ServletOutputStreamImpl flush "ServletOutputStreamImpl.java" 472]
  [io.undertow.servlet.spec.HttpServletResponseImpl flushBuffer "HttpServletResponseImpl.java" 461]
  [io.pedestal.http.impl.servlet_interceptor$fn__13321$fn__13428$state_machine__5500__auto____13437$fn__13440 invoke "servlet_interceptor.clj" 102]
  [io.pedestal.http.impl.servlet_interceptor$fn__13321$fn__13428$state_machine__5500__auto____13437 invoke "servlet_interceptor.clj" 102]
  [clojure.core.async.impl.ioc_macros$run_state_machine invokeStatic "ioc_macros.clj" 973]
  [clojure.core.async.impl.ioc_macros$run_state_machine invoke "ioc_macros.clj" 972]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invokeStatic "ioc_macros.clj" 977]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invoke "ioc_macros.clj" 975]
  [clojure.core.async.impl.ioc_macros$take_BANG_$fn__5518 invoke "ioc_macros.clj" 986]
  [clojure.core.async.impl.channels.ManyToManyChannel$fn__482$fn__483 invoke "channels.clj" 95]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1149]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 624]
  [java.lang.Thread run "Thread.java" 748]]}}
15:02:18.973 INFO  [io.pedestal.http.sse] (async-dispatch-7) {:msg "Response channel was closed when sending event. Shutting down SSE stream.", :line 155}
19-09-24 20:02:18 Tardis INFO [sse-app.server:53] - Client disconnected

```
## Steps to reproduce
Example code
```
(defn send-random
  [event-ch & args]
  (go-loop []
    (>! event-ch {:name "sse-random" :data (rand 999)})
    (Thread/sleep 1000)
    (recur)))

(defn sse-stream
  [event-ch ctx]
  (send-random event-ch))

(defroutes routes
  [[["/random" {:get [::random (coerce-body content-neg-intc api/gen-random)]}]
    ["/sse-random" {:get [::sse-random
                          (sse/start-event-stream my-sse/sse-stream 10 10 
                                                  {:on-client-disconnect 
                                                   (fn [_]
                                                     (timbre/info "Client disconnected"))})]}]]])

```

# Environment
 * java openJDK 1.8

## Operating System (including version).
* Ubuntu 19.04

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
* boot 2.8.2
## Pedestal version
* Pedestal version "0.5.7"

**Comment by ddeaguiar** [comment]
@stLalo, thanks for using Pedestal! A `Broken Pipe` exception is expected when the client closes the connection. Now, it looks like you are using Immutant which throughs a `java.io.IOException` instead of a `java.io.EOFException` hence you are seeing this logged at the `ERROR` level. the Pedestal servlet impl [catches](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L111-L118) `EOFException`s in these cases and logs at `WARN`.

Whether the exception handler should be more general is something to consider but, again, these types of errors are to be expected.
