### ISSUE TITLE
Tracing examples: No suitable sender found and incompatible OpenTracing-API 

### ISSUE THREAD

**Issue by jbartelh** [pedestal/pedestal#635]
# Description
i recently tried the two examples, 'tracing' and 'tracing-interceptor', and ran into some problems.

In PR #632 the version of the jaeger-java-client was updated to '1.0.0', since then the sender implementations are missing which are mandatory for sending captured span data to the Jaeger-backend. This can be noticed in the logs by starting the service:
`WARN  i.j.internal.senders.SenderResolver - No suitable sender found. Using NoopSender, meaning that data will not be sent anywhere!`
Just adding `[io.jaegertracing/jaeger-thrift "1.0.0"]` as a another dependency solves this issue (implementations are loaded from the classpath).

After this, the 'tracing' example worked, but i faced another problem with the 'tracing-interceptor' example. The following exception is thrown when visiting the /trace route:
`clojure.lang.ExceptionInfo: java.lang.NoSuchMethodError in Interceptor  - io/opentracing/Tracer$SpanBuilder.startActive(Z)Lio/opentracing/Scope;`
The 'OpenTracing-API' had breaking changes after version 0.31.0, which aren't supported by the opentracing-apache-httpclient version '0.1.0'. Updating this dependency solves the issue:
`[io.opentracing.contrib/opentracing-apache-httpclient "0.2.0"]`

## Expected Behavior
The example services should emit recorded trace data to Jaeger-backend.

## Actual Behavior
No trace data is send to Jaeger.

## Steps to reproduce
Check out the examples, build and install pedestal into local maven repository and run examples with the build pedestal versions.

## Operating System (including version).
Ubuntu 18.04.3 LTS

## Your current Leiningen or Boot version
Leiningen 2.9.1 on Java 11.0.4 OpenJDK 64-Bit Server VM

## Pedestal version
0.5.8-SNAPSHOT, Current master branch, Commit: f0df4a5ac983fd4e7d0a4f667bffb0ad5938d56e

**Comment by ddeaguiar** [comment]
@jbartelh, thanks for reporting this! We'll work on getting the sample updated

**Comment by ddeaguiar** [comment]
Fix landed on `master`.
