### ISSUE TITLE
HOWTO: servlet-less tests

### ISSUE THREAD

**Issue by vemv** [pedestal/pedestal#637]
## Problem statement

Seemingly there are two main ways of testing Pedestal-oriented code:

* Exercise one's `defn`s in isolation
  * e.g. hashmap in, hashmap out
  * No Pedestal "context" whatsoever: interceptor chain, routing, servlets etc
  * Clean, fast, functional
* Use the `response-for` helper
  * Exercises more Pedestal-related code: interceptor chain, routing, servlets etc
  * Can uncover bugs related to low-level things like HTTP / IO, or global things like how one's app is assembled

Both are nice, but quite obviously both have some drawbacks.

Specifically, `response-for` involves spinning up an actual Servlet, which is: 

* slower
* more fragile
  * normally one has to place some `fixture` catching failures and stopping the server
* less parallelizable
  * can require careful port management, in order to avoid 2 threads open a servlet over the same port.

So, I'm looking for a middle ground solution for running most of my tests:

* my tests should hit the Pedestal stack to a reasonable degree
* they should remain reasonably isolated/fast/parallelizable

## Use case

As an experience report, I have successfully written this type of "middle ground" tests over the last year, in a non-Pedestal app. It is planned to eventually migrate this app to Pedestal, but having the existing test suite become kind of worse would be a no-go.

## Proposed solution

* Document a way to write tests that hit a given interceptor chain + routing setup, without involving a Servlet.
* Make tests written in this style part of Pedestal's test suite, so they serve as an example guaranteed to work.

## Attempt

Here's a kind-of-working attempt:

```clj
(ns example.test
  (:require
   [clojure.pprint :as pprint]
   [clojure.test :refer [deftest]]
   [io.pedestal.http :as http]
   [io.pedestal.http.route.definition :refer [defroutes]]
   [io.pedestal.interceptor :as interceptor]
   [io.pedestal.interceptor.chain :as interceptor.chain]
   [ring.util.response]))

(def example-endpoint
  (interceptor/interceptor (fn [context]
                             (-> context
                                 (assoc :response (ring.util.response/response "Hello"))))))

(def interceptor-chain
  (let [{:keys [:io.pedestal.http/interceptors]} (io.pedestal.http/default-interceptors
                                                  {:env          :test
                                                   ::http/routes #{["/" :get example-endpoint :route-name ::example-endpoint]}})]
    (conj interceptors example-endpoint)))

(deftest works
  (-> {::interceptor.chain/queue []
       :request                  {:scheme         :http
                                  :request-method :get
                                  :protocol       "HTTP/1.1"
                                  :headers        {}
                                  :server-port    80
                                  :remote-addr    "0.0.0.0"
                                  :server-name    "localhost"
                                  :uri            "/"}}
      (interceptor.chain/execute interceptor-chain)
      (pprint/pprint)))

```

...the code will run without errors and the interceptor chain will be effectively exercised.

However the response will be `:status 404`: I couldn't get routing to work.

Maybe fixing routing, and some other nuance which I may have missed Pedestal could document this as an alternative?

## Pedestal version

```clj
  [io.pedestal/pedestal.jetty "0.5.7"]
  [io.pedestal/pedestal.service "0.5.7"]
```

---

Thanks - V

**Comment by ohpauleez** [comment]
Thanks for the bug report!

There is a little bit of misunderstanding that I think can be cleared up - your 'middle ground' approach is `response-for`.

`response-for` doesn't use a running server.  It generates a reified Servlet and just `executes` your interceptor chain within its handling.  You can run as many as you want in parallel with different instantiations.  In this way, you're seeing an HTTP response right before it would be sent out to the container.  You don't need any fixture for creating, starting, or stopping the server.  The standard Pedestal template or sample applications should help illustrate how to use `response-for` effectively.

Hope this help!

**Comment by vemv** [comment]
Hi @ohpauleez, thanks for the reply!

You're right: there's no actual port usage or perf overhead. Benchmarking with `criterium` reports 127μs per `response-for` call, for an empty app and silenced logging.

I think I assessed badly the Pedestal internal code and had incorrect/mixed memories of previous Pedestal experience. Sorry for that!

However, [hello-world.service-test](https://github.com/pedestal/pedestal/blob/4fe921325c06f8ccfa9dd5cac8c324c93a84b1f8/samples/hello-world/test/hello_world/service_test.clj) (which was part of my assessment) is a bit confusing.

Inlining the whole example, we get something analog to:

```clj
(require '[io.pedestal.http :as http]
         '[io.pedestal.test :refer [response-for]])

(def service-fn
  (-> {:env                 :test
       ::http/routes        #{}
       ::http/resource-path "/public"
       ::http/type          :jetty
       ::http/port          8080}
      http/create-servlet
      ::http/service-fn))

(comment
  (response-for service-fn :get "/"))
```
The problem being, the code explicitly contains references to `:jetty` and `8080`. That can lead newcomers to believe that there's an actual Jetty server running over 8080 as one runs the tests.

What could be improved?

* Adding a comment to `hello-world.service-test` indicating the actual nature of the test
* Making the `response-for` docstring clearer 
  * e.g. explicitly state that no server is run, even in face of `::http/type` and `::http/port` arguments 
  * Maybe explain a bit that this works via a reified Servlet

WDYT?

**Comment by vemv** [comment]
I'll close this issue so as not to keep the GH issue count high (particularly with a slightly confusing issue), but I think improving the suggested docstring and examples would be a nice addition.

-V
