### ISSUE TITLE
Override logger used incorrectly in pedestal.log log function.

### ISSUE THREAD

**Issue by ddeaguiar** [pedestal/pedestal#638]
# Description
The [`override-logger`](https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L196) is a factory function which takes a single argument and returns a logger instance.  However, the `log` function, which exposes logging capabilities as a function, [treats it](https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L247) as a logger instance.

Thanks to @hlship for reporting this in the #pedestal Clojurians Slack channel.

## Expected Behavior
The `override-logger` should be used In `log` to create a logger instance.

## Actual Behavior
The `override-logger` is treated as a logger instance which leads to an exception being thrown when an override logger is specified.

## Steps to reproduce
1. Create a new project which implements `io.pedestal.log/LoggerSource`.
1. Set the `override-logger` using the `PEDESTAL_LOGGER` envar.
1. Call `io.pedestal.log/log` without setting the `:io.pedestal.log/logger` key.

# Environment
Leiningen 2.8.3 on Java 1.8.0_222 OpenJDK 64-Bit Server VM

## Operating System (including version).
MacOS Catalina 10.15.2

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
See above.
## Pedestal version
0.5.7

**Comment by ddeaguiar** [comment]
The fix is to create the logger instance using the `override-logger` fn [here](https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L247) as we do for `LoggerFactory/getLogger` in the [next line](https://github.com/pedestal/pedestal/blob/master/log/src/io/pedestal/log.clj#L24).

**Comment by hlship** [comment]
Thanks for looking into this; I was just opening up Slack to see if I needed to add this very issue.

**Comment by orestis** [comment]
BTW this is a breaking change in 0.5.8 -- I was calling `(log {:io.pedestal.log/logger-name "my.logger" ,,,})` which was working, and now it blows up because it tries to call `override-logger` as a function, which is nil.

**Comment by ddeaguiar** [comment]
@orestis yep, the override-logger check should be `(and override-logger (override-logger logger-name))`. I'll create an issue.
