### ISSUE TITLE
Outdated Dockerfile FROM-image

### ISSUE THREAD

**Issue by ivarref** [pedestal/pedestal#642]
Hi, and thanks for a very fine project!

# Description

It seems that the example Dockerfile uses a discontinued image:

```bash
$ lein new pedestal-service my-project

$ cat my-project/Dockerfile 
FROM java:8-alpine
...
```

The `java` docker image has been discontinued. [https://hub.docker.com/_/java](https://hub.docker.com/_/java) redirects to [https://hub.docker.com/_/openjdk](https://hub.docker.com/_/openjdk).

The java version is outdated in the discontinued image:
```bash
$ docker pull java:8-alpine && docker run java:8-alpine /usr/bin/java -version
...
openjdk version "1.8.0_111-internal"
```

whereas in the `openjdk` image the java version is updated:
```bash
$ docker pull openjdk:8-alpine && docker run openjdk:8-alpine /usr/bin/java -version
...
openjdk version "1.8.0_212"
```

## Pedestal version
`0.5.7`

Thanks and kind regards.

**Comment by ddeaguiar** [comment]
Thanks for opening the issue. I'll take a look!
