### ISSUE TITLE
"What is an Interceptor?" guide raises unexpected exception.

### ISSUE THREAD

**Issue by aidanhb** [pedestal/pedestal#649]
# Description
The interceptor guide titled "What is an Interceptor?" errored out in the section "Manipulating The Queue". Copying the additional interceptors into `service.clj` causes an internal server error, namely: `Assert failed: (every? interceptor/interceptor? interceptors)`. I believe this is thrown during the `chain/enqueue` operation.

## Expected Behavior
A request to `http://localhost:8822/data-science?n=2` should return the text `Even numbers are my bag`.

## Actual Behavior
Caused internal server error `Assert failed: (every? interceptor/interceptor? interceptors)`.

## Steps to reproduce
Follow the steps in the guide up to and including "Manipulating The Queue".

## Steps to fix
Cast all interceptor maps as `Interceptor`s:
1. Require `[io.pedestal.interceptor :as interceptor]`
2. Pass all interceptor maps to the `interceptor/interceptor` function before returning.

# Environment
VSCode 1.43.0
JDK:
```
java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

## Operating System (including version).
macOS Catalina 10.15.2

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Leiningen 2.9.1

## Pedestal version
0.5.7

**Comment by ddeaguiar** [comment]
Hi @aidanhb, thanks for reporting this. The pedestal documentation is housed in a separate [repository](https://github.com/pedestal/pedestal-docs) so I'm closing this issue and creating in there. I'll have a fix for the docs out shortly.
