### ISSUE TITLE
Support accessing incoming message Session when working with WebSockets.

### ISSUE THREAD

**Issue by ddeaguiar** [pedestal/pedestal#659]
This request has come up numerous times ([example](https://clojurians-log.clojureverse.org/pedestal/2020-04-09)) in the #pedestal Slack Clojurians channel. 

# Description

Outside of the `onWebSocketCreate` implementation, Pedestal's `WebSocketListener` does not provide visibility to the underlying WebSocket Session which contains a reference to the upgrade request and it's associated headers, session info, etc... If this information were made visible to the other WebSocket lifecycle methods then the service implementer could leverage it to make more informed decisions about message handling. As of now it looks like folks are rolling their own `WebSocketListener` to handle such needs.

References:
- Jetty [docs](https://www.eclipse.org/jetty/documentation/current/jetty-websocket-api-listener.html)
-

**Comment by ohpauleez** [comment]
I strongly support this.  It's a change I have wanted to make for quite a long time (it just was always at the bottom of the list because WebSockets weren't used as much as other parts of the system).

**Comment by Hindol** [comment]
Are you also planning to integrate the interceptor model with WS data handling?

I am myself not sure how that would look like as WS does not dictate the format of messages and thus cannot be naturally converted to a map representation.

**Comment by ddeaguiar** [comment]
@Hindol no but I'll think through that further. Pedestal's philosophy is to provide the functionality which service implementors need to construct their services while trying not to be too prescriptive. It's easy enough for service implementors to add since the interceptor model is backed by a public API. 

As for the message, it would be a key on the context map. FWIW, I think it only makes sense to support unidirectional processing (i.e., `:leave` doesn't really make sense).

**Comment by ohpauleez** [comment]
@Hindol The Interceptor engine already supports executing a chain in a single direction via [execute-only](https://github.com/pedestal/pedestal/blob/master/interceptor/src/io/pedestal/interceptor/chain.clj#L326).  This was originally done to handle streams and has been used to build systems for WebSockets, Kafka, and others.

As @ddeaguiar alluded to, interceptors take and return contexts.  A "chain provider" is responsible for making the initial context (map), and calling `execute` or `execute-only` with your chain (vector) of interceptors.  To use interceptors with WebSockets, the body of your `on-text` or `on-binary` function would build an initial context and call `execute-only` (which returns a final, fully-processed context - you can do whatever you want with the result).

**Comment by hlship** [comment]
As implemented in #762 , an endpoint map can define several callbacks (on-open, on-close, on-error, on-text, and on-binary).  The first three are passed the jakarta.websocket.Session.  With some work, I could pass the session to the on-text and on-binary callbacks as well.

**Comment by hlship** [comment]
I was just reviewing earlier web socket changes.  In 0.7.x, you can provide callbacks related to web socket connections, which are bundled up with a path and passed to io.pedestal.websocket/add-endpoints.

```
  :on-open (jakarta.websocket.Session,  jakarta.websocket.EndpointConfig)
  : Invoked when client first opens a connection.  The returned value is retained
    and passed as the first argument of the remaining callbacks.

  :on-close (Object, jakarta.websocket.Session, jakarta.websocket.CloseReason)
  : Invoked when the socket is closed, allowing any resources to be freed.

  :on-error (Object, jakarta.websocket.Session, Throwable)
  : Passed any unexpected exceptions.

  :on-string (Object, String)
  : Passed a text message as a single String.

  :on-binary (Object, java.nio.ByteBuffer)
  : Passed a binary message as a single ByteBuffer.
```

Whatever is returned from the :on-open callback will be the first parameter passed to all other callbacks.

So, you can capture the Session in :on-open and return it, or return a map containing it, and other callbacks can have access to it.

**Comment by hlship** [comment]
I think the enhancements in 0.7.0 already address this issue. I'm going to close this issue unless. Please re-open if you have further clarifications.
