### ISSUE TITLE
Fix Override logger usage when using Pedestal's logging macros

### ISSUE THREAD

**Issue by ddeaguiar** [pedestal/pedestal#660]
# Description

This issue stems from a recent discussion with @hlship in Slack.

#638 addressed override logger usage with the `io.pedestal.log/log` fn but there's still an issue with setting the override logger when using the log macros. It appears the override logger is interpreted too late and thus, not used.

## Actual Behavior

The default logger is used.

0.5.8

**Comment by ddeaguiar** [comment]
@hlship has reported that he is using the following workaround:

```
(def logger (memoize logger*))
;; This actually doesn't accomplish anything in Pedestal 0.5.8
(alter-var-root #'io.pedestal.log/override-logger (fn [_] logger))
(System/setProperty  "io.pedestal.log.overrideLogger" "com.walmartlabs.log.pedestal/logger")
```

**Comment by ddeaguiar** [comment]
I do recall working through this at some point but need to find my notes around this.

**Comment by ddeaguiar** [comment]
@hlship, I've added a [sample](https://github.com/pedestal/pedestal/tree/master/samples/override-logging) which demonstrates how to configure an override logger for use with Pedestal's macros. There are some nuances to the configuration because:
1. The `LoggerSource` protocol and override logger usage reside in the same namespace (`io.pedestal.log`)
2. You must be careful what gets AOT compiled otherwise logging done through macros won't pick up the override logger setting at runtime.

I'll leave this issue open for a now to collect additional feedback.

**Comment by ddeaguiar** [comment]
Closing since a sample demonstrating usage is now on `master`.

**Comment by hlship** [comment]
Thanks for the work; I've been slammed at work and haven't had a chance to look at this solution yet.

**Comment by hlship** [comment]
It would be nice if you could deprecate LoggerSource protocol and create a new namespace with an equivalent, with mappings from the old to the new.  That would break this awful (but fortunately, pretty rare) dependency cycle.

**Comment by ddeaguiar** [comment]
@hlship yes, something to consider. Overriding the logger is currently not intuitive and I can only surmise that it's not done very frequently because of that.

**Comment by hlship** [comment]
A lot of our code base predates many of the common libraries that are available now and too much of our monitoring is built on the exact way our Log4J wrappers execute.  I don't have permission to disrupt the world by moving everything over to Pedestal logging even though I vastly prefer logs-as-data (and it would ultimately make our monitoring easier).
