### ISSUE TITLE
CORS / Access-Control-Allow-Origin and other headers not set / not correct even when explicitly set in response

### ISSUE THREAD

**Issue by lucian303** [pedestal/pedestal#664]
# Description

In the service config, I set `::http/allowed-origins ["*"]` but the CORS headers don't show up. In my current app `Access-Control-Allow-Origin` shows up as a blank header *even when I explicitly set the header in a response map to `*`.*

## Expected Behavior
CORS headers should work. `Access-Control-Allow-Origin` should be set to `*`. `Access-Control-Allow-Methods` at a minimum should be set and sent to the default value.

## Actual Behavior

Either no CORS headers at all or `Access-Control-Allow-Origin` is set to an empty string.

## Steps to reproduce

New pedestal app with `lein new pedestal-service testing-pedestal`
In the service config, I set `::http/allowed-origins ["*"]`
Curl the test routes

# Environment

Clojure 1.10.1 / JDK 11 / Pedestal / Jetty

## Operating System (including version).

OS X 10.15.5

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)

Leiningen 2.9.3 on Java 11.0.6 OpenJDK 64-Bit Server VM

## Pedestal version

0.5.8

**Comment by Wellers0n** [comment]
I'm with a error similar: `INFO  io.pedestal.http.cors  - {:msg "cors request processing", :origin "http://localhost:3000", :allowed nil, :line 84}`

**Comment by ddeaguiar** [comment]
@lucian303 the way to _wildcard_ origins is to set `::http/allow-origins (constantly true)`. The value `*` as an _allowed-origin_ string was never intended to convey that semantic. A server _may_ decide to return `Access-Control-Allow-Origin: *` to convey to browsers that any origin can access the resource in question but Pedestal does not do that.
