### ISSUE TITLE
Access the WebSocket Session object in ws-paths when using Jetty

### ISSUE THREAD

**Issue by lukaszmakuch** [pedestal/pedestal#669]
Hi! 👋 

I'd like to start a discussion about WebSocket Sessions and Jetty.

## Expected Behavior

In a long running, production service I'd like to keep the memory consumption low.
Additionally, when a message arrives, I'd like to be able to access detailed information about it, such as the `.getRequestURI`.

## Actual Behavior

1. New sessions and channels are always added to `ws-clients`, but never removed, what makes it grow over time.
2. In the function associated with `:on-text` in `ws-paths`, we know what is the message, but we don't know which session sent it.

## Steps to reproduce

1. Run this example https://github.com/pedestal/pedestal/tree/master/samples/jetty-web-sockets
2. In REPL observe @ws-clients as clients connect and disconnect

## My workaround

First of all, I'd like to say that I'm a clojure amateur, so my solution may totally be flawed. I'd like to present it anyways, just to illustrate where I was heading, as well as get your opinion whether this makes any sense. 

In my project I decided to provide a custom `:listener-fn`, like this:
```clojure
:context-configurator #(add-ws-endpoints % ws-paths {:listener-fn ws-listener}
```

`ws-listener` passes the Session object to all the functions:
```clojure
(ns ...
  (:require ...
            [io.pedestal.http.jetty.websockets :refer [start-ws-connection]])
  (:import [org.eclipse.jetty.websocket.api Session WebSocketAdapter]))

;; ...

(defn ws-listener
  [_request _response ws-map]
  (proxy [WebSocketAdapter] []
    (onWebSocketConnect [^Session ws-session]
      (proxy-super onWebSocketConnect ws-session)
      (when-let [f (:on-connect ws-map)]
        (f ws-session)))
    (onWebSocketClose [status-code reason]
      (when-let [f (:on-close ws-map)]
        (f (.getSession this) status-code reason)))
    (onWebSocketError [^Throwable e]
      (when-let [f (:on-error ws-map)]
        (f (.getSession this) e)))
    (onWebSocketText [^String message]
      (when-let [f (:on-text ws-map)]
        (f (.getSession this) message)))
    (onWebSocketBinary [^bytes payload offset length]
      (when-let [f (:on-binary ws-map)]
        (f (.getSession this) payload offset length)))))
```
And here's a snippet illustrating what it enables me to:
```clojure
(def ws-clients (atom {}))

(defn get-session-id [ws-session]
  (-> ws-session
      .getRequestURI
      .getQuery
      route/parse-query-string
      :session))

(defn new-ws-client
  [ws-session send-ch]
  (let [sess (get-session-id ws-session)]
    (swap! ws-clients assoc sess send-ch)))
    ;; here you may want to do something in response to the new connection

(def ws-paths
  {"/ws" {:on-connect (start-ws-connection new-ws-client)
          :on-text (fn [sess msg] (receive-message! (get-session-id sess) msg))
          :on-binary (fn [sess payload offset length] (log/info :msg "Binary Message!" :bytes payload))
          :on-error (fn [sess t] (log/error :msg "WS Error happened" :exception t))
          :on-close (fn [sess num-code reason-text]
                      (swap! ws-clients dissoc (get-session-id sess))
                      (handle-disconnection! (get-session-id sess)))}})
```
All the functions start like `(fn [sess `, where `sess` is the WebSocket Session object form Jetty.
When a client disconnects, I can `dissoc` the corresponding channel from `ws-clients`. 
Also, when a message arrives, I know exactly which client sent it, what's crucial to my business logic. 

**What do you think? Is this the "right" way?**

# Environment
Docker
```
FROM clojure:lein
```

## Operating System (including version).
Docker Desktop (engine 19.03.12) on a mac (10.15.6)

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
```
Leiningen 2.9.3 on Java 11.0.8 OpenJDK 64-Bit Server VM
```

## Pedestal version
0.5.8

**Comment by ddeaguiar** [comment]
Hi @lukaszmakuch, thanks for your interest in Pedestal! This is a dup of #659 so I'm going to go ahead and close this issue.

**Comment by sudorock** [comment]
@lukaszmakuch Thanks for your example, it was very helpful.
