### ISSUE TITLE
WebSockets, Jetty, and keeping connection alive with Ping/Pong

### ISSUE THREAD

**Issue by lukaszmakuch** [pedestal/pedestal#670]
Hi! 👋 

I'd like to start a discussion about keeping WebSocket connections alive.

## Steps to reproduce

1. Run this example https://github.com/pedestal/pedestal/tree/master/samples/jetty-web-sockets
2. Connect in a browser
3. Wait over 30 seconds

## Actual Behavior

Even though both the server and the browser are running, the connection ends due to inactivity.

## Expected Behavior

I'd like the WebSockets connection to stay open as long as the client's browser is open, so that I can send messages from the server to the client at any time.

## My workaround

First of all, I'd like to say that I'm a clojure (and Java) amateur, so my solution may totally be flawed. I'd like to present it just to illustrate what was the problem I was trying to solve, as well as to get your opinion on whether this is the right way to do it. 

When a new Session starts, I set its idle timeout to some value and then, as long as it's open, I ping it at an interval smaller than the timeout.

Please bear in mind the concrete values (5s, 1s) are just for testing purposes and may require tweaking for production usage. 

```clojure
(defn new-ws-client [ws-session send-ch]
  (.setIdleTimeout ws-session 5000)
  (go-loop []
    (<! (timeout 1000))
    (if (.isOpen ws-session)
        (do (.sendPing (.getRemote ws-session) (ByteBuffer/allocate 1))
            (recur)))))
```

The browser will automatically respond with Pong. If it arrives, the session will stay open. If it doesn't, it'll be closed.

To be honest, I was kinda surprised that I had to write this code. I still have a feeling that I might have missed some obvious way of keeping connection alive. If so, please let me know how this may be achieved. 

# Environment
Docker
```
FROM clojure:lein
```

## Operating System (including version).
Docker Desktop (engine 19.03.12) on a mac (10.15.6)

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
```
Leiningen 2.9.3 on Java 11.0.8 OpenJDK 64-Bit Server VM
```

## Pedestal version
0.5.8

**Comment by ddeaguiar** [comment]
Hi @lukaszmakuch, Pedestal's philosophy is to provide the foundational implementation required to integrate with WebSockets while providing the hooks and escape hatches necessary for Pedestal users to customize the implementation to fit their needs. The fine-grained session control you've captured above falls outside of Pedestal's scope.

In regards to Your approach, I don't think you are missing something in regards to keeping the connections alive.

**Comment by ohpauleez** [comment]
Hi @lukaszmakuch, thanks for using Pedestal and reporting an issue to try to make it better!
As @ddeaguiar stated, one of core principles in Pedestal is let the developer keep control.

A few things you might want to consider when designing your WebSocket-based system:
 * If your client is on a lossy/unreliable link, it will need to handle reconnect logic.  If this logic is at the foundation of your client code, then reconnecting for interaction is less problematic (and you don't have to manage the WS Ping/Pong heartbeat on the server-side).  This approach makes more sense if all logic/control/data-flow is client-based - if it's largely server-based, heartbeats tend to be favored.  Regardless, if you're keeping connections open, you'll need to ensure your OS is tuned appropriately for max-open-files/ulimit.
 * If your application protocol design is such that the client is issuing commands and the server is streaming back results (ie: the dataflow is unidirectional, and you don't need a full-duplex comm), server-sent events might make your life easier.

Hope this helps!
--Paul
