### ISSUE TITLE
CORS Error request processing

### ISSUE THREAD

**Issue by Wellers0n** [pedestal/pedestal#677]
I'm with this error on pedestal, can someone help me with this ?

`INFO  io.pedestal.http.cors  - {:msg "cors request processing", :origin "http://localhost:3000", :allowed nil, :line 84}`

**Comment by gnarroway** [comment]
That is not an error. It is just a noisy INFO level log when you enable the `allow-origin` [default interceptor](http://pedestal.io/reference/default-interceptors).

You can turn it off by configuring your log library, e.g. for `log4j2`:

```
logger.pedestal.name = io.pedestal.http.cors
logger.pedestal.level = off
```

That said, I think pedestal should consider making it a DEBUG level log.

**Comment by Wellers0n** [comment]
Where can I put this config?

**Comment by Wellers0n** [comment]
but in the browser I receive a cors error

![image](https://user-images.githubusercontent.com/39449389/106923157-8daa5f00-66ec-11eb-8aa0-c48be30df855.png)

**Comment by ddeaguiar** [comment]
@Wellers0n there's not enough information to understand your issue. When running in dev mode you'll want to allow all origins ([example](https://github.com/pedestal/pedestal/blob/master/samples/hello-world/src/hello_world/server.clj#L34)). If you generated your service using the `pedestal-service` template, you should see this approach used in the `run-dev` implementation.

**Comment by ddeaguiar** [comment]
Closing this for now.
