### ISSUE TITLE
print-method generates an invalid edn when printing interceptors without name

### ISSUE THREAD

**Issue by souenzzo** [pedestal/pedestal#678]
# Description

## Expected Behavior

I expect that print-method print's a valid edn

## Actual Behavior

print-method generates `{:name }`

## Steps to reproduce

```
(-> #{["/" :get (fn [_]) :route-name :hello]}
    (route/expand-routes)
    first
    :interceptors
    first)
=> #Interceptor{:name }
```

# Environment

## Operating System (including version).

`Linux T480 5.10.16-arch1-1 #1 SMP PREEMPT Sat, 13 Feb 2021 20:50:18 +0000 x86_64 GNU/Linux`

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)

`clj v1.10.2.774`

## Pedestal version

`0.5.8`

**Comment by souenzzo** [comment]
It can be fixed with a `pr-str` at https://github.com/pedestal/pedestal/blob/master/interceptor/src/io/pedestal/interceptor.clj#L21
```
-  (.write w (str "#Interceptor{:name " (.name i) "}"))
+  (.write w (str "#Interceptor{:name " (pr-str (.name i)) "}"))
```

**Comment by ddeaguiar** [comment]
Thanks for reporting. Another option is to not include `:name` if it's not present.
