### ISSUE TITLE
Include ex-data in the response built by the exception-debug dev-interceptor

### ISSUE THREAD

**Issue by dannyfreeman** [pedestal/pedestal#687]
### Problem
When developing with the default dev-interceptors, I view any exceptions thrown by an endpoint in the response body through my web browser. My code will almost always throw exceptions using `ex-info` and include relevant ex-data that may have caused the exception to be thrown. That ex-data is not included in the response, which is built by the  `:io.pedestal.http.impl.servlet-interceptor/exception-debug` interceptor. I would like for it to be included.

### Rationale
Carefully crafted ex-data can make issues easy to identify and resolve. The `exception-debug` interceptor already handles showing the exception message and pedestal context so it seems like a good place to also include ex-data.

### Proposed Solution

If `ex-data` exists on an exception when the `error-debug` interceptor is running, include it in the response here: https://github.com/pedestal/pedestal/blob/6b518f1403132e0474daa5edaf08b1de1df267b5/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L319-L322

Implementing this could be as simple as adding the following expression into the code linked directly above

```clojure
(when-let [data (ex-data exception)]
  (println "\nEx-data\n")
  (pprint/pprint data))
```

I would be very happy to open a PR for this, made a branch on my fork to start https://github.com/dannyfreeman/pedestal/commit/fcd46742c037e39879fa1562629828002a9dd1d1

**Comment by ddeaguiar** [comment]
Hi @dannyfreeman! The ex-data is visible in the printed exception. There's no need to create a separate section for that.
