### ISSUE TITLE
Expose `.setUser` on AWS X-ray segments

### ISSUE THREAD

**Issue by orestis** [pedestal/pedestal#701]
# Description

It seems like the SDKs for Xray have a special value for user, where instead of just adding annotations it's a top level field. It would be nice if this could be handled via the X-ray tracing adapter.

## Expected Behavior

`(log/tag-span x "user" "U12345")` should call `segment.setUser("U12345")`.

## Actual Behavior

`(log/tag-span x "user" "U12345")` sets an annotation with the name user.

## Steps to reproduce

# Environment

**Comment by ddeaguiar** [comment]
Hi @orestis, thanks for using Pedestal! I'm hesitant to mix tag support with X-ray's `setUser` method on segments. As per the OpenTracing [docs](https://opentracing.io/docs/overview/tags-logs-baggage/):

> Tags are key:value pairs that enable user-defined annotation of spans in order to query, filter, and comprehend trace data

 and `setUser` is something other than a "user-defined" annotation. While using a tag seems like a convenient way to shuttle the value in, I'm not convinced it's the best way. I'll flag this issue for further discussion.

**Comment by ohpauleez** [comment]
If certain applications want implementation specific behavior, I would expect that to happen at the application level and not at the interface level.  @orestis If all of your systems are using X-Ray and you never run/test locally with OpenTracing+Jaeger, you might find it helpful to make a library namespace in your service for the X-Ray specific things you'd like to do.
Other companies take that approach (eg: Kevel).
In this setup, you're fully in control of the implementation specific details.

**Comment by orestis** [comment]
Thanks for the replies! Indeed the setUser is an annoyance of xray, all it does is that it sets a field in a class that is serialized to JSON via an ObjectMapper. I chalk it down to Java class-itis. @ohpauleez indeed I will probably go down the route of having a custom namespace that forwards to pedestal.log plus some other conveniences like this. Or perhaps this is a function that could be added at the pedestal X-ray adapter since it’s imported anyway?

**Comment by ddeaguiar** [comment]
> Or perhaps this is a function that could be added at the pedestal X-ray adapter since it’s imported anyway?

I'm not sure that adds much value over calling `.setUser` directly.

**Comment by hlship** [comment]
I'm afraid that with the removal of the io.pedestal/pedestal.aws library as part of 0.7.0, this issue is no long actionable.
