### ISSUE TITLE
Wildcard route matches randomly with linear router as route order cannot be specified in set using table syntax

### ISSUE THREAD

**Issue by lucian303** [pedestal/pedestal#709]
# Description
I have some routes:
```
(def routes #{["/" :get (conj html-interceptors `home-page)]
              ["/api/config" :get (conj open-api-interceptors `config)]
              ["/*all" :get (conj html-interceptors `all-page)]})
```
And I added `   :io.pedestal.http/router :linear-search` to my service map.

I just want a wildcard route for the entire site. The docs suggest this is possible with the linear router. However, the router randomly chooses which route to follow. Sometimes the wildcard, sometimes the explicit rule. I have tried reordering the routes and it has zero effect. I've tried using an ordered set. That didn't work.

So if the linear router tests routes in order, what does that mean since the routes have to be a set and a set by definition has no order? Basically the linear router cannot be linear in any predictable way and it seems to refuse vectors and other data structures that have order.

Is the only solution to use expanded syntax? The terse syntax is too simplistic as I have more than one interceptor. I've extended the ExpandableRoutes protocol in the meantime to process vectors using table syntax, but for the library as a whole, a different solution is needed, possibly a config option in the routes to indicate the type rather than inferring the type from the collection type. Relying on an unordered set for an ordered list is not going to work.

```
(extend-protocol route/ExpandableRoutes
  clojure.lang.APersistentVector
  (-expand-routes [route-spec]
    (table/table-routes route-spec)))
```

## Expected Behavior

Wildcard route catches all routes *except* the explicitly defined ones when using the linear router.

## Actual Behavior

Route being matched is random and even random per request to the same running server: some requests get the explicit route, some get the wildcard.

## Steps to reproduce

Add routes to a linear router and hit endpoints.

# Environment

clj version 1.10.3.1058

## Operating System (including version).

macos 11.6.3

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)

Leiningen 2.9.6 on Java 11.0.12 OpenJDK 64-Bit Server VM

## Pedestal version

0.5.10

**Comment by ddeaguiar** [comment]
@lucian303 you can achieve the behavior you desire by calling [`table-routes`](http://pedestal.io/api/pedestal.route/io.pedestal.http.route.definition.table.html#var-table-routes) directly.

```
(def routes  (table/table-routes [["/" :get (conj html-interceptors `home-page)]
                                  ["/api/config" :get (conj open-api-interceptors `config)]
                                  ["/*all" :get (conj html-interceptors `all-page)]}])
```

Just keep in mind that if you are using the service template you'll have to remove the explicit `expand-routes` call used to set `::server/routes` in the `server` ns `run-dev` impl.

**Comment by ohpauleez** [comment]
In Pedestal2 the linear-search router was updated to handle this case (and we could easily backport the change here).

This [line in the linear-search](https://github.com/pedestal/pedestal/blob/master/route/src/io/pedestal/http/route/linear_search.clj#L50) really ought to group routes with those containing `:path-params` and those that don't.  Then do the current `mapv` over the `(concat no-params with-params)` so that static routes will always be matched first over wildcard routes, regardless of specification.

**Comment by lucian303** [comment]
Thanks @ddeaguiar. It's that `expand-routes` call I missed earlier when trying the `table-routes` fn. It's working now this way without extending the protocol.

**Comment by ddeaguiar** [comment]
> This [line in the linear-search](https://github.com/pedestal/pedestal/blob/master/route/src/io/pedestal/http/route/linear_search.clj#L50) really ought to group routes with those containing :path-params and those that don't. Then do the current mapv over the (concat no-params with-params) so that static routes will always be matched first over wildcard routes, regardless of specification.

Thanks @ohpauleez, I'll open a ticket to explore this
