### ISSUE TITLE
[Question] How add interceptor on verb route?

### ISSUE THREAD

**Issue by mobilemindtec** [pedestal/pedestal#714]
Hi,

How can I add an interceptor to the POST customer route without benchmarking GET customer?

My routes are like this:

```[[[ "/api" ^:interceptors [api-interceptors]
       ["/v1"
                ["/" ^:interceptors [my-other-interceptor]
                      {:get customer-api/customer-index
                       :post customer-api/customer-create ; how add interceptor here?
                       :put customer-api/customer-update}]]]]]
```

Thank you for your help!

**Comment by ohpauleez** [comment]
I believe in that route format you do something like:
```
{:post ^:interceptors [interceptor-1 interceptor-2] customer-api/customer-create}
```

You can see a similar route in the [route unit tests](https://github.com/pedestal/pedestal/blob/master/service/test/io/pedestal/http/route_test.clj#L184)

If you switch to the the "table routes" format, the [Pedestal docs on routes](http://pedestal.io/guides/defining-routes) covers that under the "Interceptors" section.

You might also browse through some of the [Pedestal Sample Applications](https://github.com/pedestal/pedestal/tree/master/samples) if you get stuck -- I didn't see anything immediately relevant, but it's a good place to check if you get stuck.

I hope this helps!

**Comment by mobilemindtec** [comment]
Hi, 

Using this syntax gives the following error

`Map literal must contain an even number of forms`

```
["/agreement" 
    ["/" {:put customer-api/customer-update
          :post ^:interceptors [(create-my-interceptor)] customer-api/customer-create}]]

```

**Comment by mobilemindtec** [comment]
It worked like this:

```
["/agreement" 
    ["/" {:put customer-api/customer-update
          :post [^:interceptors [(create-my-interceptor)] customer-api/customer-create}]]]
```
