### ISSUE TITLE
Jetty 9 is end of community support since june 2022 - provide options for Jetty 10 and 11 ?!

### ISSUE THREAD

**Issue by ieugen** [pedestal/pedestal#722]
# Description

> June 1st, 2022 will mark the official End of Community Support for Eclipse Jetty 9.x. 

Full text here:  https://github.com/eclipse/jetty.project/issues/7958

Would it make sense to provide options for Jetty 10 and 11 to help people upgrade / new projects use the newer, stable versions ? 

I think supporting both Jetty 10 and Jetty 11 at the same time makes sense since they use different servlet API's - one uses `javax.` packages and the other uses the new `jakarta.` packages . 

See https://www.eclipse.org/jetty/download.php . 

Thanks,

**Comment by hlship** [comment]
We are deciding whether Jetty 10 or 11 will supplement or replace Jetty 9; this is being deferred to 0.5.12 - which we do not expect to take a full year as with the last few Pedestal releases.

**Comment by ieugen** [comment]
IMO there is no real reason to continue with Jetty 9. 
Both Jetty 10 and 11 should be supported. 
Jetty 9 is replaced by Jetty 10.
Jetty 11 uses new Jakarta namespace (future packages of Servlet API). 

Eclipse plans to support both for the next 3-5 years (if I recall correctly) ?! 
Jetty 9 is EOL since summer.

**Comment by jrdoane** [comment]
Has there been any movement on this issue? Jetty 9 has been out of community support for over a year now and it's only getting older.

**Comment by hlship** [comment]
We're actively working on Jetty 11 / Tomcat 10, which uses the jakarta.* namespaces.  You can track progress in this branch: [jetty11-and-friends](https://github.com/pedestal/pedestal/tree/jetty11-and-friends)

**Comment by brown131** [comment]
We are eagerly awaiting the completion of this issue! :)

**Comment by hlship** [comment]
The jetty part is coming along nicely, but we're a bit stall on Tomcat upgrades to match.  Just a lack of time to work on it.

**Comment by hlship** [comment]
Fixed by #762.
