### ISSUE TITLE
Bug in prefix tree router implementation

### ISSUE THREAD

**Issue by michalwilk123** [pedestal/pedestal#726]
# Description
Bug in prefix tree router implementation. Seems like it does not recognize the "/" sign in the path-params names or the request method.

Quick solution for this would be setting the router field in service map from default `:prefix-tree` to `:linear-search`

## Expected Behavior
To match correct route, returning desirable result

## Actual Behavior
Returns default, blank 404 Exception with body: `Not found`

## Steps to reproduce
Set the route table accordingly
![image](https://user-images.githubusercontent.com/60885424/194778062-cd4c3b7f-b00f-4cba-a2b7-a69bb8129434.png)

Do not change the default :prefix-tree route setting.

Sent POST request to "app/User/user-regular"

# Environment

## Operating System (including version).
Manjaro Linux 
Kernel: 5.10

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Leiningen 2.9.8 on Java 11.0.16.1 OpenJDK 64-Bit Server VM

## Pedestal version
"0.5.10"

**Comment by hlship** [comment]
Is this something you saw in your running server or your tests?  I find your example, `Send POST request to "app/User/user-regular"`, to be suspicious - as per the [Ring Spec](https://github.com/ring-clojure/ring/blob/master/SPEC) the :uri that routing matches on should including the leading slash, and that would presumably explain why the routes did not match.  An example project or Gist would be helpful.

**Comment by michalwilk123** [comment]
I created a blank project and tried to recreate the issue. Still i was not able to do that. I will close the issue. Sorry for wasting anyone's time. The problem was caused probably by not successfully refreshing the map generated by the *expand-routes* function.

**Comment by hlship** [comment]
No problems!

I've recently updated the documentation to go into detail about a REPL workflow that handles reloading of the routing map and interceptor chain and all that.  There's a lot of gotchas that I think are now addressed.  We may (may!) add some helper macros or functions to simplify it all.
