### ISSUE TITLE
Warnings related to : clojure.tools.analyzer.utils/update-vals

### ISSUE THREAD

**Issue by vaibhawc** [pedestal/pedestal#728]
Was just trying it out on repl, but got these weird warnings instead.

**deps.edn**
{:paths ["src"]
 :deps {io.pedestal/pedestal.service {:mvn/version "0.5.10"}
        io.pedestal/pedestal.route {:mvn/version "0.5.10"}
        io.pedestal/pedestal.jetty {:mvn/version "0.5.10"}
        org.slf4j/slf4j-simple {:mvn/version "2.0.3"}
        org.clojure/data.json {:mvn/version "2.4.0"}
        clj-http/clj-http {:mvn/version "3.12.3"}
        environ/environ {:mvn/version "1.2.0"}}}

**repl**
`clj`
`Clojure 1.11.1`
`(ns try (:require [io.pedestal.http :as http]))`
`WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/update-vals`
`WARNING: update-keys already refers to: #'clojure.core/update-keys in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/update-keys`
`WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/update-vals`
`WARNING: update-keys already refers to: #'clojure.core/update-keys in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/update-keys`
`WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer.passes, being replaced by: #'clojure.tools.analyzer.utils/update-vals`
`WARNING: update-vals already refers to: #'clojure.core/update-vals in namespace: clojure.tools.analyzer.passes.uniquify, being replaced by: #'clojure.tools.analyzer.utils/update-vals`
`nil`
`try=> `

**Comment by hlship** [comment]
I believe this was fixed by #729. I just tested with clojure 1.11.1 and pedestal 0.5.11-beta-1 and no warnings.
