### ISSUE TITLE
async interceptors are blocking the chain

### ISSUE THREAD

**Issue by mtsbarbosa** [pedestal/pedestal#740]
# Description
As described in the docs, returning a channel on an `:enter` or `:leave` interceptor map functions, being the value put on that channel the context map should enable async execution.
Maybe I didn't get that properly from the docs, or I'm messing up with the implementation, but looks like the chain waits for the completion of each of the async channels anyway before proceeding to the next interceptor. Is that supposed to be like that?

## Expected Behavior
❔ not sure

## Actual Behavior
each async interceptor awaits for the previous async one completion 

## Steps to reproduce
I've set up an example project [here](https://github.com/mtsbarbosa/bakery) if anyone is interested checking it.   
Here are the code main points:    

interceptors.clj
```clojure
(defn push-async-data
  [context data]
  (assoc-in context [:request :async-data] (conj (get-in context [:request :async-data] [])
                                                 data)))

(def async-interceptor
  {:name  ::async
   :enter (fn [context]
            (let [chan (async/go
                               (do
                                 (Thread/sleep 2000)
                                 (println "channel 1 being put!")
                                 (push-async-data context 42)))]
              (println "exit 1")
              chan))})

(def async-interceptor-2
  {:name  ::async-2
   :enter (fn [context]
            (let [chan (async/go
                               (do
                                 (Thread/sleep 4000)
                                 (println "channel 2 being put!")
                                 (push-async-data context 1917)))]
              (println "exit 2")
              chan))})
```
   
routing + handler
```clojure
(defn take-foo-2
  [request]
  (println "Handler")
  {:status 200 :headers {"Content-Type" "application/json"} :body (:async-data request)})

(def json-take-interceptors [(body-params/body-params)
                             i/async-interceptor
                             i/async-interceptor-2
                             (i/json-out)
                             http/html-body])

(def specs 
         #{["/foo" :get (conj json-interceptors `r.foo/get-foo) :route-name :get-foo]
             ["/take-foo" :get (conj json-take-interceptors `take-foo-2) :route-name :take-foo]
             ["/foo" :post (conj json-interceptors `r.foo/post-foo) :route-name :post-foo]})
```

Current output from `http://localhost:8080/take-foo`
```bash
INFO  org.eclipse.jetty.server.Server  - Started @18368ms
INFO  io.pedestal.http  - {:msg "GET /take-foo", :line 80}
exit 1
channel 1 being put!
exit 2
channel 2 being put!
Handler
```

My expectation:
```bash
INFO  org.eclipse.jetty.server.Server  - Started @18368ms
INFO  io.pedestal.http  - {:msg "GET /take-foo", :line 80}
exit 1
exit 2
channel 1 being put!
channel 2 being put!
Handler
```

# Environment

## Operating System (including version).
`MacOS 13.2.1 (22D68)` 

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
`Leiningen 2.10.0 on Java 11.0.11 OpenJDK 64-Bit Server VM`

## Pedestal version
`0.5.10`

**Comment by ohpauleez** [comment]
I'm always happy to help and I'm glad that all made sense!
Updates to the docs and additional clarification is always helpful for the project and the community.  It's one of the best ways to contribute and help improve the project.

**Comment by hlship** [comment]
I've made [documentation improvements](https://github.com/pedestal/pedestal-docs/commit/8150882c565e1a383fbecb852df3c81667f21178) to more explicitly describe what async behavior is about, and the pitfalls therein.
