### ISSUE TITLE
Remove support for Immutant

### ISSUE THREAD

**Issue by hlship** [pedestal/pedestal#754]
[Immutant](https://github.com/immutant/immutant) has not had a commit in over 6 years (since Jan 2018).  As we look to refresh the version of Jetty, and perhaps Tomcat ... Immutant may be at a dead end for support.  I've reached out on [Slack](https://clojurians.slack.com/archives/C0K65B20P/p1687816716290939) to see if there's any real users that would be locked into Pedestal 0.6.0, but I feel removing Immutant support may be necessary to move forward with any significant improvements.

**Comment by bonkydog** [comment]
[Here's a thread on r/Clojure](https://www.reddit.com/r/Clojure/comments/dhx6b6/deploying_clojure_war_is_immutant_deprecated/) asking if Immutant is dead. It's 4 years old.

[Here's a thread on r/java](https://www.reddit.com/r/java/comments/rpjvjq/do_i_even_care_about_jboss_or_are_there_better/) asking if **JBOSS** is dead. It's from 2 years ago.

The Slack thread you started has a bunch of folks talking about Jetty 10 vs 11. No one even mentions Immutant.

I feel OK about dropping support of for Immutant.

**Comment by bonkydog** [comment]
[Here](https://clojurians.slack.com/archives/C085AR8RE/p1560772063004300) is Toby Crawley, one of the Immutant maintainers, declaring Immutant dead on the Clojurians #immutant channel in June of 2019.

**Comment by ohpauleez** [comment]
I think removing Immutant is fine to do.  If folks were interested/motivated, it could be replaced with a Wildfly or Undertow implementation (since the code would be quite similar).

**Comment by hlship** [comment]
Fixed by #753
