### ISSUE TITLE
There are no tests for websocket support

### ISSUE THREAD

**Issue by hlship** [pedestal/pedestal#756]
Pedestal has long had container-specific websocket support, but is not (well) documented, and has no tests in existing code. The underlying APIs change dramatically between Jetty 9 and Jetty 11.

**Comment by claj** [comment]
There has been discussions on adding a unified websocket interface. A unified WS interface is probably beyond the scope of this ticket. However, a way to test the websocket is to use the java.net.http WebSocket client - probably like hato does:

https://github.com/gnarroway/hato/blob/master/src/hato/websocket.clj
