### ISSUE TITLE
Transit reader broken for some input stream implementations

### ISSUE THREAD

**Issue by raystubbs** [pedestal/pedestal#764]
This check breaks it when running on Helidon/Nima, since their InputStreams always seem to return `0` for `.available`.  It should probably just try to read it without checking, like the others do.

https://github.com/pedestal/pedestal/blob/565d1e670d2af8f5711b2d72a3d524face1b74c8/service/src/io/pedestal/http/body_params.clj#L130

**Comment by hlship** [comment]
JavaDocs do say that InputStream/available returns "an estimate".

**Comment by hlship** [comment]
Fixed by #787
