### ISSUE TITLE
Unable to access the application when running with Docker and io.pedestal/pedestal.service "0.6.1"

### ISSUE THREAD

**Issue by nicolasmnl** [pedestal/pedestal#772]
# Description
Hi, there! I am not sure why, but i recently figured it out that when the pedestal.service library is set to "0.6.1" or latest, and running the application with Docker, the application becomes unavailable from the outside (even locally). However, with the "0.5.3" version of the pedestal.service library, this does not occur and the error vanishes. I haven't tried with every version in between them, but i noticed that there are a lot that have the same problem (0.5.11, 0.5.10, 0.5.9,...)

## Expected Behavior
It should be possible to access the application when running with Docker normally, with the current/latest pedestal.service library, just making a simple `curl localhost:8080` request after running the container.

## Actual Behavior
When building the Docker image and running the container the application becomes unavailable and is not possible to make requests or access any of the application endpoints

## Steps to reproduce
Create a new leiningen project from the pedestal template (from the time of this issue the library is the 0.6.1):
```
lein new pedestal-service the-next-big-server-side-thing
```
Enter the created directory folder and start the server:
```
cd the-next-big-server-side-thing
lein run
```
Make a request to localhost:8080 where the server is running:
```
curl localhost:8080
```
Expected Output:
```
Hello World!
```
Try creating a container using Docker:
```
This will be the default Dockerfile created:

FROM openjdk:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/the-next-big-server-side-thing-0.0.1-SNAPSHOT-standalone.jar /the-next-big-server-side-thing/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/the-next-big-server-side-thing/app.jar"]
```
Create your uberjar:
```
lein uberjar
```
Build and run your image:
```
docker build -t <image-name> .
docker dun -p 8080:8080 <image-name>
```
Make the request:
```
curl localhost:8080
```
Expected Output:
```
curl: (56) Recv failure: Connection reset by peer
```

# Environment
Memory: 16GB
Processor: Intel® Core™ i5-8250U CPU @ 1.60GHz × 8
Graphics: Mesa Intel® UHD Graphics 620 (KBL GT2)
Disk Capacity: 128.0 GB

## Operating System (including version).
OS Name: Ubuntu 20.04.6 LTS Focal
OS Type: 64-bit

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Leiningen 2.10.0 on Java 17.0.8.1 OpenJDK 64-Bit Server VM

## Pedestal version
"0.6.1"

**Comment by lread** [comment]
Probably due to [this change](https://github.com/pedestal/pedestal/blob/f40d7badeab6f2f1fd73509c57a1a1aa030c2623/CHANGELOG.md?plain=1#L98)?

**Comment by nicolasmnl** [comment]
> Probably due to [this change](https://github.com/pedestal/pedestal/blob/f40d7badeab6f2f1fd73509c57a1a1aa030c2623/CHANGELOG.md?plain=1#L98)?

Yep, that's it! Sorry then, i think i missed it
You have to change to ::http/host "0.0.0.0" now
