### ISSUE TITLE
Add configuration for linting using clj-kondo

### ISSUE THREAD

**Issue by vedang** [pedestal/pedestal#780]
Hello maintainers,

It would be great if Pedestal provided `clj-kondo` configuration[^1] in the `io.pedestal` jars which introduce macros. This makes using the macro easier and ensures that `clj-kondo` does not throw false warnings. 

[^1]: Providing `clj-kondo` configuration as part of the project: https://github.com/clj-kondo/clj-kondo/blob/be6efa075a0a2b903ab220ce7c7e61a242bd9126/doc/config.md#exporting-and-importing-configuration

**Comment by hlship** [comment]
Thanks for putting this together; I've taken it further by properly bundling the config files and hooks, integrating a GitHub action to run the linter, and fixing dozens of linter warnings and errors; this was in PR #816
