### ISSUE TITLE
Confusing error message when multiple interceptors have the same name

### ISSUE THREAD

**Issue by achuth10** [pedestal/pedestal#791]
# Description
When you have more than one interceptor with the same name, the error message says "Route names are not unique"
## Expected Behavior
This error message is incorrect as the routes themselves are unique, it's the interceptor names that are incorrectly duplicated.
This is a minor issue I realise but will probably save some time when someone tries to debug such an issue?
Expected error message - "Interceptor names are not unique"
## Actual Behavior
`Execution error (ExceptionInfo) at io.pedestal.http.route.definition/verify-unique-route-names (definition.clj:67).
Route names are not unique`
## Steps to reproduce
;; Declare two interceptors

(def interceptor1
  {:name :interceptor-1
   :enter (fn [ctx])
  })

(def interceptor2
  {:name :interceptor-1 ;; Incorrectly duplicated interceptor name
   :enter (fn [ctx])
  })

And create two different routes with those interceptors
1. "/route1" [interceptor1]
2. "/route2"  [interceptor 2]

## Operating System (including version).
Mac OS V14

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)
Leiningen 2.10.0 on Java 21.0.1 OpenJDK 64-Bit Server VM
## Pedestal version
0.5.10

**Comment by hlship** [comment]
This is because, when failing to identify the route name specifically, Pedestal will derive a route name from the interceptors (I believe it uses the final interceptor), and that is what causes the conflict; you will rarely have the same interceptor stack for two different routes.

**Comment by achuth10** [comment]
Thanks for clarifying!
