### ISSUE TITLE
Jetty 9.x, Logback, and Java 17 Dependency Issues

### ISSUE THREAD

**Issue by brown131** [pedestal/pedestal#801]
There is a cross-dependency issue with Pedestal, Jetty, and Logback in newer versions of Java.

1.  Pedestal 0.6.3 requires Jetty 9.x because it uses an interface (Trie) that does not exist in Jetty 10+
2. Jetty 9.x requires a class (HttpField$Mutable) that no longer exists in Logback after 1.3.*, that is 1.4.*+
3. Logback 1.3.x requires javax.* libraries and not jakarta.* libraries (fixed in Logback 1.4.*) so it cannot be used with Java 17
4. Thus one cannot upgrade to Java 17 using Pedestal 0.6.3 and Logback until Pedestal starts using Jetty 10+

I saw that there was version 0.7.0 that used Jetty 10 but was jettisoned (jetty-soned?) it seems because it had breaking changes. 
However, as shown above, breaking changes are required if you wish to maintain Pedestal going forward. (Or, I suppose, you wish to force users to no longer use Logback.) Nonetheless, Jetty 9.x has not been supported for over a year (https://github.com/jetty/jetty.project/issues/7958) so you should be upgrading to Jetty 10+ anyways!

**Comment by hlship** [comment]
Upgrading Jetty to 11 is in-progress for upcoming Pedestal 0.7.
