### ISSUE TITLE
Pedestal should identify conflicting routes

### ISSUE THREAD

**Issue by hlship** [pedestal/pedestal#842]
Even as of Pedestal 0.7, it is possible to create routes in Pedestal that have conflicts: a wild card in one route will shadow a different, fixed route.  There's example in the documentation about this, and the need to avoid it.

That's insufficient, a router that can have such a conflict should include validation code that doesn't allow routes with such conflicts to be defined.

Even with the linear router, such a conflict is possible, because an early wild-card route may prevent a later static route from being reachable.

Whether this would take the form of a new router, or enhancements to existing routers, is an open question.

**Comment by adityaathalye** [comment]
Hi! The following behaviour tripped me up, as someone trying out pedestal for the first time. I found this issue while trying to figure out what was going on. It seems directly related, so here's what I'm seeing.

As of `0.7.0-beta1`, pedestal does not disambiguate these two paths (excerpt from routes table printed to REPL).

```clojure
:get /item/new           :com.example/new-item-page
:get /item/:item-id/view :com.example/view-item-page
```

Given the overlap of static/parameterised prefix (`/item/new` v/s/ `/item/:item-id:`), I believed the `prefix-tree` router would kick in and disambiguate these. However, in this case, pedestal matches `/item/:item-id/view` but returns "not found" for `/item/new`.

If I change the "view" route to `/item/view/:item-id`, then both routes match and work as expected.

A cursory experiment with `prefix-tree` as found in 0.7.0-beta1 makes me think the router should be able to disambiguate these routes and dispatch accordingly. If I have correctly understood the following, the insert/lookup pair appears to have the necessary information to do so. Or, at least, to complain to me about potentially conflicting routes.

```clojure
(comment
  (require 'io.pedestal.http.route.prefix-tree)

  (def insert io.pedestal.http.route.prefix-tree/insert)

  ;; Try the same routes, in different orders

  (def ptree1 (-> nil
                  (insert "/item/:item-id/view" 1)
                  (insert "/item/new" 2)))

  (def ptree2 (-> nil
                  (insert "/item/new" 1)
                  (insert "/item/:item-id/view" 2)))

  ;; ptree1 looks like this

  {:wild? nil,
   :catch-all? nil,
   :segment "/item/",
   :param nil,
   :payload nil,
   :children
   {":"
    {:wild? true,
     :catch-all? nil,
     :segment ":item-id",
     :param :item-id,
     :payload nil,
     :children
     {"v"
      {:wild? nil,
       :catch-all? nil,
       :segment "view",
       :param nil,
       :payload {:routes [1]},
       :children nil}}},
    "n"
    {:wild? nil,
     :catch-all? nil,
     :segment "new",
     :param nil,
     :payload {:routes [2]},
     :children nil}}}

  ;; ptree2 looks like this

  {:wild? nil,
   :catch-all? nil,
   :segment "/item/",
   :param nil,
   :payload nil,
   :children
   {"n"
    {:wild? nil,
     :catch-all? nil,
     :segment "new",
     :param nil,
     :payload {:routes [1]},
     :children nil},
    ":"
    {:wild? true,
     :catch-all? nil,
     :segment ":item-id",
     :param :item-id,
     :payload nil,
     :children
     {"v"
      {:wild? nil,
       :catch-all? nil,
       :segment "view",
       :param nil,
       :payload {:routes [2]},
       :children nil}}}}}

  (def lookup io.pedestal.http.route.prefix-tree/lookup)

  (lookup ptree1 "/item/new")
  ;; => {:path-params {:item-id "new"}, :payload nil}
  (lookup ptree2 "/item/new")
  ;; => {:path-params {:item-id "new"}, :payload nil}

  (lookup ptree1 "/item/:item-id/view")
  ;; => {:path-params {:item-id ":item-id"}, :payload {:routes [1]}}

  (lookup ptree2 "/item/:item-id/view")
  ;; => {:path-params {:item-id ":item-id"}, :payload {:routes [2]}}

  #_())
