### ISSUE TITLE
Version 0.7.0 breaking changes not listed in changelog

### ISSUE THREAD

**Issue by lucian303** [pedestal/pedestal#865]
# Description

0.7.0 has a few breaking changes not listed in the changelog.

## Expected Behavior

Upgrade to 0.7.0 and the app works.

## Actual Behavior

App doesn't work due to various library changes:

Error 1:
`java.lang.IllegalAccessError: perr does not exist`

In `io.pedestal.internal`, `perr`  is a symbol that's referred to that doesn't exist. It does exist in `[org.clj-commons/pretty "3.0.0"]` if that library is added explicitly but this should be a dependency of pedestal itself or it should be listed in the docs that pretty 3.0.0 must be required first to use pedestal.

Error 2:

The `io.pedestal.interceptor.error` namespace doesn't exist in 0.7.0 but is not mentioned in http://pedestal.io/pedestal/0.7/deprecations.html nor was it deprecated in 0.6.0. What is the replacement for `io.pedestal.interceptor.error/error-dispatch`?

## Steps to reproduce

Upgrade to 0.7.0

# Environment

## Operating System (including version).

PopOS 22.04

## Your current Leiningen or Boot version (`lein --version` or `boot --version`)

Leiningen 2.9.10 on Java 21.0.4 OpenJDK 64-Bit Server VM

## Pedestal version

0.7.0

**Comment by lucian303** [comment]
Adding 
```
[org.clj-commons/pretty "3.0.0"]
```
and
```
[io.pedestal/pedestal.error "0.7.0"]
```

Seems to fix the issues above, though the `error-dispatch` macro leads to this error that previously was not triggered, even when there isn't an exception it catches, so those changes should be documented in the changelog as well.

```
clojure.lang.ExceptionInfo: clojure.lang.ExceptionInfo in Interceptor #Interceptor{} - Response map must have positive integer value for :status
    exception-type: :clojure.lang.ExceptionInfo
      execution-id: 29
       interceptor: "#Interceptor{}"
          response: {:name nil,
                 :enter nil,
                 :leave nil,
                 :error
                 #object[runwp.app.http.authorization$authorization_interceptor$fn__45715 0x664f25cb "runwp.app.http.authorization$authorization_interceptor$fn__45715@664f25cb"]}
             stage: :enter
```

**Comment by hlship** [comment]
Something seems odd here.  Internally at NuBank we build with Leiningen and haven't seen these issues with our internal upgrade to 0.7.0.

pedestal.common does declare a dependency on org.clj-commons/pretty:

https://github.com/pedestal/pedestal/blob/master/common/deps.edn#L13

The CHANGELOG explains how we moved around io.pedestal.interceptor.error:

https://github.com/pedestal/pedestal/blob/0.7.0/CHANGELOG.md?plain=1#L13

Finally, 0.7.0 is both more flexible about the response map, and more picky that it be well structured:

https://github.com/pedestal/pedestal/blob/0.7.0/CHANGELOG.md?plain=1#L16

https://github.com/pedestal/pedestal/pull/835

So I suspect your interceptor was doing something that Pedestal "let slide" in prior versions, but is now being caught and reported.

**Comment by lucian303** [comment]
Sorry, I was looking at this deprecations page instead of the changelog in the repo: http://pedestal.io/pedestal/0.7/deprecations.html

Should `pedestal.common` be explicitly required? In the past I only required `pedestal.service` and `pedestal.jetty` but that did not bring in pretty in v7. I'm also using lein.

@hlship

**Comment by hlship** [comment]
AFAIK you should get pedestal.common as a transitive dependency.
