### ISSUE TITLE
Broken pipe detection is not implemented effectively

### ISSUE THREAD

**Issue by hlship** [pedestal/pedestal#877]
Just commenting on this, that as implemented, the broken pipe detection is not working, since the actual IOException is a few layers down the exception cause chain. I have implemented this as an alternative:

```
(defn- broken-pipe-in-chain? [exception]
  (loop [ex exception]
    (cond
      (nil? ex) false
      (and
       (instance? java.io.IOException ex)
       (= "broken pipe" (string/lower-case (str (ex-message ex)))))
      true
      :else (recur (ex-cause ex)))))
```

_Originally posted by @orestis in https://github.com/pedestal/pedestal/issues/623#issuecomment-2451731038_

**Comment by orestis** [comment]
I think perhaps that `stacktrace/root-cause` might also be worth looking into - it's more than likely that an `IOException` would be at the root.
